In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\chahat\Downloads\employees.csv")
df

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13

In [3]:
df1 = pd.read_csv(r"C:\Users\chahat\Downloads\employee.csv",usecols=['EmployeeID','Name','Gender'])
df1

   EmployeeID              Name  Gender
0        E001     Alice Johnson  Female
1        E002         Bob Smith    Male
2        E003       Carol White  Female
3        E004       David Brown    Male
4        E005      Eva Martinez  Female
5        E006         Frank Lee    Male
6        E007         Grace Kim  Female
7        E008       Henry Davis    Male
8        E009      Irene Wilson  Female
9        E010       Jack Taylor    Male
10       E011      Karen Thomas  Female
11       E012     Liam Anderson    Male
12       E013       Mia Jackson  Female
13       E014        Noah White    Male
14       E015     Olivia Harris  Female
15       E016      Peter Martin    Male
16       E017    Quinn Thompson  Female
17       E018     Rachel Garcia  Female
18       E019   Samuel Martinez    Male
19       E020     Tina Robinson  Female
20       E021         Uma Clark  Female
21       E022  Victor Rodriguez    Male
22       E023       Wendy Lewis  Female
23       E024        Xander Lee    Male
24       E025       Yara Walker  Female
25       E026          Zoe Hall  Female
26       E027       Aaron Young    Male
27       E028        Bella King  Female
28       E029     Carlos Wright    Male
29       E030       Diana Scott  Female
30       E031       Ethan Adams    Male
31       E032       Fiona Baker  Female
32       E033   George Gonzalez    Male
33       E034     Hannah Nelson  Female
34       E035        Ian Carter    Male
35       E036    Julia Mitchell  Female
36       E037       Kevin Perez    Male
37       E038     Laura Roberts  Female
38       E039     Marcus Turner    Male
39       E040    Nancy Phillips  Female
40       E041    Oscar Campbell    Male
41       E042       Paula Evans  Female
42       E043     Quinn Collins    Male
43       E044   Rebecca Stewart  Female
44       E045    Steven Sanchez    Male
45       E046     Teresa Morris  Female
46       E047    Ulysses Rogers    Male
47       E048       Violet Reed  Female
48       E049       Walter Cook    Male
49       E050       Xena Morgan  Female

In [4]:
df2 = pd.read_csv(r"C:\Users\chahat\Downloads\employees.csv",nrows=100)
df2

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13

In [5]:
df3 = pd.read_csv(r"C:\Users\chahat\Downloads\employees.csv",skiprows=[1,2,3,4,5])
df3

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
0,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
1,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
2,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
3,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
4,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
5,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
6,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
7,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
8,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
9,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
10,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
11,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
12,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
13,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
14,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
15,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
16,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
17,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
18,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
19,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
20,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
21,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
22,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
23,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
24,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
25,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
26,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
27,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
28,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
29,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
30,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
31,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
32,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
33,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
34,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13

In [6]:
df4 = pd.read_csv(r"C:\Users\chahat\Downloads\employees_pipe.csv",sep='|')
df4

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,Country,Education,YearsExperience,PerformanceScore,IsManager,ProjectCount,LastPromotionYear
0,E001,Alice Johnson,Engineering,Female,32,95000,2018-03-15,New York,USA,Masters,8,4.5,True,12,2022
1,E002,Bob Smith,Marketing,Male,45,72000,2010-07-22,Chicago,USA,Bachelors,20,3.8,False,5,2019
2,E003,Carol White,HR,Female,28,55000,2021-01-10,Austin,USA,Bachelors,4,4.2,False,3,2023
3,E004,David Brown,Engineering,Male,38,110000,2015-06-01,San Francisco,USA,PhD,14,4.8,True,20,2021
4,E005,Eva Martinez,Finance,Female,35,88000,2017-09-30,Miami,USA,Masters,11,4.1,False,7,2020
5,E006,Frank Lee,Engineering,Male,29,85000,2020-02-14,Seattle,USA,Bachelors,5,3.9,False,9,2023
6,E007,Grace Kim,Marketing,Female,41,68000,2012-11-05,Boston,USA,Masters,17,4.3,True,8,2021
7,E008,Henry Davis,Operations,Male,50,92000,2008-04-18,Denver,USA,Bachelors,25,3.5,True,15,2018
8,E009,Irene Wilson,Finance,Female,33,79000,2019-08-25,Atlanta,USA,Masters,9,4.0,False,6,2022
9,E010,Jack Taylor,HR,Male,27,52000,2022-05-12,Portland,USA,Bachelors,3,3.7,False,2,2023
10,E011,Karen Thomas,Engineering,Female,36,98000,2016-12-03,New York,USA,Masters,12,4.6,False,14,2022
11,E012,Liam Anderson,Sales,Male,42,65000,2011-03-28,Los Angeles,USA,Bachelors,18,3.6,False,10,2019
12,E013,Mia Jackson,Operations,Female,31,73000,2018-10-15,Chicago,USA,Masters,7,4.4,False,11,2022
13,E014,Noah White,Engineering,Male,47,125000,2006-01-20,San Francisco,USA,PhD,22,4.9,True,25,2020
14,E015,Olivia Harris,Marketing,Female,26,58000,2023-03-01,Austin,USA,Bachelors,2,3.8,False,3,2023
15,E016,Peter Martin,Finance,Male,39,91000,2014-07-14,New York,USA,Masters,15,4.2,True,9,2021
16,E017,Quinn Thompson,Sales,Female,34,69000,2017-05-20,Seattle,USA,Bachelors,10,3.9,False,7,2022
17,E018,Rachel Garcia,HR,Female,30,57000,2020-09-08,Miami,USA,Bachelors,6,4.1,False,4,2023
18,E019,Samuel Martinez,Engineering,Male,44,105000,2009-02-28,Boston,USA,Masters,19,4.7,True,18,2020
19,E020,Tina Robinson,Operations,Female,37,80000,2015-11-17,Denver,USA,Bachelors,13,4.0,False,12,2021
20,E021,Uma Clark,Sales,Female,25,60000,2023-06-05,Atlanta,USA,Bachelors,1,3.5,False,2,2023
21,E022,Victor Rodriguez,Engineering,Male,43,115000,2010-04-10,San Francisco,USA,PhD,20,4.8,True,22,2019
22,E023,Wendy Lewis,Finance,Female,52,98000,2005-08-22,Chicago,USA,Masters,27,4.3,True,13,2018
23,E024,Xander Lee,Marketing,Male,28,62000,2021-07-30,New York,USA,Bachelors,4,3.7,False,5,2023
24,E025,Yara Walker,HR,Female,35,60000,2017-01-15,Portland,USA,Masters,11,4.2,False,6,2021
25,E026,Zoe Hall,Engineering,Female,31,90000,2019-04-22,Seattle,USA,Masters,7,4.5,False,10,2022
26,E027,Aaron Young,Operations,Male,48,85000,2007-10-03,Los Angeles,USA,Bachelors,22,3.8,True,16,2019
27,E028,Bella King,Finance,Female,29,77000,2021-02-18,Austin,USA,Masters,5,4.0,False,5,2023
28,E029,Carlos Wright,Sales,Male,40,72000,2013-09-25,Miami,USA,Bachelors,16,3.6,False,9,2020
29,E030,Diana Scott,Engineering,Female,46,118000,2007-05-14,New York,USA,PhD,21,4.9,True,24,2019
30,E031,Ethan Adams,Marketing,Male,33,66000,2018-12-01,Chicago,USA,Bachelors,9,4.0,False,7,2022
31,E032,Fiona Baker,HR,Female,27,54000,2022-08-15,Boston,USA,Bachelors,3,3.9,False,3,2023
32,E033,George Gonzalez,Operations,Male,55,95000,2004-03-28,Denver,USA,Masters,28,4.1,True,18,2017
33,E034,Hannah Nelson,Finance,Female,38,86000,2015-06-30,Seattle,USA,Masters,14,4.4,False,10,2021
34,E035,Ian Carter,Engineering,Male,30,88000,2020-01-06,San Francisco,USA,Masters,6,4.3,False,8,2023
35,E036,Julia Mitchell,Sales,Female,43,74000,2011-11-19,Atlanta,USA,Bachelors,19,3.8,False,12,2020
36,E037,Kevin Perez,Marketing,Male,36,70000,2016-04-25,Los Angeles,USA,Masters,12,4.1,False,8,2021
37,E038,Laura Roberts,Engineering,Female,49,122000,2006-07-11,New York,USA,PhD,23,4.7,True,26,2018
38,E039,Marcus Turner,HR,Male,32,58000,2019-10-20,Austin,USA,Bachelors,8,4.0,False,5,2022
39,E040,Nancy Phillips,Operations,Female,41,82000,2012-02-14,Chicago,USA,Masters,18,4.2,True,14,2020
40,E041,Oscar Campbell,Finance,Male,26,73000,2023-01-09,Miami,USA,Masters,2,3.6,False,3,2023
41,E042,Paula Evans,Sales,Female,37,68000,2016-08-07,Portland,USA,Bachelors,13,3.9,False,9,2021
42,E043,Quinn Collins,Engineering,Male,34,96000,2017-11-28,Boston,USA,Masters,11,4.6,False,13,2022
43,E044,Rebecca Stewart,Marketing,Female,44,75000,2010-05-16,Denver,USA,Masters,20,4.3,True,10,2019
44,E045,Steven Sanchez,Operations,Male,39,88000,2014-09-03,Seattle,USA,Bachelors,15,4.0,False,13,2021
45,E046,Teresa Morris,HR,Female,53,65000,2005-12-27,San Francisco,USA,Masters,28,4.4,True,8,2016
46,E047,Ulysses Rogers,Finance,Male,35,82000,2018-03-21,New York,USA,Bachelors,11,4.1,False,7,2022
47,E048,Violet Reed,Engineering,Female,28,83000,2021-06-14,Chicago,USA,Masters,4,4.4,False,6,2023
48,E049,Walter Cook,Sales,Male,46,78000,2008-01-30,Atlanta,USA,Bachelors,24,3.7,False,14,2018
49,E050,Xena Morgan,Marketing,Female,32,64000,2019-07-09,Los Angeles,USA,Bachelors,8,4.0,False,6,2022

In [7]:
df5 = pd.read_excel(r"C:\Users\chahat\Downloads\employees.xlsx",skiprows=1)
df5

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,Country,Education,YearsExperience,PerformanceScore,IsManager,ProjectCount,LastPromotionYear
0,E001,Alice Johnson,Engineering,Female,32,95000,2018-03-15,New York,USA,Masters,8,4.5,True,12,2022
1,E002,Bob Smith,Marketing,Male,45,72000,2010-07-22,Chicago,USA,Bachelors,20,3.8,False,5,2019
2,E003,Carol White,HR,Female,28,55000,2021-01-10,Austin,USA,Bachelors,4,4.2,False,3,2023
3,E004,David Brown,Engineering,Male,38,110000,2015-06-01,San Francisco,USA,PhD,14,4.8,True,20,2021
4,E005,Eva Martinez,Finance,Female,35,88000,2017-09-30,Miami,USA,Masters,11,4.1,False,7,2020
5,E006,Frank Lee,Engineering,Male,29,85000,2020-02-14,Seattle,USA,Bachelors,5,3.9,False,9,2023
6,E007,Grace Kim,Marketing,Female,41,68000,2012-11-05,Boston,USA,Masters,17,4.3,True,8,2021
7,E008,Henry Davis,Operations,Male,50,92000,2008-04-18,Denver,USA,Bachelors,25,3.5,True,15,2018
8,E009,Irene Wilson,Finance,Female,33,79000,2019-08-25,Atlanta,USA,Masters,9,4.0,False,6,2022
9,E010,Jack Taylor,HR,Male,27,52000,2022-05-12,Portland,USA,Bachelors,3,3.7,False,2,2023
10,E011,Karen Thomas,Engineering,Female,36,98000,2016-12-03,New York,USA,Masters,12,4.6,False,14,2022
11,E012,Liam Anderson,Sales,Male,42,65000,2011-03-28,Los Angeles,USA,Bachelors,18,3.6,False,10,2019
12,E013,Mia Jackson,Operations,Female,31,73000,2018-10-15,Chicago,USA,Masters,7,4.4,False,11,2022
13,E014,Noah White,Engineering,Male,47,125000,2006-01-20,San Francisco,USA,PhD,22,4.9,True,25,2020
14,E015,Olivia Harris,Marketing,Female,26,58000,2023-03-01,Austin,USA,Bachelors,2,3.8,False,3,2023
15,E016,Peter Martin,Finance,Male,39,91000,2014-07-14,New York,USA,Masters,15,4.2,True,9,2021
16,E017,Quinn Thompson,Sales,Female,34,69000,2017-05-20,Seattle,USA,Bachelors,10,3.9,False,7,2022
17,E018,Rachel Garcia,HR,Female,30,57000,2020-09-08,Miami,USA,Bachelors,6,4.1,False,4,2023
18,E019,Samuel Martinez,Engineering,Male,44,105000,2009-02-28,Boston,USA,Masters,19,4.7,True,18,2020
19,E020,Tina Robinson,Operations,Female,37,80000,2015-11-17,Denver,USA,Bachelors,13,4.0,False,12,2021
20,E021,Uma Clark,Sales,Female,25,60000,2023-06-05,Atlanta,USA,Bachelors,1,3.5,False,2,2023
21,E022,Victor Rodriguez,Engineering,Male,43,115000,2010-04-10,San Francisco,USA,PhD,20,4.8,True,22,2019
22,E023,Wendy Lewis,Finance,Female,52,98000,2005-08-22,Chicago,USA,Masters,27,4.3,True,13,2018
23,E024,Xander Lee,Marketing,Male,28,62000,2021-07-30,New York,USA,Bachelors,4,3.7,False,5,2023
24,E025,Yara Walker,HR,Female,35,60000,2017-01-15,Portland,USA,Masters,11,4.2,False,6,2021
25,E026,Zoe Hall,Engineering,Female,31,90000,2019-04-22,Seattle,USA,Masters,7,4.5,False,10,2022
26,E027,Aaron Young,Operations,Male,48,85000,2007-10-03,Los Angeles,USA,Bachelors,22,3.8,True,16,2019
27,E028,Bella King,Finance,Female,29,77000,2021-02-18,Austin,USA,Masters,5,4.0,False,5,2023
28,E029,Carlos Wright,Sales,Male,40,72000,2013-09-25,Miami,USA,Bachelors,16,3.6,False,9,2020
29,E030,Diana Scott,Engineering,Female,46,118000,2007-05-14,New York,USA,PhD,21,4.9,True,24,2019
30,E031,Ethan Adams,Marketing,Male,33,66000,2018-12-01,Chicago,USA,Bachelors,9,4.0,False,7,2022
31,E032,Fiona Baker,HR,Female,27,54000,2022-08-15,Boston,USA,Bachelors,3,3.9,False,3,2023
32,E033,George Gonzalez,Operations,Male,55,95000,2004-03-28,Denver,USA,Masters,28,4.1,True,18,2017
33,E034,Hannah Nelson,Finance,Female,38,86000,2015-06-30,Seattle,USA,Masters,14,4.4,False,10,2021
34,E035,Ian Carter,Engineering,Male,30,88000,2020-01-06,San Francisco,USA,Masters,6,4.3,False,8,2023
35,E036,Julia Mitchell,Sales,Female,43,74000,2011-11-19,Atlanta,USA,Bachelors,19,3.8,False,12,2020
36,E037,Kevin Perez,Marketing,Male,36,70000,2016-04-25,Los Angeles,USA,Masters,12,4.1,False,8,2021
37,E038,Laura Roberts,Engineering,Female,49,122000,2006-07-11,New York,USA,PhD,23,4.7,True,26,2018
38,E039,Marcus Turner,HR,Male,32,58000,2019-10-20,Austin,USA,Bachelors,8,4.0,False,5,2022
39,E040,Nancy Phillips,Operations,Female,41,82000,2012-02-14,Chicago,USA,Masters,18,4.2,True,14,2020
40,E041,Oscar Campbell,Finance,Male,26,73000,2023-01-09,Miami,USA,Masters,2,3.6,False,3,2023
41,E042,Paula Evans,Sales,Female,37,68000,2016-08-07,Portland,USA,Bachelors,13,3.9,False,9,2021
42,E043,Quinn Collins,Engineering,Male,34,96000,2017-11-28,Boston,USA,Masters,11,4.6,False,13,2022
43,E044,Rebecca Stewart,Marketing,Female,44,75000,2010-05-16,Denver,USA,Masters,20,4.3,True,10,2019
44,E045,Steven Sanchez,Operations,Male,39,88000,2014-09-03,Seattle,USA,Bachelors,15,4.0,False,13,2021
45,E046,Teresa Morris,HR,Female,53,65000,2005-12-27,San Francisco,USA,Masters,28,4.4,True,8,2016
46,E047,Ulysses Rogers,Finance,Male,35,82000,2018-03-21,New York,USA,Bachelors,11,4.1,False,7,2022
47,E048,Violet Reed,Engineering,Female,28,83000,2021-06-14,Chicago,USA,Masters,4,4.4,False,6,2023
48,E049,Walter Cook,Sales,Male,46,78000,2008-01-30,Atlanta,USA,Bachelors,24,3.7,False,14,2018
49,E050,Xena Morgan,Marketing,Female,32,64000,2019-07-09,Los Angeles,USA,Bachelors,8,4.0,False,6,2022

In [8]:
df6 = pd.read_json(r"C:\Users\chahat\Downloads\employees.json")
df6

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,Country,Education,YearsExperience,PerformanceScore,IsManager,ProjectCount,LastPromotionYear
0,E001,Alice Johnson,Engineering,Female,32,95000,2018-03-15,New York,USA,Masters,8,4.5,True,12,2022
1,E002,Bob Smith,Marketing,Male,45,72000,2010-07-22,Chicago,USA,Bachelors,20,3.8,False,5,2019
2,E003,Carol White,HR,Female,28,55000,2021-01-10,Austin,USA,Bachelors,4,4.2,False,3,2023
3,E004,David Brown,Engineering,Male,38,110000,2015-06-01,San Francisco,USA,PhD,14,4.8,True,20,2021
4,E005,Eva Martinez,Finance,Female,35,88000,2017-09-30,Miami,USA,Masters,11,4.1,False,7,2020
5,E006,Frank Lee,Engineering,Male,29,85000,2020-02-14,Seattle,USA,Bachelors,5,3.9,False,9,2023
6,E007,Grace Kim,Marketing,Female,41,68000,2012-11-05,Boston,USA,Masters,17,4.3,True,8,2021
7,E008,Henry Davis,Operations,Male,50,92000,2008-04-18,Denver,USA,Bachelors,25,3.5,True,15,2018
8,E009,Irene Wilson,Finance,Female,33,79000,2019-08-25,Atlanta,USA,Masters,9,4.0,False,6,2022
9,E010,Jack Taylor,HR,Male,27,52000,2022-05-12,Portland,USA,Bachelors,3,3.7,False,2,2023
10,E011,Karen Thomas,Engineering,Female,36,98000,2016-12-03,New York,USA,Masters,12,4.6,False,14,2022
11,E012,Liam Anderson,Sales,Male,42,65000,2011-03-28,Los Angeles,USA,Bachelors,18,3.6,False,10,2019
12,E013,Mia Jackson,Operations,Female,31,73000,2018-10-15,Chicago,USA,Masters,7,4.4,False,11,2022
13,E014,Noah White,Engineering,Male,47,125000,2006-01-20,San Francisco,USA,PhD,22,4.9,True,25,2020
14,E015,Olivia Harris,Marketing,Female,26,58000,2023-03-01,Austin,USA,Bachelors,2,3.8,False,3,2023
15,E016,Peter Martin,Finance,Male,39,91000,2014-07-14,New York,USA,Masters,15,4.2,True,9,2021
16,E017,Quinn Thompson,Sales,Female,34,69000,2017-05-20,Seattle,USA,Bachelors,10,3.9,False,7,2022
17,E018,Rachel Garcia,HR,Female,30,57000,2020-09-08,Miami,USA,Bachelors,6,4.1,False,4,2023
18,E019,Samuel Martinez,Engineering,Male,44,105000,2009-02-28,Boston,USA,Masters,19,4.7,True,18,2020
19,E020,Tina Robinson,Operations,Female,37,80000,2015-11-17,Denver,USA,Bachelors,13,4.0,False,12,2021
20,E021,Uma Clark,Sales,Female,25,60000,2023-06-05,Atlanta,USA,Bachelors,1,3.5,False,2,2023
21,E022,Victor Rodriguez,Engineering,Male,43,115000,2010-04-10,San Francisco,USA,PhD,20,4.8,True,22,2019
22,E023,Wendy Lewis,Finance,Female,52,98000,2005-08-22,Chicago,USA,Masters,27,4.3,True,13,2018
23,E024,Xander Lee,Marketing,Male,28,62000,2021-07-30,New York,USA,Bachelors,4,3.7,False,5,2023
24,E025,Yara Walker,HR,Female,35,60000,2017-01-15,Portland,USA,Masters,11,4.2,False,6,2021
25,E026,Zoe Hall,Engineering,Female,31,90000,2019-04-22,Seattle,USA,Masters,7,4.5,False,10,2022
26,E027,Aaron Young,Operations,Male,48,85000,2007-10-03,Los Angeles,USA,Bachelors,22,3.8,True,16,2019
27,E028,Bella King,Finance,Female,29,77000,2021-02-18,Austin,USA,Masters,5,4.0,False,5,2023
28,E029,Carlos Wright,Sales,Male,40,72000,2013-09-25,Miami,USA,Bachelors,16,3.6,False,9,2020
29,E030,Diana Scott,Engineering,Female,46,118000,2007-05-14,New York,USA,PhD,21,4.9,True,24,2019
30,E031,Ethan Adams,Marketing,Male,33,66000,2018-12-01,Chicago,USA,Bachelors,9,4.0,False,7,2022
31,E032,Fiona Baker,HR,Female,27,54000,2022-08-15,Boston,USA,Bachelors,3,3.9,False,3,2023
32,E033,George Gonzalez,Operations,Male,55,95000,2004-03-28,Denver,USA,Masters,28,4.1,True,18,2017
33,E034,Hannah Nelson,Finance,Female,38,86000,2015-06-30,Seattle,USA,Masters,14,4.4,False,10,2021
34,E035,Ian Carter,Engineering,Male,30,88000,2020-01-06,San Francisco,USA,Masters,6,4.3,False,8,2023
35,E036,Julia Mitchell,Sales,Female,43,74000,2011-11-19,Atlanta,USA,Bachelors,19,3.8,False,12,2020
36,E037,Kevin Perez,Marketing,Male,36,70000,2016-04-25,Los Angeles,USA,Masters,12,4.1,False,8,2021
37,E038,Laura Roberts,Engineering,Female,49,122000,2006-07-11,New York,USA,PhD,23,4.7,True,26,2018
38,E039,Marcus Turner,HR,Male,32,58000,2019-10-20,Austin,USA,Bachelors,8,4.0,False,5,2022
39,E040,Nancy Phillips,Operations,Female,41,82000,2012-02-14,Chicago,USA,Masters,18,4.2,True,14,2020
40,E041,Oscar Campbell,Finance,Male,26,73000,2023-01-09,Miami,USA,Masters,2,3.6,False,3,2023
41,E042,Paula Evans,Sales,Female,37,68000,2016-08-07,Portland,USA,Bachelors,13,3.9,False,9,2021
42,E043,Quinn Collins,Engineering,Male,34,96000,2017-11-28,Boston,USA,Masters,11,4.6,False,13,2022
43,E044,Rebecca Stewart,Marketing,Female,44,75000,2010-05-16,Denver,USA,Masters,20,4.3,True,10,2019
44,E045,Steven Sanchez,Operations,Male,39,88000,2014-09-03,Seattle,USA,Bachelors,15,4.0,False,13,2021
45,E046,Teresa Morris,HR,Female,53,65000,2005-12-27,San Francisco,USA,Masters,28,4.4,True,8,2016
46,E047,Ulysses Rogers,Finance,Male,35,82000,2018-03-21,New York,USA,Bachelors,11,4.1,False,7,2022
47,E048,Violet Reed,Engineering,Female,28,83000,2021-06-14,Chicago,USA,Masters,4,4.4,False,6,2023
48,E049,Walter Cook,Sales,Male,46,78000,2008-01-30,Atlanta,USA,Bachelors,24,3.7,False,14,2018
49,E050,Xena Morgan,Marketing,Female,32,64000,2019-07-09,Los Angeles,USA,Bachelors,8,4.0,False,6,2022

In [9]:
df.head(5)

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18

In [10]:
df.tail(10)

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13

In [11]:
df.ndim

2

In [12]:
df.shape

(40, 9)

In [13]:
df.columns

Index(['emp_id', 'name', 'department', 'city', 'salary', 'experience_years',
       'performance_score', 'age', 'joining_date'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   emp_id             40 non-null     int64
 1   name               40 non-null     object
 2   department         40 non-null     object
 3   city               40 non-null     object
 4   salary             40 non-null     int64
 5   experience_years   40 non-null     int64
 6   performance_score  40 non-null     float64
 7   age                40 non-null     int64
 8   joining_date       40 non-null     object
dtypes: float64(1), int64(4), object(4)
memory usage: 2.9+ KB

In [15]:
df.describe()

,emp_id,salary,experience_years,performance_score,age
count,40.000000,40.000000,40.000000,40.000000,40.000000
mean,120.500000,81775.000000,7.275000,80.595000,31.050000
std,11.690452,19163.918421,3.381606,8.916362,4.031606
min,101.000000,53000.000000,2.000000,63.400000,24.000000
25%,110.750000,66500.000000,4.750000,74.025000,27.750000
50%,120.500000,81500.000000,7.000000,81.200000,31.000000
75%,130.250000,94250.000000,9.250000,87.475000,33.250000
max,140.000000,125000.000000,15.000000,95.300000,40.000000

In [16]:
df.describe(include='object')

              name   department    city joining_date
count           40           40      40           40
unique          40            4       8           40
top     Aarav Shah  Engineering  Mumbai   2016-03-15
freq             1           11       8            1

In [17]:
for i in df:
    print(df[i].unique())

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140]
['Aarav Shah' 'Priya Mehta' 'Rohan Verma' 'Sneha Patel' 'Karan Joshi'
 'Divya Nair' 'Amit Kumar' 'Pooja Singh' 'Raj Malhotra' 'Ananya Gupta'
 'Vikram Rao' 'Meera Iyer' 'Suresh Das' 'Lakshmi Pillai' 'Nikhil Sharma'
 'Tanya Bose' 'Arjun Menon' 'Kavya Reddy' 'Manish Tiwari' 'Deepika Saxena'
 'Rahul Choudhury' 'Shreya Bhatt' 'Varun Agarwal' 'Nisha Kapoor'
 'Siddharth Jain' 'Ankita Desai' 'Mohit Pandey' 'Ritu Sinha'
 'Gaurav Mishra' 'Priyanka Khanna' 'Aditya Bansal' 'Swati Dubey'
 'Harsh Tripathi' 'Pallavi Shukla' 'Rohit Chandra' 'Neha Kulkarni'
 'Vivek Srivastava' 'Ayesha Khan' 'Saurabh Garg' 'Mona Chopra']
['Engineering' 'Marketing' 'HR' 'Finance']
['Mumbai' 'Delhi' 'Bangalore' 'Surat' 'Chennai' 'Hyderabad' 'Pune'
 'Kolkata']
[ 95000  72000 110000  58000  87000  68000 125000  91000  62000 105000
  75000  83000  98000  55000  70000  89000 115000  60000  65000  94000
  88000  53000  78000  86000 102000  57000  73000  80000 119000  61000
  67000  92000 107000  59000  71000  85000  96000  56000  76000]
[ 8  5 12  3  7  4 15  9  6 11 10  2 13 14]
[88.5 76.2 92.1 69.8 83.4 74.5 95.3 85.7 71.3 90.6 79.1 81.9 89.4 65.2
 77.8 84.2 93.7 68.5 72.6 87.3 86.  63.4 80.5 82.8 91.2 67.1 78.3 80.
 94.5 70.9 75.  86.8 91.8 69.2 76.9 83.1 88.  66.7 79.6 84.9]
[32 28 36 26 31 27 40 33 30 35 29 34 25 38 24 39 37]
['2016-03-15' '2019-07-22' '2012-01-10' '2021-06-01' '2017-09-18'
 '2020-04-11' '2009-11-05' '2015-02-28' '2018-08-14' '2013-05-20'
 '2018-12-03' '2016-07-17' '2014-03-09' '2022-01-25' '2019-10-30'
 '2015-06-12' '2011-04-22' '2020-09-08' '2021-03-17' '2014-08-05'
 '2016-11-19' '2022-07-14' '2017-02-28' '2016-04-03' '2013-09-16'
 '2021-11-07' '2018-05-23' '2017-07-11' '2010-02-14' '2019-04-29'
 '2020-01-15' '2014-10-22' '2012-06-30' '2020-07-06' '2019-01-18'
 '2016-09-24' '2015-12-01' '2021-08-19' '2018-03-07' '2015-10-13']

In [18]:
df.describe(include='object')

              name   department    city joining_date
count           40           40      40           40
unique          40            4       8           40
top     Aarav Shah  Engineering  Mumbai   2016-03-15
freq             1           11       8            1

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   emp_id             40 non-null     int64
 1   name               40 non-null     object
 2   department         40 non-null     object
 3   city               40 non-null     object
 4   salary             40 non-null     int64
 5   experience_years   40 non-null     int64
 6   performance_score  40 non-null     float64
 7   age                40 non-null     int64
 8   joining_date       40 non-null     object
dtypes: float64(1), int64(4), object(4)
memory usage: 2.9+ KB

In [20]:
df.sample(n=2)

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18

In [21]:
data_report = pd.DataFrame({
    'columns':df.columns,
    'data types':df.dtypes.values,
    'missing values':df.isnull().sum().values,
    'missing%':(df.isnull().sum()/len(df))*100,
    'unique values':df.nunique().values
})
data_report

,columns,data types,missing values,missing%,unique values
emp_id,emp_id,int64,0,0.0,40
name,name,object,0,0.0,40
department,department,object,0,0.0,4
city,city,object,0,0.0,8
salary,salary,int64,0,0.0,39
experience_years,experience_years,int64,0,0.0,14
performance_score,performance_score,float64,0,0.0,40
age,age,int64,0,0.0,17
joining_date,joining_date,object,0,0.0,40

In [22]:
import pandas as pd
import numpy as np
df7 = pd.read_csv(r"C:\Users\chahat\Downloads\students_dataset.csv")
df7.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'City', 'State', 'Department',
       'Score', 'Grade', 'Attendance', 'Fee_Paid', 'Enrollment_Date', 'GPA',
       'Scholarship'],
      dtype='object')

In [23]:
df7['StudentID']

0     S001
1     S002
2     S003
3     S004
4     S005
5     S006
6     S007
7     S008
8     S009
9     S010
10    S011
11    S012
12    S013
13    S014
14    S015
15    S016
16    S017
17    S018
18    S019
19    S020
20    S021
21    S022
22    S023
23    S024
24    S025
Name: StudentID, dtype: object

In [24]:
df7[['Name','Age']]

               Name  Age
0        Aarav Shah   20
1       Priya Mehta   22
2       Rohan Verma   21
3       Sneha Patel   23
4       Karan Joshi   20
5      Anjali Singh   24
6       Vikram Nair   22
7         Divya Rao   21
8       Arjun Kumar   25
9      Pooja Sharma   20
10     Nikhil Gupta   23
11       Riya Desai   22
12     Aditya Patil   21
13       Kavya Iyer   24
14     Rahul Tiwari   20
15     Meera Pillai   22
16    Siddharth Roy   23
17   Tanvi Kulkarni   21
18     Hardik Bhatt   24
19    Nisha Agarwal   20
20        Yash Modi   22
21     Swati Mishra   25
22       Dev Pandey   21
23   Kritika Saxena   23
24  Manav Choudhary   20

In [25]:
df.loc[0:2]

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10

In [26]:
df7.iloc[2:4]

,StudentID,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
2,S003,Rohan Verma,21,Male,Mumbai,Maharashtra,Physics,72,C,85.0,No,2022-07-15,2.8,No
3,S004,Sneha Patel,23,Female,Surat,Gujarat,Computer Science,81,B,89.5,Yes,2020-07-18,3.2,No

In [27]:
df7.set_index('StudentID',inplace=True)

In [28]:
df7.loc['S001':'S003']

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S001,Aarav Shah,20,Male,Surat,Gujarat,Computer Science,88,B,92.5,Yes,2022-07-15,3.5,No
S002,Priya Mehta,22,Female,Ahmedabad,Gujarat,Mathematics,95,A,98.0,Yes,2021-07-20,3.9,Yes
S003,Rohan Verma,21,Male,Mumbai,Maharashtra,Physics,72,C,85.0,No,2022-07-15,2.8,No

In [29]:
df7.iloc[1:4]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S002,Priya Mehta,22,Female,Ahmedabad,Gujarat,Mathematics,95,A,98.0,Yes,2021-07-20,3.9,Yes
S003,Rohan Verma,21,Male,Mumbai,Maharashtra,Physics,72,C,85.0,No,2022-07-15,2.8,No
S004,Sneha Patel,23,Female,Surat,Gujarat,Computer Science,81,B,89.5,Yes,2020-07-18,3.2,No

In [30]:
df7[df7['Age'] > 18]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S001,Aarav Shah,20,Male,Surat,Gujarat,Computer Science,88,B,92.5,Yes,2022-07-15,3.5,No
S002,Priya Mehta,22,Female,Ahmedabad,Gujarat,Mathematics,95,A,98.0,Yes,2021-07-20,3.9,Yes
S003,Rohan Verma,21,Male,Mumbai,Maharashtra,Physics,72,C,85.0,No,2022-07-15,2.8,No
S004,Sneha Patel,23,Female,Surat,Gujarat,Computer Science,81,B,89.5,Yes,2020-07-18,3.2,No
S005,Karan Joshi,20,Male,Pune,Maharashtra,Chemistry,65,D,78.0,No,2022-07-15,2.5,No
S006,Anjali Singh,24,Female,Delhi,Delhi,Mathematics,91,A,95.0,Yes,2019-07-22,3.7,Yes
S007,Vikram Nair,22,Male,Bangalore,Karnataka,Physics,78,B,88.0,Yes,2021-07-20,3.1,No
S008,Divya Rao,21,Female,Chennai,Tamil Nadu,Chemistry,84,B,91.0,Yes,2022-07-15,3.4,Yes
S009,Arjun Kumar,25,Male,Hyderabad,Telangana,Computer Science,90,A,96.0,Yes,2019-07-22,3.8,Yes
S010,Pooja Sharma,20,Female,Jaipur,Rajasthan,Mathematics,55,F,70.0,No,2022-07-15,2.1,No
S011,Nikhil Gupta,23,Male,Surat,Gujarat,Physics,77,C,83.0,Yes,2020-07-18,3.0,No
S012,Riya Desai,22,Female,Vadodara,Gujarat,Computer Science,93,A,97.0,Yes,2021-07-20,3.8,Yes
S013,Aditya Patil,21,Male,Nashik,Maharashtra,Chemistry,69,D,80.0,No,2022-07-15,2.6,No
S014,Kavya Iyer,24,Female,Kochi,Kerala,Mathematics,87,B,90.0,Yes,2020-07-18,3.4,No
S015,Rahul Tiwari,20,Male,Lucknow,Uttar Pradesh,Computer Science,74,C,82.0,Yes,2022-07-15,2.9,No
S016,Meera Pillai,22,Female,Thiruvananthapuram,Kerala,Physics,96,A,99.0,Yes,2021-07-20,4.0,Yes
S017,Siddharth Roy,23,Male,Kolkata,West Bengal,Chemistry,62,D,75.0,No,2020-07-18,2.4,No
S018,Tanvi Kulkarni,21,Female,Pune,Maharashtra,Computer Science,85,B,92.0,Yes,2022-07-15,3.3,No
S019,Hardik Bhatt,24,Male,Surat,Gujarat,Mathematics,79,C,86.0,Yes,2019-07-22,3.1,No
S020,Nisha Agarwal,20,Female,Agra,Uttar Pradesh,Physics,58,F,68.0,No,2022-07-15,2.2,No
S021,Yash Modi,22,Male,Gandhinagar,Gujarat,Computer Science,92,A,94.0,Yes,2021-07-20,3.7,Yes
S022,Swati Mishra,25,Female,Bhopal,Madhya Pradesh,Chemistry,83,B,89.0,Yes,2019-07-22,3.3,Yes
S023,Dev Pandey,21,Male,Varanasi,Uttar Pradesh,Mathematics,70,C,81.0,No,2022-07-15,2.7,No
S024,Kritika Saxena,23,Female,Indore,Madhya Pradesh,Computer Science,88,B,93.0,Yes,2020-07-18,3.5,No
S025,Manav Choudhary,20,Male,Chandigarh,Punjab,Physics,75,C,84.0,Yes,2022-07-15,3.0,No

In [31]:
df7[(df7['Age'] > 18) & (df7['City']=='Surat')]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S001,Aarav Shah,20,Male,Surat,Gujarat,Computer Science,88,B,92.5,Yes,2022-07-15,3.5,No
S004,Sneha Patel,23,Female,Surat,Gujarat,Computer Science,81,B,89.5,Yes,2020-07-18,3.2,No
S011,Nikhil Gupta,23,Male,Surat,Gujarat,Physics,77,C,83.0,Yes,2020-07-18,3.0,No
S019,Hardik Bhatt,24,Male,Surat,Gujarat,Mathematics,79,C,86.0,Yes,2019-07-22,3.1,No

In [32]:
df7[(df7['Score'] > 90) & (df7['Scholarship']=='Yes')]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S002,Priya Mehta,22,Female,Ahmedabad,Gujarat,Mathematics,95,A,98.0,Yes,2021-07-20,3.9,Yes
S006,Anjali Singh,24,Female,Delhi,Delhi,Mathematics,91,A,95.0,Yes,2019-07-22,3.7,Yes
S012,Riya Desai,22,Female,Vadodara,Gujarat,Computer Science,93,A,97.0,Yes,2021-07-20,3.8,Yes
S016,Meera Pillai,22,Female,Thiruvananthapuram,Kerala,Physics,96,A,99.0,Yes,2021-07-20,4.0,Yes
S021,Yash Modi,22,Male,Gandhinagar,Gujarat,Computer Science,92,A,94.0,Yes,2021-07-20,3.7,Yes

In [33]:
df7[(df7['Score'] > 90) | (df7['Scholarship']=='Yes')]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S002,Priya Mehta,22,Female,Ahmedabad,Gujarat,Mathematics,95,A,98.0,Yes,2021-07-20,3.9,Yes
S006,Anjali Singh,24,Female,Delhi,Delhi,Mathematics,91,A,95.0,Yes,2019-07-22,3.7,Yes
S008,Divya Rao,21,Female,Chennai,Tamil Nadu,Chemistry,84,B,91.0,Yes,2022-07-15,3.4,Yes
S009,Arjun Kumar,25,Male,Hyderabad,Telangana,Computer Science,90,A,96.0,Yes,2019-07-22,3.8,Yes
S012,Riya Desai,22,Female,Vadodara,Gujarat,Computer Science,93,A,97.0,Yes,2021-07-20,3.8,Yes
S016,Meera Pillai,22,Female,Thiruvananthapuram,Kerala,Physics,96,A,99.0,Yes,2021-07-20,4.0,Yes
S021,Yash Modi,22,Male,Gandhinagar,Gujarat,Computer Science,92,A,94.0,Yes,2021-07-20,3.7,Yes
S022,Swati Mishra,25,Female,Bhopal,Madhya Pradesh,Chemistry,83,B,89.0,Yes,2019-07-22,3.3,Yes

In [34]:
df7[~((df7['Score'] > 90) & (df7['Scholarship']=='Yes'))]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S001,Aarav Shah,20,Male,Surat,Gujarat,Computer Science,88,B,92.5,Yes,2022-07-15,3.5,No
S003,Rohan Verma,21,Male,Mumbai,Maharashtra,Physics,72,C,85.0,No,2022-07-15,2.8,No
S004,Sneha Patel,23,Female,Surat,Gujarat,Computer Science,81,B,89.5,Yes,2020-07-18,3.2,No
S005,Karan Joshi,20,Male,Pune,Maharashtra,Chemistry,65,D,78.0,No,2022-07-15,2.5,No
S007,Vikram Nair,22,Male,Bangalore,Karnataka,Physics,78,B,88.0,Yes,2021-07-20,3.1,No
S008,Divya Rao,21,Female,Chennai,Tamil Nadu,Chemistry,84,B,91.0,Yes,2022-07-15,3.4,Yes
S009,Arjun Kumar,25,Male,Hyderabad,Telangana,Computer Science,90,A,96.0,Yes,2019-07-22,3.8,Yes
S010,Pooja Sharma,20,Female,Jaipur,Rajasthan,Mathematics,55,F,70.0,No,2022-07-15,2.1,No
S011,Nikhil Gupta,23,Male,Surat,Gujarat,Physics,77,C,83.0,Yes,2020-07-18,3.0,No
S013,Aditya Patil,21,Male,Nashik,Maharashtra,Chemistry,69,D,80.0,No,2022-07-15,2.6,No
S014,Kavya Iyer,24,Female,Kochi,Kerala,Mathematics,87,B,90.0,Yes,2020-07-18,3.4,No
S015,Rahul Tiwari,20,Male,Lucknow,Uttar Pradesh,Computer Science,74,C,82.0,Yes,2022-07-15,2.9,No
S017,Siddharth Roy,23,Male,Kolkata,West Bengal,Chemistry,62,D,75.0,No,2020-07-18,2.4,No
S018,Tanvi Kulkarni,21,Female,Pune,Maharashtra,Computer Science,85,B,92.0,Yes,2022-07-15,3.3,No
S019,Hardik Bhatt,24,Male,Surat,Gujarat,Mathematics,79,C,86.0,Yes,2019-07-22,3.1,No
S020,Nisha Agarwal,20,Female,Agra,Uttar Pradesh,Physics,58,F,68.0,No,2022-07-15,2.2,No
S022,Swati Mishra,25,Female,Bhopal,Madhya Pradesh,Chemistry,83,B,89.0,Yes,2019-07-22,3.3,Yes
S023,Dev Pandey,21,Male,Varanasi,Uttar Pradesh,Mathematics,70,C,81.0,No,2022-07-15,2.7,No
S024,Kritika Saxena,23,Female,Indore,Madhya Pradesh,Computer Science,88,B,93.0,Yes,2020-07-18,3.5,No
S025,Manav Choudhary,20,Male,Chandigarh,Punjab,Physics,75,C,84.0,Yes,2022-07-15,3.0,No

In [35]:
df['name'].isin(['Chahat Vora']).unique()

array([False])

In [36]:
df7['Name'].isin(['Dev Pandey']).unique()

array([False,  True])

In [37]:
df7['Score'].between(95,100)

StudentID
S001    False
S002     True
S003    False
S004    False
S005    False
S006    False
S007    False
S008    False
S009    False
S010    False
S011    False
S012    False
S013    False
S014    False
S015    False
S016     True
S017    False
S018    False
S019    False
S020    False
S021    False
S022    False
S023    False
S024    False
S025    False
Name: Score, dtype: bool

In [38]:
df7.query("Name=='Dev Pandey'")

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S023,Dev Pandey,21,Male,Varanasi,Uttar Pradesh,Mathematics,70,C,81.0,No,2022-07-15,2.7,No

In [39]:
df7[df7.isna()]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df7[~df7.isna()]

,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
StudentID,,,,,,,,,,,,,
S001,Aarav Shah,20,Male,Surat,Gujarat,Computer Science,88,B,92.5,Yes,2022-07-15,3.5,No
S002,Priya Mehta,22,Female,Ahmedabad,Gujarat,Mathematics,95,A,98.0,Yes,2021-07-20,3.9,Yes
S003,Rohan Verma,21,Male,Mumbai,Maharashtra,Physics,72,C,85.0,No,2022-07-15,2.8,No
S004,Sneha Patel,23,Female,Surat,Gujarat,Computer Science,81,B,89.5,Yes,2020-07-18,3.2,No
S005,Karan Joshi,20,Male,Pune,Maharashtra,Chemistry,65,D,78.0,No,2022-07-15,2.5,No
S006,Anjali Singh,24,Female,Delhi,Delhi,Mathematics,91,A,95.0,Yes,2019-07-22,3.7,Yes
S007,Vikram Nair,22,Male,Bangalore,Karnataka,Physics,78,B,88.0,Yes,2021-07-20,3.1,No
S008,Divya Rao,21,Female,Chennai,Tamil Nadu,Chemistry,84,B,91.0,Yes,2022-07-15,3.4,Yes
S009,Arjun Kumar,25,Male,Hyderabad,Telangana,Computer Science,90,A,96.0,Yes,2019-07-22,3.8,Yes
S010,Pooja Sharma,20,Female,Jaipur,Rajasthan,Mathematics,55,F,70.0,No,2022-07-15,2.1,No
S011,Nikhil Gupta,23,Male,Surat,Gujarat,Physics,77,C,83.0,Yes,2020-07-18,3.0,No
S012,Riya Desai,22,Female,Vadodara,Gujarat,Computer Science,93,A,97.0,Yes,2021-07-20,3.8,Yes
S013,Aditya Patil,21,Male,Nashik,Maharashtra,Chemistry,69,D,80.0,No,2022-07-15,2.6,No
S014,Kavya Iyer,24,Female,Kochi,Kerala,Mathematics,87,B,90.0,Yes,2020-07-18,3.4,No
S015,Rahul Tiwari,20,Male,Lucknow,Uttar Pradesh,Computer Science,74,C,82.0,Yes,2022-07-15,2.9,No
S016,Meera Pillai,22,Female,Thiruvananthapuram,Kerala,Physics,96,A,99.0,Yes,2021-07-20,4.0,Yes
S017,Siddharth Roy,23,Male,Kolkata,West Bengal,Chemistry,62,D,75.0,No,2020-07-18,2.4,No
S018,Tanvi Kulkarni,21,Female,Pune,Maharashtra,Computer Science,85,B,92.0,Yes,2022-07-15,3.3,No
S019,Hardik Bhatt,24,Male,Surat,Gujarat,Mathematics,79,C,86.0,Yes,2019-07-22,3.1,No
S020,Nisha Agarwal,20,Female,Agra,Uttar Pradesh,Physics,58,F,68.0,No,2022-07-15,2.2,No
S021,Yash Modi,22,Male,Gandhinagar,Gujarat,Computer Science,92,A,94.0,Yes,2021-07-20,3.7,Yes
S022,Swati Mishra,25,Female,Bhopal,Madhya Pradesh,Chemistry,83,B,89.0,Yes,2019-07-22,3.3,Yes
S023,Dev Pandey,21,Male,Varanasi,Uttar Pradesh,Mathematics,70,C,81.0,No,2022-07-15,2.7,No
S024,Kritika Saxena,23,Female,Indore,Madhya Pradesh,Computer Science,88,B,93.0,Yes,2020-07-18,3.5,No
S025,Manav Choudhary,20,Male,Chandigarh,Punjab,Physics,75,C,84.0,Yes,2022-07-15,3.0,No

In [41]:
df7.reset_index(inplace=True)

In [42]:
df7.set_index(['StudentID','Name'],inplace=True)

In [43]:
df7.loc['S023','Dev Pandey']

Age                           21
Gender                      Male
City                    Varanasi
State              Uttar Pradesh
Department           Mathematics
Score                         70
Grade                          C
Attendance                  81.0
Fee_Paid                      No
Enrollment_Date       2022-07-15
GPA                          2.7
Scholarship                   No
Name: (S023, Dev Pandey), dtype: object

In [44]:
df7.reset_index(inplace=True)

In [45]:
df7

,StudentID,Name,Age,Gender,City,State,Department,Score,Grade,Attendance,Fee_Paid,Enrollment_Date,GPA,Scholarship
0,S001,Aarav Shah,20,Male,Surat,Gujarat,Computer Science,88,B,92.5,Yes,2022-07-15,3.5,No
1,S002,Priya Mehta,22,Female,Ahmedabad,Gujarat,Mathematics,95,A,98.0,Yes,2021-07-20,3.9,Yes
2,S003,Rohan Verma,21,Male,Mumbai,Maharashtra,Physics,72,C,85.0,No,2022-07-15,2.8,No
3,S004,Sneha Patel,23,Female,Surat,Gujarat,Computer Science,81,B,89.5,Yes,2020-07-18,3.2,No
4,S005,Karan Joshi,20,Male,Pune,Maharashtra,Chemistry,65,D,78.0,No,2022-07-15,2.5,No
5,S006,Anjali Singh,24,Female,Delhi,Delhi,Mathematics,91,A,95.0,Yes,2019-07-22,3.7,Yes
6,S007,Vikram Nair,22,Male,Bangalore,Karnataka,Physics,78,B,88.0,Yes,2021-07-20,3.1,No
7,S008,Divya Rao,21,Female,Chennai,Tamil Nadu,Chemistry,84,B,91.0,Yes,2022-07-15,3.4,Yes
8,S009,Arjun Kumar,25,Male,Hyderabad,Telangana,Computer Science,90,A,96.0,Yes,2019-07-22,3.8,Yes
9,S010,Pooja Sharma,20,Female,Jaipur,Rajasthan,Mathematics,55,F,70.0,No,2022-07-15,2.1,No
10,S011,Nikhil Gupta,23,Male,Surat,Gujarat,Physics,77,C,83.0,Yes,2020-07-18,3.0,No
11,S012,Riya Desai,22,Female,Vadodara,Gujarat,Computer Science,93,A,97.0,Yes,2021-07-20,3.8,Yes
12,S013,Aditya Patil,21,Male,Nashik,Maharashtra,Chemistry,69,D,80.0,No,2022-07-15,2.6,No
13,S014,Kavya Iyer,24,Female,Kochi,Kerala,Mathematics,87,B,90.0,Yes,2020-07-18,3.4,No
14,S015,Rahul Tiwari,20,Male,Lucknow,Uttar Pradesh,Computer Science,74,C,82.0,Yes,2022-07-15,2.9,No
15,S016,Meera Pillai,22,Female,Thiruvananthapuram,Kerala,Physics,96,A,99.0,Yes,2021-07-20,4.0,Yes
16,S017,Siddharth Roy,23,Male,Kolkata,West Bengal,Chemistry,62,D,75.0,No,2020-07-18,2.4,No
17,S018,Tanvi Kulkarni,21,Female,Pune,Maharashtra,Computer Science,85,B,92.0,Yes,2022-07-15,3.3,No
18,S019,Hardik Bhatt,24,Male,Surat,Gujarat,Mathematics,79,C,86.0,Yes,2019-07-22,3.1,No
19,S020,Nisha Agarwal,20,Female,Agra,Uttar Pradesh,Physics,58,F,68.0,No,2022-07-15,2.2,No
20,S021,Yash Modi,22,Male,Gandhinagar,Gujarat,Computer Science,92,A,94.0,Yes,2021-07-20,3.7,Yes
21,S022,Swati Mishra,25,Female,Bhopal,Madhya Pradesh,Chemistry,83,B,89.0,Yes,2019-07-22,3.3,Yes
22,S023,Dev Pandey,21,Male,Varanasi,Uttar Pradesh,Mathematics,70,C,81.0,No,2022-07-15,2.7,No
23,S024,Kritika Saxena,23,Female,Indore,Madhya Pradesh,Computer Science,88,B,93.0,Yes,2020-07-18,3.5,No
24,S025,Manav Choudhary,20,Male,Chandigarh,Punjab,Physics,75,C,84.0,Yes,2022-07-15,3.0,No

In [46]:
import pandas as pd
import numpy as np

df8 = pd.read_csv(r"C:\Users\chahat\Downloads\missing_values_dataset.csv")
df8

,StudentID,Name,Age,Gender,City,Department,Score,Grade,Attendance,Fee_Paid,GPA,Scholarship,Height_cm,Weight_kg,Monthly_Income
0,S001,Aarav Shah,20.0,Male,Surat,Computer Science,88.0,B,92.5,Yes,3.5,No,172.0,68.0,NaN
1,S002,Priya Mehta,22.0,Female,Ahmedabad,Mathematics,95.0,A,98.0,Yes,3.9,Yes,161.0,52.0,45000.0
2,S003,Rohan Verma,NaN,Male,Mumbai,Physics,72.0,C,NaN,No,2.8,No,178.0,NaN,32000.0
3,S004,Sneha Patel,23.0,Female,Surat,Computer Science,NaN,B,89.5,Yes,NaN,No,155.0,50.0,NaN
4,S005,Karan Joshi,20.0,Male,Pune,Chemistry,65.0,D,78.0,No,2.5,NaN,169.0,74.0,28000.0
5,S006,Anjali Singh,24.0,Female,Delhi,Mathematics,91.0,A,95.0,Yes,3.7,Yes,NaN,NaN,55000.0
6,S007,Vikram Nair,22.0,Male,Bangalore,Physics,78.0,B,88.0,NaN,3.1,No,182.0,80.0,38000.0
7,S008,Divya Rao,21.0,Female,Chennai,Chemistry,84.0,B,NaN,Yes,3.4,Yes,159.0,54.0,NaN
8,S009,Arjun Kumar,25.0,Male,Hyderabad,Computer Science,90.0,A,96.0,Yes,3.8,Yes,NaN,NaN,62000.0
9,S010,Pooja Sharma,NaN,Female,Jaipur,Mathematics,55.0,F,70.0,No,NaN,NaN,157.0,48.0,22000.0
10,S011,Nikhil Gupta,23.0,Male,Surat,Physics,77.0,C,83.0,Yes,3.0,No,175.0,72.0,NaN
11,S012,Riya Desai,22.0,Female,Vadodara,Computer Science,93.0,A,97.0,Yes,3.8,Yes,163.0,NaN,48000.0
12,S013,Aditya Patil,21.0,Male,Nashik,Chemistry,NaN,D,80.0,No,2.6,No,NaN,65.0,25000.0
13,S014,Kavya Iyer,24.0,Female,Kochi,Mathematics,87.0,B,90.0,Yes,3.4,NaN,164.0,55.0,NaN
14,S015,Rahul Tiwari,20.0,Male,Lucknow,Computer Science,74.0,C,82.0,Yes,2.9,No,170.0,70.0,31000.0
15,S016,Meera Pillai,22.0,Female,Trivandrum,Physics,96.0,A,99.0,Yes,4.0,Yes,NaN,NaN,59000.0
16,S017,Siddharth Roy,23.0,Male,Kolkata,Chemistry,62.0,NaN,75.0,No,2.4,No,168.0,66.0,NaN
17,S018,Tanvi Kulkarni,21.0,Female,Pune,Computer Science,85.0,B,NaN,Yes,3.3,No,160.0,53.0,36000.0
18,S019,Hardik Bhatt,24.0,Male,Surat,Mathematics,79.0,C,86.0,Yes,NaN,No,177.0,78.0,NaN
19,S020,Nisha Agarwal,NaN,Female,Agra,Physics,58.0,F,68.0,No,2.2,No,153.0,46.0,20000.0
20,S021,Yash Modi,22.0,Male,Gandhinagar,Computer Science,92.0,A,94.0,Yes,3.7,Yes,180.0,NaN,52000.0
21,S022,Swati Mishra,25.0,Female,Bhopal,Chemistry,83.0,B,89.0,Yes,3.3,Yes,NaN,NaN,44000.0
22,S023,Dev Pandey,21.0,Male,Varanasi,Mathematics,NaN,C,81.0,No,2.7,NaN,166.0,62.0,27000.0
23,S024,Kritika Saxena,23.0,Female,Indore,Computer Science,88.0,B,93.0,Yes,3.5,No,162.0,51.0,NaN
24,S025,Manav Choudhary,20.0,Male,Chandigarh,Physics,75.0,C,84.0,NaN,3.0,No,174.0,69.0,33000.0
25,S026,Ishaan Reddy,NaN,Male,Hyderabad,Chemistry,80.0,B,87.5,Yes,3.2,Yes,171.0,NaN,41000.0
26,S027,Disha Kapoor,22.0,Female,Delhi,Computer Science,67.0,D,NaN,No,2.6,No,158.0,49.0,NaN
27,S028,Aryan Sharma,24.0,Male,Jaipur,Mathematics,91.0,A,95.5,Yes,NaN,Yes,NaN,NaN,57000.0
28,S029,Simran Kaur,21.0,Female,Chandigarh,Physics,73.0,C,82.0,Yes,2.9,No,165.0,56.0,30000.0
29,S030,Raj Malhotra,25.0,Male,Mumbai,Computer Science,86.0,B,91.0,Yes,3.4,NaN,176.0,75.0,NaN

In [47]:
df8.isnull().sum()

StudentID          0
Name               0
Age                4
Gender             0
City               0
Department         0
Score              3
Grade              1
Attendance         4
Fee_Paid           2
GPA                4
Scholarship        5
Height_cm          6
Weight_kg          9
Monthly_Income    10
dtype: int64

In [48]:
(df8.isnull().sum().values/len(df8))*100

array([ 0.        ,  0.        , 13.33333333,  0.        ,  0.        ,
        0.        , 10.        ,  3.33333333, 13.33333333,  6.66666667,
       13.33333333, 16.66666667, 20.        , 30.        , 33.33333333])

In [49]:
df8.isnull().any(axis=1).sum()

np.int64(27)

In [50]:
df8.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'City', 'Department', 'Score',
       'Grade', 'Attendance', 'Fee_Paid', 'GPA', 'Scholarship', 'Height_cm',
       'Weight_kg', 'Monthly_Income'],
      dtype='object')

In [51]:
df8.dropna(subset=['Grade'],inplace=True)

In [52]:
df8.drop('Weight_kg',inplace=True,axis=1)

In [53]:
df8['Age'] = df8['Age'].fillna(np.round(df8['Age'].mean(),0))

In [54]:
df8['Height_cm'] = df8['Height_cm'].fillna(np.round(df8['Height_cm'].median(),1))

In [55]:
df8['Scholarship'] = df8['Scholarship'].fillna(df8['Scholarship'].mode()[0])

In [56]:
df8.isnull().sum()

StudentID         0
Name              0
Age               0
Gender            0
City              0
Department        0
Score             3
Grade             0
Attendance        4
Fee_Paid          2
GPA               4
Scholarship       0
Height_cm         0
Monthly_Income    9
dtype: int64

In [57]:
df8['Score'] = df8['Score'].ffill()

In [58]:
df8['Attendance'] = df8['Attendance'].bfill()

In [59]:
df8['GPA'] = df8['GPA'].fillna(df8.groupby('Grade')['GPA'].transform('mean'))

In [60]:
df8.loc[(df8['Fee_Paid'].isna()) & (df8['Scholarship']=='No'),'Fee_Paid'] = 'No'

In [61]:
df8['missing_Monthly_Income'] = df8['Monthly_Income'].isna().astype('int')

Common Imputation Techniques
Mean Imputation
Median Imputation
Mode Imputation
Forward Fill (ffill)
Backward Fill (bfill)
Group-wise Mean/Median
KNN Imputation
Iterative Imputation (MICE)

In [62]:
a = pd.DataFrame({
    'columns':df.columns,
    'missing percentage':(df.isnull().sum().values/len(df))*100
    
})

In [63]:
a

             columns  missing percentage
0             emp_id                 0.0
1               name                 0.0
2         department                 0.0
3               city                 0.0
4             salary                 0.0
5   experience_years                 0.0
6  performance_score                 0.0
7                age                 0.0
8       joining_date                 0.0

In [64]:
df9 = pd.read_csv(r"C:\Users\chahat\Downloads\duplicates_dataset.csv")
df9

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
3,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [65]:
df9[df9.duplicated()]

,ID,Name,Email,Department,Salary,JoinDate,City
3,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [66]:
df9[df9.duplicated()].nunique()

ID            9
Name          9
Email         9
Department    4
Salary        9
JoinDate      9
City          6
dtype: int64

In [67]:
df9.drop_duplicates(inplace=True)

In [68]:
df9

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi

In [69]:
df10 = pd.read_csv(r"C:\Users\chahat\Downloads\duplicates_dataset.csv")
df10

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
3,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [70]:
df10.drop_duplicates(subset = ['ID'],inplace=True)

In [71]:
df10

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi

In [72]:
df11 = pd.read_csv(r"C:\Users\chahat\Downloads\duplicates_dataset.csv")
df11

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
3,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [73]:
df11.drop_duplicates(subset=['ID'],keep='first',inplace=True)

In [74]:
df11

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi

In [75]:
df12 = pd.read_csv(r"C:\Users\chahat\Downloads\duplicates_dataset.csv")
df12

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
3,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [76]:
df12.drop_duplicates(subset=['ID'],keep='last',inplace=True)

In [77]:
df12

,ID,Name,Email,Department,Salary,JoinDate,City
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [78]:
df13 = pd.read_csv(r"C:\Users\chahat\Downloads\duplicates_dataset.csv")
df13

,ID,Name,Email,Department,Salary,JoinDate,City
0,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
1,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
2,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
3,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
4,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
5,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
7,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
10,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
16,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
22,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [79]:
df13.drop_duplicates(subset=['ID'],keep=False,inplace=True)

In [80]:
df13

,ID,Name,Email,Department,Salary,JoinDate,City
8,107,Grace Kim,grace@example.com,HR,52000,2023-02-14,Mumbai
11,109,Isla Turner,isla@example.com,Marketing,47000,2022-08-19,Kolkata
13,110,Jake Wilson,jake@example.com,Finance,63000,2020-12-01,Pune
14,111,Karen Hall,karen@example.com,IT,71000,2021-09-15,Bangalore
17,113,Mia Thomas,mia@example.com,Marketing,46000,2022-03-30,Mumbai
19,114,Noah Harris,noah@example.com,IT,77000,2019-06-17,Delhi
20,115,Olivia Martin,olivia@example.com,Finance,66000,2020-10-08,Pune
23,117,Quinn Allen,quinn@example.com,IT,69000,2022-07-29,Hyderabad
25,118,Rachel Young,rachel@example.com,HR,57000,2020-02-18,Kolkata
26,119,Sam Clark,sam@example.com,Finance,64000,2023-01-09,Mumbai
28,120,Tina Lewis,tina@example.com,IT,74000,2018-08-24,Delhi

In [81]:
df14 = pd.read_csv(r"C:\Users\chahat\Downloads\duplicates_dataset.csv")

In [82]:
df14[df14['ID'].duplicated()]

,ID,Name,Email,Department,Salary,JoinDate,City
3,101,Alice Johnson,alice@example.com,HR,55000,2021-03-15,Mumbai
6,102,Bob Smith,bob@example.com,IT,72000,2020-07-01,Delhi
9,103,Carol White,carol@example.com,Finance,61000,2019-11-20,Pune
12,101,Alice Johnson,alice@example.com,HR,58000,2021-03-15,Mumbai
15,104,David Brown,david@example.com,IT,68000,2022-01-10,Bangalore
18,106,Frank Lee,frank@example.com,Finance,75000,2018-09-05,Hyderabad
21,112,Leo Scott,leo@example.com,HR,50000,2023-05-22,Chennai
24,108,Henry Adams,henry@example.com,IT,80000,2017-04-30,Delhi
27,116,Paul Walker,paul@example.com,Marketing,53000,2021-11-03,Bangalore
29,105,Eva Green,eva@example.com,Marketing,49000,2021-06-25,Chennai

In [83]:
df15 = pd.read_csv(r"C:\Users\chahat\Downloads\dtype_dataset (1).csv")
df15

,OrderID,CustomerName,Age,Salary,JoinDate,LastPurchaseDate,IsActive,Rating,Department,Quantity,Price,Discount,OrderStatus,Score,ZipCode,PhoneNumber,AccountBalance,TransactionDate,Gender,ProductCategory
0,1001,Alice Johnson,28,55000.75,15-03-2021,2024-01-10,1,4.5,HR,10,299.99,10%,Delivered,88.0,395001,9876543210,12500.50,2024-06-15 10:30:00,Female,Electronics
1,1002,Bob Smith,34,72000.00,01-07-2020,2024-02-20,0,3.8,IT,2,149.49,5%,Pending,76.0,110001,9123456780,8900.00,2024-06-16 11:45:00,Male,Clothing
2,1003,Carol White,29,61000.50,20-11-2019,2024-03-05,1,4.2,Finance,5,499.00,15%,Shipped,91.0,411001,9988776655,20300.75,2024-06-17 09:15:00,Female,Grocery
3,1004,David Brown,41,68000.00,10-01-2022,2024-01-28,1,NaN,IT,8,89.99,0%,Delivered,65.0,560001,9871234560,5400.25,2024-06-18 14:00:00,Male,Electronics
4,1005,Eva Green,26,49000.25,25-06-2021,2024-04-11,0,4.9,Marketing,1,999.00,20%,Cancelled,95.0,600001,9765432109,31000.00,2024-06-19 08:30:00,Female,Beauty
5,1006,Frank Lee,38,75000.00,05-09-2018,2024-02-14,1,4.1,Finance,3,249.99,10%,Delivered,80.0,500001,9654321098,15600.50,2024-06-20 13:20:00,Male,Clothing
6,1007,Grace Kim,31,52000.00,14-02-2023,2024-05-01,1,3.9,HR,7,59.99,5%,Pending,72.0,400001,9543210987,7200.00,2024-06-21 10:00:00,Female,Grocery
7,1008,Henry Adams,45,80000.50,30-04-2017,2024-03-22,0,4.6,IT,4,799.00,25%,Shipped,89.0,110002,9432109876,42000.75,2024-06-22 16:45:00,Male,Electronics
8,1009,Isla Turner,twenty seven,47000.00,19-08-2022,2024-04-30,1,3.2,Marketing,12,19.99,0%,Delivered,58.0,700001,9321098765,3100.00,2024-06-23 07:55:00,Female,Beauty
9,1010,Jake Wilson,33,63000.75,01-12-2020,2024-01-15,1,4.4,Finance,6,349.49,12%,Delivered,84.0,411002,9210987654,18900.25,2024-06-24 11:10:00,Male,Clothing
10,1011,Karen Hall,30,71000.00,15-09-2021,2024-05-20,0,4.0,IT,9,129.99,8%,Cancelled,77.0,560002,9109876543,9800.00,2024-06-25 12:30:00,Female,Electronics
11,1012,Leo Scott,22,50000.00,22-05-2023,2024-02-08,1,3.7,HR,2,449.99,18%,Shipped,69.0,600002,9098765432,6500.50,2024-06-26 15:00:00,Male,Grocery
12,1013,Mia Thomas,36,46000.50,30-03-2022,2024-03-17,1,4.8,Marketing,fifteen,9.99,0%,Delivered,93.0,400002,9987654321,2200.00,2024-06-27 09:45:00,Female,Beauty
13,1014,Noah Harris,50,seventy seven thousand,17-06-2019,2024-04-02,1,3.6,IT,3,659.00,22%,Pending,71.0,110003,9876543201,28700.75,2024-06-28 10:20:00,Male,Electronics
14,1015,Olivia Martin,28,66000.25,08-10-2020,2024-05-14,0,4.3,Finance,5,199.99,7%,Delivered,86.0,411003,9765432190,13400.50,2024-06-29 13:50:00,Female,Clothing
15,1016,Paul Walker,39,53000.00,03-11-2021,2024-01-25,yes,3.4,Marketing,11,39.99,3%,Shipped,62.0,560003,9654321987,4700.00,2024-06-30 08:10:00,Male,Grocery
16,1017,Quinn Allen,24,69000.75,29-07-2022,2024-02-28,1,4.7,IT,1,1199.00,30%,Delivered,97.0,500002,9543219876,55000.25,2024-07-01 14:35:00,Female,Electronics
17,1018,Rachel Young,44,57000.00,18-02-2020,2024-03-09,no,3.3,HR,4,89.49,6%,Cancelled,67.0,700002,9432198765,7900.00,2024-07-02 11:55:00,Female,Beauty
18,1019,Sam Clark,31,64000.50,09-01-2023,2024-04-19,1,4.1,Finance,7,279.99,14%,Delivered,81.0,395002,9321987654,16100.75,2024-07-03 09:30:00,Male,Clothing
19,1020,Tina Lewis,29,74000.00,24-08-2018,2024-05-30,1,4.5,IT,2,899.00,20%,Shipped,90.0,110004,9210976543,38500.00,2024-07-04 16:00:00,Female,Electronics

In [84]:
df15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           20 non-null     int64
 1   CustomerName      20 non-null     object
 2   Age               20 non-null     object
 3   Salary            20 non-null     object
 4   JoinDate          20 non-null     object
 5   LastPurchaseDate  20 non-null     object
 6   IsActive          20 non-null     object
 7   Rating            19 non-null     float64
 8   Department        20 non-null     object
 9   Quantity          20 non-null     object
 10  Price             20 non-null     float64
 11  Discount          20 non-null     object
 12  OrderStatus       20 non-null     object
 13  Score             20 non-null     float64
 14  ZipCode           20 non-null     int64
 15  PhoneNumber       20 non-null     int64
 16  AccountBalance    20 non-null     float64
 17  TransactionDate   20 non-null     object
 18  Gender            20 non-null     object
 19  ProductCategory   20 non-null     object
dtypes: float64(4), int64(3), object(13)
memory usage: 3.3+ KB

In [85]:
df15['Age'] = df15['Age'].replace({
    'twenty seven':27
})

In [86]:
df15['Age'] = df15['Age'].astype('int')

In [87]:
df15['Salary'] = df15['Salary'].replace({
    'seventy seven thousand':77000
})

In [88]:
df15['Salary'] = df15['Salary'].astype('float')

In [89]:
df15['JoinDate'] = pd.to_datetime(df15['JoinDate'])

C:\Users\chahat\AppData\Local\Temp\ipykernel_3508\2951898537.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df15['JoinDate'] = pd.to_datetime(df15['JoinDate'])

In [90]:
df15['LastPurchaseDate'] = pd.to_datetime(df15['LastPurchaseDate'])

In [91]:
df15['TransactionDate'] = pd.to_datetime(df15['TransactionDate'])

In [92]:
df15['TransactionDate'] = df15['TransactionDate'].astype('str')

In [93]:
df15['IsActive'] = df15['IsActive'].replace({
    'yes':1,
    'no':0
})

In [94]:
df15['Rating'] = df15['Rating'].fillna(df15.groupby('Department')['Rating'].transform('mean'))

In [95]:
df15['Quantity'] = df15['Quantity'].replace({
    'fifteen':15
})

In [96]:
df15['PhoneNumber'] = df15['PhoneNumber'].astype('object')

In [97]:
df15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           20 non-null     int64
 1   CustomerName      20 non-null     object
 2   Age               20 non-null     int64
 3   Salary            20 non-null     float64
 4   JoinDate          20 non-null     datetime64[ns]
 5   LastPurchaseDate  20 non-null     datetime64[ns]
 6   IsActive          20 non-null     object
 7   Rating            20 non-null     float64
 8   Department        20 non-null     object
 9   Quantity          20 non-null     object
 10  Price             20 non-null     float64
 11  Discount          20 non-null     object
 12  OrderStatus       20 non-null     object
 13  Score             20 non-null     float64
 14  ZipCode           20 non-null     int64
 15  PhoneNumber       20 non-null     object
 16  AccountBalance    20 non-null     float64
 17  TransactionDate   20 non-null     object
 18  Gender            20 non-null     object
 19  ProductCategory   20 non-null     object
dtypes: datetime64[ns](2), float64(5), int64(3), object(10)
memory usage: 3.3+ KB

In [98]:
df15[['Department','Gender','OrderStatus','ProductCategory']] = df15[['Department','Gender','OrderStatus','ProductCategory']].astype('category')

In [99]:
df15['Score'] = df15['Score'].astype('float32')

In [100]:
df15 = df15.infer_objects()

In [101]:
df15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           20 non-null     int64
 1   CustomerName      20 non-null     object
 2   Age               20 non-null     int64
 3   Salary            20 non-null     float64
 4   JoinDate          20 non-null     datetime64[ns]
 5   LastPurchaseDate  20 non-null     datetime64[ns]
 6   IsActive          20 non-null     object
 7   Rating            20 non-null     float64
 8   Department        20 non-null     category
 9   Quantity          20 non-null     object
 10  Price             20 non-null     float64
 11  Discount          20 non-null     object
 12  OrderStatus       20 non-null     category
 13  Score             20 non-null     float32
 14  ZipCode           20 non-null     int64
 15  PhoneNumber       20 non-null     int64
 16  AccountBalance    20 non-null     float64
 17  TransactionDate   20 non-null     object
 18  Gender            20 non-null     category
 19  ProductCategory   20 non-null     category
dtypes: category(4), datetime64[ns](2), float32(1), float64(4), int64(4), object(5)
memory usage: 3.3+ KB

In [102]:
df16 = pd.read_csv(r"C:\Users\chahat\Downloads\string_ops_dataset.csv")
df16

,ID,FullName,Email,PhoneRaw,Address,Department,Bio,SocialPost,Price_Raw,JoinDate_Raw,Comments,ProductCode,ZipCode_Raw,Website,Notes
1,alice johnson,Alice.Johnson@Gmail.COM,+91-98765-43210,"123, MG Road, Mumbai - 400001",hr manager,loves coding & data!! #python #datascience,Just attended @PyCon2024! Amazing event!! #Pyt...,Rs. 1,299.99,15th March 2021,Great product!! But packaging was BAD :( ratin...,PRD-#001-XYZ,395 001,www.alice-portfolio.com,Follow-up PENDING
2,BOB SMITH,bob.smith@@yahoo.com,9123 456 780,"456 Linking Rd,,Bandra, Mumbai",IT Developer,"Enjoys gaming, travel & photography!! #travel",Excited for @ReactConf! #JavaScript #WebDev #R...,$ 2500,01 July 2020,Product is ok. nothing special. would not reco...,PRD--002--ABC,110-001,http://bobsmith.dev,notes: call back on MONDAY,NaN
3,carol WHITE,Carol.White@Outlook.COM,(022) 2345-6789,"789, FC Road, Pune - 411001",finance executive,Passionate about #finance and travel!! loves c...,Met @DataScienceGuru at summit! #DataScience #...,₹ 850.00,20-Nov-2019,Awesome!! Exactly what I needed. perfect. rati...,prd_003_lmn,411 001,NaN,URGENT: renewal DUE,NaN
4,David BROWN,david.brown@,+1 (800) 555-0199,"1010 Elm St,, Springfield, IL - 62701",IT Manager,David is a #DevOps enthusiast & cloud lover!!,Can't wait for @AWSreInvent! #AWS #Cloud #DevO...,USD 3,750.50,January 10 2022,Worst experience ever!! Delayed by 3 weeks. ra...,PRD/004/OPQ,62701,https://davidbrown.io,reminder: INVOICE #4521 due
5,EVA GREEN,eva_green@company.co.in,9765432109,"22, Park Street, Kolkata - 700016",marketing lead,Creative thinker with a passion for #branding ...,Loved the talk by @MarketingPro! #Marketing #B...,INR1999.00,25th Jun 2021,Nice product but a bit expensive. value for mo...,Prd-005-rst,700 016,marketing.company.co.in,to-do: send PROPOSAL by friday,NaN
6,frank lee,Frank.Lee@HOTMAIL.com,040-2345 6789,"Plot 12, Jubilee Hills, Hyderabad-500033",finance manager,Numbers nerd!! loves #excel #python & long drives,Shoutout to @FinanceGuru! #Finance #Excel #Acc...,Rs 5000,5th September 2018,Decent quality. fast delivery!! would buy agai...,PRD 006 UVW,500-033,franklee.finance.com,follow up: CALL scheduled monday,NaN
7,Grace KIM,grace.kim@samsung.net,+82-10-1234-5678,"Rm 701, Gangnam Bldg, Seoul - 06000",hr executive,Loves #HR tech & people analytics!! yoga enthu...,Great panel with @HRLeader2024! #HR #PeopleOps...,KRW 120000,14-Feb-2023,Good but instructions were unclear. rating: 3/5,grc-007-xyz,06000,grace.samsung.net/profile,note: VISA expiry check needed,NaN
8,HENRY ADAMS,henry.adams@gmail.com,(800) 123-4567,"Apt 3B, 456 Oak Ave, New York, NY - 10001",IT Director,Blockchain & #AI enthusiast!! building the future,Inspired by @TechVisionary! #Blockchain #AI #W...,"$8,000.00",April 30 2017,Outstanding product!! Highly recommend to ever...,PRD-008-DEF,10001,http://henryadams.tech,ACTION: contract renewal ASAP,NaN
9,isla turner,isla.turner@@gmail.com,+91 97654 32109,"B-204, Sunrise Apt, Andheri, Mumbai - 400053",marketing exec,Foodie & #travel blogger!! exploring new place...,Just posted on @Foodie! #Food #Travel #Explore...,Rs. 450.50,19th Aug 2022,Packaging damaged on arrival!! very disappoint...,ISL_009_GHI,400-053,NaN,todo: INSTAGRAM post draft pending,NaN
10,Jake WILSON,jake.wilson@outlook.com,9876 543 210,"C-12, Vasant Vihar, New Delhi - 110057",finance analyst,#Investing and #stocks geek!! weekend cricketer,Big fan of @InvestorMindset! #Investing #Stock...,INR 3,100.75,1st December 2020,Satisfied with purchase. timely delivery. rati...,JKW-010-JKL,110 057,jakewilson.finance.net,PENDING: tax document submission
11,KAREN HALL,karen.hall@yahoo.co.in,(044) 6789-1234,"Old No.5 New No.10, Anna Nagar, Chennai-600040",IT lead,Python & #MachineLearning lover!! cat person 🐱,Attended @PyDataChennai meetup! #Python #Data ...,₹ 2,799.00,15-Sep-2021,Great value for price!! Fast shipping. rating:...,KRN.011.MNO,600-040,karenhall.dev,reminder: TEAM meeting notes due
12,leo scott,Leo.Scott@protonmail.com,+91-90987-65432,"123 MG road, Mysore - 570001",hr analyst,Aspiring #HR professional!! loves football & m...,Rooting for @TeamIndia! #Cricket #Sports #Chee...,Rs 1500,22nd May 2023,Average product. nothing wow. rating: 3/5,leo-012-pqr,570 001,leoscott.hr.in,note: background check PENDING for new hire,NaN
13,Mia THOMAS,mia.thomas@company.org,800-555-0187,"Suite 400, 789 Pine St, Los Angeles, CA - 90001",marketing manager,Storyteller & #ContentMarketing expert!! coffe...,Panel with @ContentQueen was epic! #Content #S...,USD 599.99,30th Mar 2022,Loved the product!! great quality & fast deliv...,MIA_013_STU,90001,mia.company.org/team,followup: CLIENT call tuesday URGENT,NaN
14,NOAH HARRIS,noah.harris@icloud.com,+1-800-555-0142,"88 Maple Dr, Austin, TX - 78701",IT architect,#CloudComputing & #Kubernetes nerd!! hiker & t...,Hyped for @KubeCon! #Kubernetes #Cloud #DevOps...,$ 12,450.00,17th June 2019,Terrible!! stopped working after 2 days. ratin...,NOH-014-VWX,78701,noahharris.cloud.io,ALERT: server maintenance TONIGHT
15,olivia martin,Olivia.Martin@Gmail.COM,(020) 4567-8901,"Flat 3, Koregaon Park, Pune - 411001",finance director,Loves #FinTech & investment banking!! avid rea...,Inspired by @FinTechLeader! #FinTech #Banking ...,INR 8500.00,8th October 2020,Decent product. average quality. rating: 3/5,OLV.015.YZA,411-001,olivia.financeblogs.com,schedule: QUARTERLY review pending,NaN
16,PAUL WALKER,paul.walker@twitter.com,+91 96543 21987,"H.No 234, Sector 17, Chandigarh - 160017",marketing exec,#SocialMedia strategist!! loves #Memes & cricket,Twitter power user @PaulWalks! #SocialMedia #M...,Rs. 750,3rd November 2021,Okay product. expected better. rating: 2/5,PWL-016-BCD,160 017,NaN,todo: SOCIAL media calendar update,NaN
17,quinn allen,quinn.allen@github.io,9543219876,"Dorm 5, MIT Campus, Cambridge, MA - 02139",IT intern,Open source contributor!! #GitHub & #OpenSourc...,Just merged my first PR! @github #OpenSource #...,$ 0.00,29th July 2022,Brilliant!! exceeded all expectations. rating:...,QNN_017_EFG,02139,quinn.allen.github.io,note: INTERNSHIP contract renewal check,NaN
18,RACHEL YOUNG,rachel.young@@rediff.com,(033) 2345-6780,"8B, Ballygunge, Kolkata - 700019",hr director,People-first leader!! #Diversity & #Inclusion ...,Proud to speak at @WomeninTech! #Diversity #In...,₹ 6,200.50,18th February 2020,Very happy with purchase!! great customer serv...,RCH-018-HIJ,700-019,rachelhr.in,REMINDER: appraisal cycle starts MONDAY
19,Sam CLARK,sam.clark@microsoft.com,+1 (425) 555-0190,"1 Microsoft Way, Redmond, WA - 98052",IT manager,Azure & #PowerBI wizard!! weekend golfer ⛳,Proud @Microsoft employee! #Azure #PowerBI #Cl...,USD 4,999.00,9th January 2023,Good product. solid build quality. rating: 4/5,SAM.019.KLM,98052,sam.microsoft.com/profile,ACTION: AZURE budget approval pending
20,TINA LEWIS,tina.lewis@adobe.com,(080) 9876-5432,"No 7, Whitefield, Bengaluru - 560066",marketing director,#Design & #Creativity evangelist!! watercolor ...,Inspired by @AdobeMAX! #Design #Creative #Adob...,INR 11,750.00,24th August 2018,Fantastic product!! will definitely buy again....,TNA-020-NOP,560-066,tina.adobe.com/work,FOLLOW-UP: CREATIVE brief due FRIDAY

In [103]:
df16.columns

Index(['ID', 'FullName', 'Email', 'PhoneRaw', 'Address', 'Department', 'Bio',
       'SocialPost', 'Price_Raw', 'JoinDate_Raw', 'Comments', 'ProductCode',
       'ZipCode_Raw', 'Website', 'Notes'],
      dtype='object')

In [104]:
cols = ['FullName','Department']
df16[cols] = df16[cols].apply(lambda x:x.str.upper())

In [105]:
cols1 = ['Email','Department']
df16[cols1] = df16[cols1].apply(lambda x:x.str.lower())

In [106]:
cols2 = ['FullName','ZipCode_Raw','Address']
df16[cols2] = df16[cols2].apply(lambda x:x.str.strip())

In [107]:
df16['Price_Raw'].unique()

array(['299.99', '01 July 2020', '20-Nov-2019', '750.50', '25th Jun 2021',
       '5th September 2018', '14-Feb-2023', 'April 30 2017',
       '19th Aug 2022', '100.75', '799.00', '22nd May 2023',
       '30th Mar 2022', '450.00', '8th October 2020', '3rd November 2021',
       '29th July 2022', '200.50', '999.00', '750.00'], dtype=object)

In [108]:
mask = df16['Price_Raw'].str.match(r'^\d+\.\d+$',na=False)
df16['Price_Raw'] = df16['Price_Raw'].where(mask,np.nan)

In [109]:
df16['ID'] = df16['ID'].str.strip()

In [110]:
df16['ID'] = df16['ID'].str.split(' ')

In [111]:
df16['PhoneRaw'] = df16['PhoneRaw'].str.split(',')

In [112]:
df16['ID'] = df16['ID'].str.join(',')

In [113]:
df16['PhoneRaw'] = df16['PhoneRaw'].str.join(',')

In [114]:
df16['FirstName'] = df16['ID'].str.split(',').str[0]

In [115]:
df16['SecondName'] = df16['ID'].str.split(',').str[1]

In [116]:
df16['Domain'] = df16['Address'].str.split(' ').str[0]

In [117]:
df16['Role'] = df16['Address'].str.split(' ').str[1]

In [118]:
df16['c'] = df16['FullName'].str.len()

In [119]:
df16['Zipcode'] = df16['PhoneRaw'].str.extract(r'(\d{5,6})\s*$')

In [120]:
df16['hn'] = df16['PhoneRaw'].str.extract(r'\s*(\d{1,4})\s*')

In [121]:
df16.columns

Index(['ID', 'FullName', 'Email', 'PhoneRaw', 'Address', 'Department', 'Bio',
       'SocialPost', 'Price_Raw', 'JoinDate_Raw', 'Comments', 'ProductCode',
       'ZipCode_Raw', 'Website', 'Notes', 'FirstName', 'SecondName', 'Domain',
       'Role', 'c', 'Zipcode', 'hn'],
      dtype='object')

In [122]:
df16['comment_new'] = df16['Comments'].str.replace(r'[^A-Za-z0-9]',' ',regex=True)

In [123]:
df16[df16['ID'].str.startswith('a')]

,ID,FullName,Email,PhoneRaw,Address,Department,Bio,SocialPost,Price_Raw,JoinDate_Raw,...,Website,Notes,FirstName,SecondName,Domain,Role,c,Zipcode,hn,comment_new
1,"alice,johnson",ALICE.JOHNSON@GMAIL.COM,+91-98765-43210,"123, MG Road, Mumbai - 400001",hr manager,loves coding & data!! #python #datascience,Just attended @PyCon2024! Amazing event!! #Pyt...,Rs. 1,299.99,15th March 2021,...,www.alice-portfolio.com,Follow-up PENDING,alice,johnson,hr,manager,23,400001,123,Great product But packaging was BAD ratin...

In [124]:
df16[df16['ID'].str.endswith('e')]

,ID,FullName,Email,PhoneRaw,Address,Department,Bio,SocialPost,Price_Raw,JoinDate_Raw,...,Website,Notes,FirstName,SecondName,Domain,Role,c,Zipcode,hn,comment_new
6,"frank,lee",FRANK.LEE@HOTMAIL.COM,040-2345 6789,"Plot 12, Jubilee Hills, Hyderabad-500033",finance manager,numbers nerd!! loves #excel #python & long drives,Shoutout to @FinanceGuru! #Finance #Excel #Acc...,Rs 5000,NaN,Decent quality. fast delivery!! would buy agai...,...,follow up: CALL scheduled monday,NaN,frank,lee,finance,manager,21,500033,12,PRD 006 UVW

In [125]:
df16[df16['SocialPost'].str.contains(r'\s*(Rs.)\s*')]

C:\Users\chahat\AppData\Local\Temp\ipykernel_3508\1472880966.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df16[df16['SocialPost'].str.contains(r'\s*(Rs.)\s*')]

,ID,FullName,Email,PhoneRaw,Address,Department,Bio,SocialPost,Price_Raw,JoinDate_Raw,...,Website,Notes,FirstName,SecondName,Domain,Role,c,Zipcode,hn,comment_new
1,"alice,johnson",ALICE.JOHNSON@GMAIL.COM,+91-98765-43210,"123, MG Road, Mumbai - 400001",hr manager,loves coding & data!! #python #datascience,Just attended @PyCon2024! Amazing event!! #Pyt...,Rs. 1,299.99,15th March 2021,...,www.alice-portfolio.com,Follow-up PENDING,alice,johnson,hr,manager,23,400001,123,Great product But packaging was BAD ratin...
6,"frank,lee",FRANK.LEE@HOTMAIL.COM,040-2345 6789,"Plot 12, Jubilee Hills, Hyderabad-500033",finance manager,numbers nerd!! loves #excel #python & long drives,Shoutout to @FinanceGuru! #Finance #Excel #Acc...,Rs 5000,NaN,Decent quality. fast delivery!! would buy agai...,...,follow up: CALL scheduled monday,NaN,frank,lee,finance,manager,21,500033,12,PRD 006 UVW
9,"isla,turner",ISLA.TURNER@@GMAIL.COM,+91 97654 32109,"B-204, Sunrise Apt, Andheri, Mumbai - 400053",marketing exec,foodie & #travel blogger!! exploring new place...,Just posted on @Foodie! #Food #Travel #Explore...,Rs. 450.50,NaN,Packaging damaged on arrival!! very disappoint...,...,todo: INSTAGRAM post draft pending,NaN,isla,turner,marketing,exec,22,400053,204,ISL 009 GHI
12,"leo,scott",LEO.SCOTT@PROTONMAIL.COM,+91-90987-65432,"123 MG road, Mysore - 570001",hr analyst,aspiring #hr professional!! loves football & m...,Rooting for @TeamIndia! #Cricket #Sports #Chee...,Rs 1500,NaN,Average product. nothing wow. rating: 3/5,...,note: background check PENDING for new hire,NaN,leo,scott,hr,analyst,24,570001,123,leo 012 pqr
16,"PAUL,WALKER",PAUL.WALKER@TWITTER.COM,+91 96543 21987,"H.No 234, Sector 17, Chandigarh - 160017",marketing exec,#socialmedia strategist!! loves #memes & cricket,Twitter power user @PaulWalks! #SocialMedia #M...,Rs. 750,NaN,Okay product. expected better. rating: 2/5,...,todo: SOCIAL media calendar update,NaN,PAUL,WALKER,marketing,exec,23,160017,234,PWL 016 BCD

In [126]:
df16['ID'] = df16['ID'].str.replace(r',',' ',regex=True)

In [127]:
df16['ID'] = df16['ID'].str.title()

In [128]:
df16['hashtag'] = df16['Department'].str.extract(r'(#\w+)')

In [129]:
df16['mentions'] = df16['Bio'].str.extract(r'(@\w+)')

In [130]:
df16

,ID,FullName,Email,PhoneRaw,Address,Department,Bio,SocialPost,Price_Raw,JoinDate_Raw,...,FirstName,SecondName,Domain,Role,c,Zipcode,hn,comment_new,hashtag,mentions
1,Alice Johnson,ALICE.JOHNSON@GMAIL.COM,+91-98765-43210,"123, MG Road, Mumbai - 400001",hr manager,loves coding & data!! #python #datascience,Just attended @PyCon2024! Amazing event!! #Pyt...,Rs. 1,299.99,15th March 2021,...,alice,johnson,hr,manager,23,400001,123,Great product But packaging was BAD ratin...,#python,@PyCon2024
2,Bob Smith,BOB.SMITH@@YAHOO.COM,9123 456 780,"456 Linking Rd,,Bandra, Mumbai",IT Developer,"enjoys gaming, travel & photography!! #travel",Excited for @ReactConf! #JavaScript #WebDev #R...,$ 2500,NaN,Product is ok. nothing special. would not reco...,...,BOB,SMITH,IT,Developer,20,NaN,456,PRD 002 ABC,#travel,@ReactConf
3,Carol White,CAROL.WHITE@OUTLOOK.COM,(022) 2345-6789,"789, FC Road, Pune - 411001",finance executive,passionate about #finance and travel!! loves c...,Met @DataScienceGuru at summit! #DataScience #...,₹ 850.00,NaN,Awesome!! Exactly what I needed. perfect. rati...,...,carol,WHITE,finance,executive,23,411001,789,prd 003 lmn,#finance,@DataScienceGuru
4,David Brown,DAVID.BROWN@,+1 (800) 555-0199,"1010 Elm St,, Springfield, IL - 62701",IT Manager,david is a #devops enthusiast & cloud lover!!,Can't wait for @AWSreInvent! #AWS #Cloud #DevO...,USD 3,750.50,January 10 2022,...,David,BROWN,IT,Manager,12,62701,1010,Worst experience ever Delayed by 3 weeks ra...,#devops,@AWSreInvent
5,Eva Green,EVA_GREEN@COMPANY.CO.IN,9765432109,"22, Park Street, Kolkata - 700016",marketing lead,creative thinker with a passion for #branding ...,Loved the talk by @MarketingPro! #Marketing #B...,INR1999.00,NaN,Nice product but a bit expensive. value for mo...,...,EVA,GREEN,marketing,lead,23,700016,22,Prd 005 rst,#branding,@MarketingPro
6,Frank Lee,FRANK.LEE@HOTMAIL.COM,040-2345 6789,"Plot 12, Jubilee Hills, Hyderabad-500033",finance manager,numbers nerd!! loves #excel #python & long drives,Shoutout to @FinanceGuru! #Finance #Excel #Acc...,Rs 5000,NaN,Decent quality. fast delivery!! would buy agai...,...,frank,lee,finance,manager,21,500033,12,PRD 006 UVW,#excel,@FinanceGuru
7,Grace Kim,GRACE.KIM@SAMSUNG.NET,+82-10-1234-5678,"Rm 701, Gangnam Bldg, Seoul - 06000",hr executive,loves #hr tech & people analytics!! yoga enthu...,Great panel with @HRLeader2024! #HR #PeopleOps...,KRW 120000,NaN,Good but instructions were unclear. rating: 3/5,...,Grace,KIM,hr,executive,21,06000,701,grc 007 xyz,#hr,@HRLeader2024
8,Henry Adams,HENRY.ADAMS@GMAIL.COM,(800) 123-4567,"Apt 3B, 456 Oak Ave, New York, NY - 10001",IT Director,blockchain & #ai enthusiast!! building the future,Inspired by @TechVisionary! #Blockchain #AI #W...,"$8,000.00",NaN,Outstanding product!! Highly recommend to ever...,...,HENRY,ADAMS,IT,Director,21,10001,3,PRD 008 DEF,#ai,@TechVisionary
9,Isla Turner,ISLA.TURNER@@GMAIL.COM,+91 97654 32109,"B-204, Sunrise Apt, Andheri, Mumbai - 400053",marketing exec,foodie & #travel blogger!! exploring new place...,Just posted on @Foodie! #Food #Travel #Explore...,Rs. 450.50,NaN,Packaging damaged on arrival!! very disappoint...,...,isla,turner,marketing,exec,22,400053,204,ISL 009 GHI,#travel,@Foodie
10,Jake Wilson,JAKE.WILSON@OUTLOOK.COM,9876 543 210,"C-12, Vasant Vihar, New Delhi - 110057",finance analyst,#investing and #stocks geek!! weekend cricketer,Big fan of @InvestorMindset! #Investing #Stock...,INR 3,100.75,1st December 2020,...,Jake,WILSON,finance,analyst,23,110057,12,Satisfied with purchase timely delivery rati...,#investing,@InvestorMindset
11,Karen Hall,KAREN.HALL@YAHOO.CO.IN,(044) 6789-1234,"Old No.5 New No.10, Anna Nagar, Chennai-600040",IT lead,python & #machinelearning lover!! cat person 🐱,Attended @PyDataChennai meetup! #Python #Data ...,₹ 2,799.00,15-Sep-2021,...,KAREN,HALL,IT,lead,22,600040,5,Great value for price Fast shipping rating ...,#machinelearning,@PyDataChennai
12,Leo Scott,LEO.SCOTT@PROTONMAIL.COM,+91-90987-65432,"123 MG road, Mysore - 570001",hr analyst,aspiring #hr professional!! loves football & m...,Rooting for @TeamIndia! #Cricket #Sports #Chee...,Rs 1500,NaN,Average product. nothing wow. rating: 3/5,...,leo,scott,hr,analyst,24,570001,123,leo 012 pqr,#hr,@TeamIndia
13,Mia Thomas,MIA.THOMAS@COMPANY.ORG,800-555-0187,"Suite 400, 789 Pine St, Los Angeles, CA - 90001",marketing manager,storyteller & #contentmarketing expert!! coffe...,Panel with @ContentQueen was epic! #Content #S...,USD 599.99,NaN,Loved the product!! great quality & fast deliv...,...,Mia,THOMAS,marketing,manager,22,90001,400,MIA 013 STU,#contentmarketing,@ContentQueen
14,Noah Harris,NOAH.HARRIS@ICLOUD.COM,+1-800-555-0142,"88 Maple Dr, Austin, TX - 78701",IT architect,#cloudcomputing & #kubernetes nerd!! hiker & t...,Hyped for @KubeCon! #Kubernetes #Cloud #DevOps...,$ 12,450.00,17th June 2019,...,NOAH,HARRIS,IT,architect,22,78701,88,Terrible stopped working after 2 days ratin...,#cloudcomputing,@KubeCon
15,Olivia Martin,OLIVIA.MARTIN@GMAIL.COM,(020) 4567-8901,"Flat 3, Koregaon Park, Pune - 411001",finance director,loves #fintech & investment banking!! avid rea...,Inspired by @FinTechLeader! #FinTech #Banking ...,INR 8500.00,NaN,Decent product. average quality. rating: 3/5,...,olivia,martin,finance,director,23,411001,3,OLV 015 YZA,#fintech,@FinTechLeader
16,Paul Walker,PAUL.WALKER@TWITTER.COM,+91 96543 21987,"H.No 234, Sector 17, Chandigarh - 160017",marketing exec,#socialmedia strategist!! loves #memes & cricket,Twitter power user @PaulWalks! #SocialMedia #M...,Rs. 750,NaN,Okay product. expected better. rating: 2/5,...,PAUL,WALKER,marketing,exec,23,160017,234,PWL 016 BCD,#socialmedia,@PaulWalks
17,Quinn Allen,QUINN.ALLEN@GITHUB.IO,9543219876,"Dorm 5, MIT Campus, Cambridge, MA - 02139",IT intern,open source contributor!! #github & #opensourc...,Just merged my first PR! @github #OpenSource #...,$ 0.00,NaN,Brilliant!! exceeded all expectations. rating:...,...,quinn,allen,IT,intern,21,02139,5,QNN 017 EFG,#github,@github
18,Rachel Young,RACHEL.YOUNG@@REDIFF.COM,(033) 2345-6780,"8B, Ballygunge, Kolkata - 700019",hr director,people-first leader!! #diversity & #inclusion ...,Proud to speak at @WomeninTech! #Diversity #In...,₹ 6,200.50,18th February 2020,...,RACHEL,YOUNG,hr,director,24,700019,8,Very happy with purchase great customer serv...,#diversity,@WomeninTech
19,Sam Clark,SAM.CLARK@MICROSOFT.COM,+1 (425) 555-0190,"1 Microsoft Way, Redmond, WA - 98052",IT manager,azure & #powerbi wizard!! weekend golfer ⛳,Proud @Microsoft employee! #Azure #PowerBI #Cl...,USD 4,999.00,9th January 2023,...,Sam,CLARK,IT,manager,23,98052,1,Good product solid build quality rating 4 5,#powerbi,@Microsoft
20,Tina Lewis,TINA.LEWIS@ADOBE.COM,(080) 9876-5432,"No 7, Whitefield, Bengaluru - 560066",marketing director,#design & #creativity evangelist!! watercolor ...,Inspired by @AdobeMAX! #Design #Creative #Adob...,INR 11,750.00,24th August 2018,...,TINA,LEWIS,marketing,director,20,560066,7,Fantastic product will definitely buy again ...,#design,@AdobeMAX

In [131]:
df17 = pd.read_csv(r"C:\Users\chahat\Downloads\employees (1).csv")
df17

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13

In [132]:
df17.sort_values('age')

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05

In [133]:
df17.sort_values(['department','salary'])

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28

In [134]:
df17.sort_values('experience_years',ascending=False)

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14

In [135]:
df17.sort_index()

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13

In [136]:
df17.sort_values('salary',ascending=False).head(10)

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15

In [137]:
df17.sort_values('salary',ascending=False).tail(10)

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14

In [138]:
df17['salary'].rank(method='average')

0     31.0
1     15.0
2     37.0
3      5.0
4     24.0
5     12.0
6     40.0
7     28.0
8      9.0
9     35.0
10    17.0
11    21.0
12    33.0
13     2.0
14    13.0
15    27.0
16    38.0
17     7.0
18    10.0
19    30.0
20    25.5
21     1.0
22    19.0
23    23.0
24    34.0
25     4.0
26    16.0
27    20.0
28    39.0
29     8.0
30    11.0
31    29.0
32    36.0
33     6.0
34    14.0
35    22.0
36    32.0
37     3.0
38    18.0
39    25.5
Name: salary, dtype: float64

In [139]:
df17['salary'].rank(method='dense')

0     30.0
1     15.0
2     36.0
3      5.0
4     24.0
5     12.0
6     39.0
7     27.0
8      9.0
9     34.0
10    17.0
11    21.0
12    32.0
13     2.0
14    13.0
15    26.0
16    37.0
17     7.0
18    10.0
19    29.0
20    25.0
21     1.0
22    19.0
23    23.0
24    33.0
25     4.0
26    16.0
27    20.0
28    38.0
29     8.0
30    11.0
31    28.0
32    35.0
33     6.0
34    14.0
35    22.0
36    31.0
37     3.0
38    18.0
39    25.0
Name: salary, dtype: float64

In [140]:
df17['salary'].rank(pct=True)

0     0.7750
1     0.3750
2     0.9250
3     0.1250
4     0.6000
5     0.3000
6     1.0000
7     0.7000
8     0.2250
9     0.8750
10    0.4250
11    0.5250
12    0.8250
13    0.0500
14    0.3250
15    0.6750
16    0.9500
17    0.1750
18    0.2500
19    0.7500
20    0.6375
21    0.0250
22    0.4750
23    0.5750
24    0.8500
25    0.1000
26    0.4000
27    0.5000
28    0.9750
29    0.2000
30    0.2750
31    0.7250
32    0.9000
33    0.1500
34    0.3500
35    0.5500
36    0.8000
37    0.0750
38    0.4500
39    0.6375
Name: salary, dtype: float64

In [141]:
df17.sort_values(['department','performance_score'],ascending=[True,False])

,emp_id,name,department,city,salary,experience_years,performance_score,age,joining_date
6,107,Amit Kumar,Engineering,Hyderabad,125000,15,95.3,40,2009-11-05
28,129,Gaurav Mishra,Engineering,Mumbai,119000,14,94.5,39,2010-02-14
16,117,Arjun Menon,Engineering,Hyderabad,115000,13,93.7,38,2011-04-22
2,103,Rohan Verma,Engineering,Bangalore,110000,12,92.1,36,2012-01-10
32,133,Harsh Tripathi,Engineering,Bangalore,107000,12,91.8,37,2012-06-30
24,125,Siddharth Jain,Engineering,Delhi,102000,11,91.2,36,2013-09-16
9,110,Ananya Gupta,Engineering,Bangalore,105000,11,90.6,35,2013-05-20
12,113,Suresh Das,Engineering,Pune,98000,10,89.4,34,2014-03-09
0,101,Aarav Shah,Engineering,Mumbai,95000,8,88.5,32,2016-03-15
36,137,Vivek Srivastava,Engineering,Pune,96000,9,88.0,33,2015-12-01
20,121,Rahul Choudhury,Engineering,Kolkata,88000,8,86.0,32,2016-11-19
19,120,Deepika Saxena,Finance,Delhi,94000,10,87.3,35,2014-08-05
31,132,Swati Dubey,Finance,Mumbai,92000,10,86.8,34,2014-10-22
7,108,Pooja Singh,Finance,Delhi,91000,9,85.7,33,2015-02-28
39,140,Mona Chopra,Finance,Delhi,88000,9,84.9,33,2015-10-13
15,116,Tanya Bose,Finance,Kolkata,89000,9,84.2,33,2015-06-12
4,105,Karan Joshi,Finance,Mumbai,87000,7,83.4,31,2017-09-18
35,136,Neha Kulkarni,Finance,Hyderabad,85000,8,83.1,32,2016-09-24
23,124,Nisha Kapoor,Finance,Bangalore,86000,8,82.8,32,2016-04-03
11,112,Meera Iyer,Finance,Chennai,83000,8,81.9,32,2016-07-17
27,128,Ritu Sinha,Finance,Pune,80000,7,80.0,30,2017-07-11
8,109,Raj Malhotra,HR,Mumbai,62000,6,71.3,30,2018-08-14
29,130,Priyanka Khanna,HR,Delhi,61000,5,70.9,29,2019-04-29
3,104,Sneha Patel,HR,Surat,58000,3,69.8,26,2021-06-01
33,134,Pallavi Shukla,HR,Chennai,59000,4,69.2,27,2020-07-06
17,118,Kavya Reddy,HR,Chennai,60000,4,68.5,27,2020-09-08
25,126,Ankita Desai,HR,Hyderabad,57000,3,67.1,26,2021-11-07
37,138,Ayesha Khan,HR,Mumbai,56000,3,66.7,26,2021-08-19
13,114,Lakshmi Pillai,HR,Bangalore,55000,2,65.2,25,2022-01-25
21,122,Shreya Bhatt,HR,Surat,53000,2,63.4,24,2022-07-14
22,123,Varun Agarwal,Marketing,Mumbai,78000,7,80.5,31,2017-02-28
38,139,Saurabh Garg,Marketing,Bangalore,76000,6,79.6,30,2018-03-07
10,111,Vikram Rao,Marketing,Hyderabad,75000,6,79.1,29,2018-12-03
26,127,Mohit Pandey,Marketing,Chennai,73000,6,78.3,30,2018-05-23
14,115,Nikhil Sharma,Marketing,Mumbai,70000,5,77.8,28,2019-10-30
34,135,Rohit Chandra,Marketing,Delhi,71000,5,76.9,29,2019-01-18
1,102,Priya Mehta,Marketing,Delhi,72000,5,76.2,28,2019-07-22
30,131,Aditya Bansal,Marketing,Kolkata,67000,4,75.0,27,2020-01-15
5,106,Divya Nair,Marketing,Chennai,68000,4,74.5,27,2020-04-11
18,119,Manish Tiwari,Marketing,Pune,65000,3,72.6,26,2021-03-17

In [142]:
df18 = pd.read_csv(r"C:\Users\chahat\Downloads\sales_data.csv")
df18

,order_id,date,region,city,category,sub_category,product,salesperson,gender,quantity,unit_price,discount,sales,profit,customer_age,customer_segment
0,1001,2024-01-03,North,Delhi,Electronics,Mobile,iPhone 14,Raj Sharma,Male,2,75000,0.05,142500,28500,34,Corporate
1,1002,2024-01-05,South,Chennai,Clothing,Shirts,Levi's Shirt,Priya Nair,Female,5,1200,0.10,5400,1080,27,Consumer
2,1003,2024-01-07,West,Mumbai,Electronics,Laptop,Dell XPS,Amit Patel,Male,1,95000,0.08,87400,13110,41,Corporate
3,1004,2024-01-09,East,Kolkata,Furniture,Chair,Office Chair,Sneha Das,Female,3,4500,0.00,13500,2700,35,Home Office
4,1005,2024-01-11,North,Delhi,Grocery,Dairy,Amul Butter,Raj Sharma,Male,20,50,0.00,1000,200,28,Consumer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2024-07-14,East,Bhubaneswar,Grocery,Beverages,B Natural Pack,Arjun Sen,Male,20,70,0.00,1400,280,45,Consumer
96,1097,2024-07-16,North,Delhi,Furniture,Bed,Storage Bed,Divya Gupta,Female,1,32000,0.05,30400,6080,22,Home Office
97,1098,2024-07-18,South,Hyderabad,Electronics,Mobile,iQOO 11,Kiran Rao,Male,3,50000,0.05,142500,28500,29,Consumer
98,1099,2024-07-20,West,Ahmedabad,Clothing,Jackets,H&M Jacket,Meera Joshi,Female,4,3500,0.10,12600,2520,33,Consumer
99,1100,2024-07-22,East,Guwahati,Electronics,Laptop,Samsung Galaxy Book,Arjun Sen,Male,1,75000,0.08,69000,10350,45,Corporate

In [143]:
df18.groupby('city')['sales'].sum()

city
Ahmedabad      184200
Bangalore      225200
Bhubaneswar    172720
Chandigarh     156370
Chennai        444050
Delhi          587250
Guwahati       212645
Hyderabad      652000
Kolkata        518950
Lucknow        337325
Mumbai         303230
Pune           550120
Name: sales, dtype: int64

In [144]:
df18.groupby(['city','category'])['profit'].sum()

city         category
Ahmedabad    Clothing         4680
             Electronics     15200
             Furniture       16720
             Grocery           240
Bangalore    Clothing         7110
             Electronics     37050
             Grocery           880
Bhubaneswar  Clothing         7744
             Electronics     22800
             Furniture        3040
             Grocery           960
Chandigarh   Clothing         1944
             Electronics     21390
             Grocery           810
Chennai      Clothing         1080
             Electronics     55740
             Furniture       19950
             Grocery           680
Delhi        Clothing         5200
             Electronics     83050
             Furniture       19950
             Grocery          1200
Guwahati     Clothing         4824
             Electronics     31170
             Grocery           325
Hyderabad    Electronics    111000
             Furniture        2660
             Grocery           640
Kolkata      Clothing         5760
             Electronics     80380
             Furniture       11440
Lucknow      Electronics     58360
             Furniture        2850
             Grocery           735
Mumbai       Clothing         6336
             Electronics     35190
             Furniture        6650
             Grocery           740
Pune         Clothing         3900
             Electronics     90275
             Furniture        5700
             Grocery           324
Name: profit, dtype: int64

In [145]:
df18.groupby('category')['sales'].mean()

category
Clothing        11040.454545
Electronics    113084.375000
Furniture       23410.526316
Grocery          1395.185185
Name: sales, dtype: float64

In [146]:
df18.groupby('category')['sales'].median()

category
Clothing        10650.0
Electronics    106400.0
Furniture       22800.0
Grocery          1200.0
Name: sales, dtype: float64

In [147]:
df18.groupby('category')['sales'].count()

category
Clothing       22
Electronics    32
Furniture      19
Grocery        27
Name: sales, dtype: int64

In [148]:
df18.groupby('category')['sales'].sum()

category
Clothing        242890
Electronics    3618700
Furniture       444800
Grocery          37670
Name: sales, dtype: int64

In [149]:
df18.groupby('category')['sales'].min()

category
Clothing        5400
Electronics    46000
Furniture      11400
Grocery          525
Name: sales, dtype: int64

In [150]:
df18.groupby('category')['sales'].max()

category
Clothing        20000
Electronics    209000
Furniture       42750
Grocery          3000
Name: sales, dtype: int64

In [151]:
df18.groupby('category')['sales'].std()

category
Clothing        3507.815054
Electronics    41937.548495
Furniture       8889.219109
Grocery          604.837043
Name: sales, dtype: float64

In [152]:
df18.groupby('category')['sales'].var()

category
Clothing       1.230477e+07
Electronics    1.758758e+09
Furniture      7.901822e+07
Grocery        3.658278e+05
Name: sales, dtype: float64

In [153]:
df18.groupby('category').agg({
    'profit':'mean'
})

                   profit
category
Clothing      2208.090909
Electronics  20050.156250
Furniture     4682.105263
Grocery        279.037037

In [154]:
df18.groupby('category').agg({
    'sales':['mean','median','std'],
    'profit':'mean'
})

                     sales                                profit
                      mean    median           std          mean
category
Clothing      11040.454545   10650.0   3507.815054   2208.090909
Electronics  113084.375000  106400.0  41937.548495  20050.156250
Furniture     23410.526316   22800.0   8889.219109   4682.105263
Grocery        1395.185185    1200.0    604.837043    279.037037

In [155]:
df18.groupby('sub_category')['sales'].agg(lambda x:x.mean()).sort_values(ascending=False)

sub_category
Mobile       141142.857143
TV            95285.714286
Laptop        88700.000000
Bed           30162.500000
Wardrobe      30083.333333
Sofa          24462.500000
Chair         19762.500000
Saree         15250.000000
Table         14250.000000
Jackets       12262.500000
Kurta          9720.000000
Shirts         9540.000000
Jeans          9252.000000
Beverages      1622.222222
Snacks         1300.000000
Dairy          1263.333333
Name: sales, dtype: float64

In [156]:
df18.groupby('city').agg(total_sales=('sales','sum'),average_profit=('profit','mean'))

             total_sales  average_profit
city
Ahmedabad         184200     4605.000000
Bangalore         225200     5630.000000
Bhubaneswar       172720     4318.000000
Chandigarh        156370     4024.000000
Chennai           444050     8605.555556
Delhi             587250     8415.384615
Guwahati          212645     4539.875000
Hyderabad         652000    14287.500000
Kolkata           518950    10842.222222
Lucknow           337325    10324.166667
Mumbai            303230     5435.111111
Pune              550120    12524.875000

In [157]:
df18.groupby('category')['profit'].transform(lambda x:(x/x.sum())*100)

0     4.441985
1     2.223229
2     2.043313
3     3.035072
4     2.654632
        ...
95    3.716485
96    6.834532
97    4.441985
98    5.187533
99    1.613142
Name: profit, Length: 100, dtype: float64

In [158]:
df18.groupby('city')['sales'].rank(ascending=False)

0      2.0
1      7.0
2      2.0
3      8.0
4     13.0
      ...
95     7.5
96     5.0
97     2.0
98     5.0
99     1.0
Name: sales, Length: 100, dtype: float64

In [159]:
df18.groupby('city')['sales'].cumsum()

0     142500
1       5400
2      87400
3      13500
4     143500
       ...
95    172720
96    587250
97    652000
98    184200
99    212645
Name: sales, Length: 100, dtype: int64

In [160]:
df18.groupby('city')['sales'].cumcount()

0      0
1      0
2      0
3      0
4      1
      ..
95     7
96    12
97     7
98     7
99     7
Length: 100, dtype: int64

In [161]:
df18.groupby('category')['profit'].transform(lambda x:x.rolling(3).mean())

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
          ...
95      225.000000
96     3926.666667
97    24693.333333
98     2188.000000
99    18010.000000
Name: profit, Length: 100, dtype: float64

In [162]:
df18.groupby('category')['profit'].transform(lambda x:x.fillna(x.mean()))

0     28500
1      1080
2     13110
3      2700
4       200
      ...
95      280
96     6080
97    28500
98     2520
99    10350
Name: profit, Length: 100, dtype: int64

In [163]:
df18.groupby('category')['profit'].transform('sum')

0     641605
1      48578
2     641605
3      88960
4       7534
       ...
95      7534
96     88960
97    641605
98     48578
99    641605
Name: profit, Length: 100, dtype: int64

In [164]:
df18.groupby('category')['profit'].transform(lambda x:(x-x.mean())/x.std())

0     0.879358
1    -1.607968
2    -0.722248
3    -1.114893
4    -0.653375
        ...
95    0.007961
96    0.786287
97    0.879358
98    0.444592
99   -1.009475
Name: profit, Length: 100, dtype: float64

In [165]:
df18.groupby('category')[['sales','profit']].mean()

                     sales        profit
category
Clothing      11040.454545   2208.090909
Electronics  113084.375000  20050.156250
Furniture     23410.526316   4682.105263
Grocery        1395.185185    279.037037

In [166]:
df19 = pd.read_csv(r"C:\Users\chahat\Downloads\employee_dataset.csv")
df19

,EmployeeID,Name,Department,Region,Gender,Education,Age,YearsExperience,Salary,Bonus,SalesAmount,Target,PerformanceScore,JoinDate
0,1001,Employee_1,Finance,West,Male,PhD,27,5,61616,13446,50336,70300,2.6,2020-03-07
1,1002,Employee_2,Marketing,East,Female,Bachelors,49,21,133727,1218,85314,42677,1.2,2021-11-09
2,1003,Employee_3,HR,West,Female,PhD,49,10,142893,4735,26641,75609,7.9,2023-02-15
3,1004,Employee_4,Marketing,East,Female,Bachelors,41,15,50932,11296,34584,76661,8.3,2021-02-17
4,1005,Employee_5,Marketing,West,Male,PhD,51,15,147796,4555,32745,51024,4.1,2022-08-18
5,1006,Employee_6,IT,North,Male,Masters,32,0,59855,9146,23093,73006,5.2,2025-04-18
6,1007,Employee_7,HR,West,Male,PhD,49,8,91434,8050,66105,35338,6.8,2018-01-27
7,1008,Employee_8,HR,East,Male,Bachelors,46,27,102694,12757,51885,88027,1.4,2019-04-21
8,1009,Employee_9,HR,East,Male,Bachelors,54,26,73016,19830,36631,39508,9.5,2017-09-04
9,1010,Employee_10,Marketing,South,Male,Masters,22,5,37400,17429,72991,23051,9.0,2017-10-05
10,1011,Employee_11,Finance,North,Male,PhD,48,15,147858,6893,4014,68747,3.3,2020-11-13
11,1012,Employee_12,HR,West,Male,PhD,34,28,72642,18077,11093,74021,1.1,2019-08-15
12,1013,Employee_13,Marketing,South,Male,Masters,24,2,45151,14373,18070,86412,9.4,2022-06-03
13,1014,Employee_14,IT,West,Female,PhD,27,19,81407,14565,35777,78335,5.5,2023-12-06
14,1015,Employee_15,Finance,West,Male,PhD,29,27,96690,3436,56958,76179,5.9,2025-06-04
15,1016,Employee_16,IT,South,Female,Bachelors,48,26,34499,8754,82074,52093,7.2,2015-02-06
16,1017,Employee_17,Finance,South,Female,PhD,30,3,36295,10677,10729,89678,6.5,2025-07-18
17,1018,Employee_18,Marketing,South,Female,PhD,58,18,89040,5895,99713,59734,9.5,2024-06-02
18,1019,Employee_19,Sales,South,Male,Masters,54,25,42183,19738,45017,37019,9.5,2025-04-24
19,1020,Employee_20,Finance,South,Male,Masters,45,2,59299,16609,66320,48251,8.8,2019-03-29
20,1021,Employee_21,IT,West,Male,Diploma,36,18,42874,15636,27751,45945,6.7,2021-05-15
21,1022,Employee_22,Marketing,South,Male,Bachelors,53,19,146336,7022,78069,52217,8.2,2021-03-14
22,1023,Employee_23,Finance,North,Female,PhD,53,6,62711,9151,54748,28308,7.1,2022-12-24
23,1024,Employee_24,Sales,East,Male,PhD,45,19,35539,5600,5801,25949,6.2,2017-05-22
24,1025,Employee_25,Sales,South,Male,Diploma,33,8,137941,7996,19190,71990,2.2,2019-12-27
25,1026,Employee_26,HR,South,Male,PhD,23,0,83351,9007,49689,21150,8.3,2018-07-20
26,1027,Employee_27,HR,West,Male,Bachelors,24,7,91267,12946,50993,86617,8.4,2025-10-27
27,1028,Employee_28,IT,South,Male,Diploma,58,6,78354,4642,29592,36896,6.6,2020-10-10
28,1029,Employee_29,Finance,South,Female,Bachelors,38,17,32557,11312,10647,66175,8.4,2016-08-18
29,1030,Employee_30,Finance,South,Male,Diploma,23,7,68360,7679,8716,27805,6.9,2020-03-18
30,1031,Employee_31,HR,West,Female,Diploma,23,0,112018,8208,88891,25237,2.9,2016-12-29
31,1032,Employee_32,Finance,South,Male,Masters,49,10,32200,18589,87545,40056,3.5,2018-09-27
32,1033,Employee_33,Finance,East,Female,Bachelors,44,27,142476,10716,89912,65543,2.9,2016-02-01
33,1034,Employee_34,Sales,West,Male,PhD,58,24,98497,17453,70316,76556,4.4,2016-11-29
34,1035,Employee_35,HR,East,Male,PhD,53,24,76975,3444,2368,23343,1.4,2023-06-18
35,1036,Employee_36,Marketing,West,Female,Bachelors,54,17,51357,10757,77575,33500,6.6,2021-02-02
36,1037,Employee_37,HR,South,Female,PhD,22,22,149121,14434,6655,73222,4.0,2019-06-24
37,1038,Employee_38,Marketing,East,Female,PhD,40,29,107505,1060,70031,49375,6.9,2016-01-31
38,1039,Employee_39,Sales,West,Male,Bachelors,23,9,32869,18711,76429,29662,4.5,2021-10-28
39,1040,Employee_40,IT,North,Female,Diploma,47,2,91135,3420,91083,36964,7.1,2024-01-18
40,1041,Employee_41,Finance,South,Male,Bachelors,53,6,80108,301,87922,79638,4.1,2025-11-30
41,1042,Employee_42,Sales,West,Male,Diploma,27,27,142296,12468,55766,87215,3.3,2015-03-17
42,1043,Employee_43,Finance,North,Female,PhD,53,15,124179,16990,13403,89042,5.5,2015-09-22
43,1044,Employee_44,IT,West,Female,PhD,25,25,120272,19554,32097,33284,7.2,2021-11-07
44,1045,Employee_45,IT,North,Male,PhD,32,15,68467,699,78657,81389,4.1,2019-12-25
45,1046,Employee_46,Sales,South,Male,Masters,38,24,53328,190,10966,29435,9.4,2016-12-18
46,1047,Employee_47,IT,East,Female,Diploma,59,19,149181,10492,99157,74340,1.4,2022-08-14
47,1048,Employee_48,Marketing,North,Female,Masters,45,27,121412,17364,93848,64078,4.8,2024-06-17
48,1049,Employee_49,IT,West,Female,Masters,26,16,116831,2975,52921,71293,9.7,2024-12-14
49,1050,Employee_50,Finance,South,Male,Bachelors,55,1,33987,6102,49726,80403,5.9,2017-04-30

In [167]:
df19['Gender'] = df19['Gender'].apply(lambda x:1 if x=='Male' else 0)

In [168]:
df19

,EmployeeID,Name,Department,Region,Gender,Education,Age,YearsExperience,Salary,Bonus,SalesAmount,Target,PerformanceScore,JoinDate
0,1001,Employee_1,Finance,West,1,PhD,27,5,61616,13446,50336,70300,2.6,2020-03-07
1,1002,Employee_2,Marketing,East,0,Bachelors,49,21,133727,1218,85314,42677,1.2,2021-11-09
2,1003,Employee_3,HR,West,0,PhD,49,10,142893,4735,26641,75609,7.9,2023-02-15
3,1004,Employee_4,Marketing,East,0,Bachelors,41,15,50932,11296,34584,76661,8.3,2021-02-17
4,1005,Employee_5,Marketing,West,1,PhD,51,15,147796,4555,32745,51024,4.1,2022-08-18
5,1006,Employee_6,IT,North,1,Masters,32,0,59855,9146,23093,73006,5.2,2025-04-18
6,1007,Employee_7,HR,West,1,PhD,49,8,91434,8050,66105,35338,6.8,2018-01-27
7,1008,Employee_8,HR,East,1,Bachelors,46,27,102694,12757,51885,88027,1.4,2019-04-21
8,1009,Employee_9,HR,East,1,Bachelors,54,26,73016,19830,36631,39508,9.5,2017-09-04
9,1010,Employee_10,Marketing,South,1,Masters,22,5,37400,17429,72991,23051,9.0,2017-10-05
10,1011,Employee_11,Finance,North,1,PhD,48,15,147858,6893,4014,68747,3.3,2020-11-13
11,1012,Employee_12,HR,West,1,PhD,34,28,72642,18077,11093,74021,1.1,2019-08-15
12,1013,Employee_13,Marketing,South,1,Masters,24,2,45151,14373,18070,86412,9.4,2022-06-03
13,1014,Employee_14,IT,West,0,PhD,27,19,81407,14565,35777,78335,5.5,2023-12-06
14,1015,Employee_15,Finance,West,1,PhD,29,27,96690,3436,56958,76179,5.9,2025-06-04
15,1016,Employee_16,IT,South,0,Bachelors,48,26,34499,8754,82074,52093,7.2,2015-02-06
16,1017,Employee_17,Finance,South,0,PhD,30,3,36295,10677,10729,89678,6.5,2025-07-18
17,1018,Employee_18,Marketing,South,0,PhD,58,18,89040,5895,99713,59734,9.5,2024-06-02
18,1019,Employee_19,Sales,South,1,Masters,54,25,42183,19738,45017,37019,9.5,2025-04-24
19,1020,Employee_20,Finance,South,1,Masters,45,2,59299,16609,66320,48251,8.8,2019-03-29
20,1021,Employee_21,IT,West,1,Diploma,36,18,42874,15636,27751,45945,6.7,2021-05-15
21,1022,Employee_22,Marketing,South,1,Bachelors,53,19,146336,7022,78069,52217,8.2,2021-03-14
22,1023,Employee_23,Finance,North,0,PhD,53,6,62711,9151,54748,28308,7.1,2022-12-24
23,1024,Employee_24,Sales,East,1,PhD,45,19,35539,5600,5801,25949,6.2,2017-05-22
24,1025,Employee_25,Sales,South,1,Diploma,33,8,137941,7996,19190,71990,2.2,2019-12-27
25,1026,Employee_26,HR,South,1,PhD,23,0,83351,9007,49689,21150,8.3,2018-07-20
26,1027,Employee_27,HR,West,1,Bachelors,24,7,91267,12946,50993,86617,8.4,2025-10-27
27,1028,Employee_28,IT,South,1,Diploma,58,6,78354,4642,29592,36896,6.6,2020-10-10
28,1029,Employee_29,Finance,South,0,Bachelors,38,17,32557,11312,10647,66175,8.4,2016-08-18
29,1030,Employee_30,Finance,South,1,Diploma,23,7,68360,7679,8716,27805,6.9,2020-03-18
30,1031,Employee_31,HR,West,0,Diploma,23,0,112018,8208,88891,25237,2.9,2016-12-29
31,1032,Employee_32,Finance,South,1,Masters,49,10,32200,18589,87545,40056,3.5,2018-09-27
32,1033,Employee_33,Finance,East,0,Bachelors,44,27,142476,10716,89912,65543,2.9,2016-02-01
33,1034,Employee_34,Sales,West,1,PhD,58,24,98497,17453,70316,76556,4.4,2016-11-29
34,1035,Employee_35,HR,East,1,PhD,53,24,76975,3444,2368,23343,1.4,2023-06-18
35,1036,Employee_36,Marketing,West,0,Bachelors,54,17,51357,10757,77575,33500,6.6,2021-02-02
36,1037,Employee_37,HR,South,0,PhD,22,22,149121,14434,6655,73222,4.0,2019-06-24
37,1038,Employee_38,Marketing,East,0,PhD,40,29,107505,1060,70031,49375,6.9,2016-01-31
38,1039,Employee_39,Sales,West,1,Bachelors,23,9,32869,18711,76429,29662,4.5,2021-10-28
39,1040,Employee_40,IT,North,0,Diploma,47,2,91135,3420,91083,36964,7.1,2024-01-18
40,1041,Employee_41,Finance,South,1,Bachelors,53,6,80108,301,87922,79638,4.1,2025-11-30
41,1042,Employee_42,Sales,West,1,Diploma,27,27,142296,12468,55766,87215,3.3,2015-03-17
42,1043,Employee_43,Finance,North,0,PhD,53,15,124179,16990,13403,89042,5.5,2015-09-22
43,1044,Employee_44,IT,West,0,PhD,25,25,120272,19554,32097,33284,7.2,2021-11-07
44,1045,Employee_45,IT,North,1,PhD,32,15,68467,699,78657,81389,4.1,2019-12-25
45,1046,Employee_46,Sales,South,1,Masters,38,24,53328,190,10966,29435,9.4,2016-12-18
46,1047,Employee_47,IT,East,0,Diploma,59,19,149181,10492,99157,74340,1.4,2022-08-14
47,1048,Employee_48,Marketing,North,0,Masters,45,27,121412,17364,93848,64078,4.8,2024-06-17
48,1049,Employee_49,IT,West,0,Masters,26,16,116831,2975,52921,71293,9.7,2024-12-14
49,1050,Employee_50,Finance,South,1,Bachelors,55,1,33987,6102,49726,80403,5.9,2017-04-30

In [169]:
df19['Age_Gap'] = df19.apply(lambda x:'Adult' if x['Age'] >= 18 else 'Minor',axis=1)

In [170]:
df19

,EmployeeID,Name,Department,Region,Gender,Education,Age,YearsExperience,Salary,Bonus,SalesAmount,Target,PerformanceScore,JoinDate,Age_Gap
0,1001,Employee_1,Finance,West,1,PhD,27,5,61616,13446,50336,70300,2.6,2020-03-07,Adult
1,1002,Employee_2,Marketing,East,0,Bachelors,49,21,133727,1218,85314,42677,1.2,2021-11-09,Adult
2,1003,Employee_3,HR,West,0,PhD,49,10,142893,4735,26641,75609,7.9,2023-02-15,Adult
3,1004,Employee_4,Marketing,East,0,Bachelors,41,15,50932,11296,34584,76661,8.3,2021-02-17,Adult
4,1005,Employee_5,Marketing,West,1,PhD,51,15,147796,4555,32745,51024,4.1,2022-08-18,Adult
5,1006,Employee_6,IT,North,1,Masters,32,0,59855,9146,23093,73006,5.2,2025-04-18,Adult
6,1007,Employee_7,HR,West,1,PhD,49,8,91434,8050,66105,35338,6.8,2018-01-27,Adult
7,1008,Employee_8,HR,East,1,Bachelors,46,27,102694,12757,51885,88027,1.4,2019-04-21,Adult
8,1009,Employee_9,HR,East,1,Bachelors,54,26,73016,19830,36631,39508,9.5,2017-09-04,Adult
9,1010,Employee_10,Marketing,South,1,Masters,22,5,37400,17429,72991,23051,9.0,2017-10-05,Adult
10,1011,Employee_11,Finance,North,1,PhD,48,15,147858,6893,4014,68747,3.3,2020-11-13,Adult
11,1012,Employee_12,HR,West,1,PhD,34,28,72642,18077,11093,74021,1.1,2019-08-15,Adult
12,1013,Employee_13,Marketing,South,1,Masters,24,2,45151,14373,18070,86412,9.4,2022-06-03,Adult
13,1014,Employee_14,IT,West,0,PhD,27,19,81407,14565,35777,78335,5.5,2023-12-06,Adult
14,1015,Employee_15,Finance,West,1,PhD,29,27,96690,3436,56958,76179,5.9,2025-06-04,Adult
15,1016,Employee_16,IT,South,0,Bachelors,48,26,34499,8754,82074,52093,7.2,2015-02-06,Adult
16,1017,Employee_17,Finance,South,0,PhD,30,3,36295,10677,10729,89678,6.5,2025-07-18,Adult
17,1018,Employee_18,Marketing,South,0,PhD,58,18,89040,5895,99713,59734,9.5,2024-06-02,Adult
18,1019,Employee_19,Sales,South,1,Masters,54,25,42183,19738,45017,37019,9.5,2025-04-24,Adult
19,1020,Employee_20,Finance,South,1,Masters,45,2,59299,16609,66320,48251,8.8,2019-03-29,Adult
20,1021,Employee_21,IT,West,1,Diploma,36,18,42874,15636,27751,45945,6.7,2021-05-15,Adult
21,1022,Employee_22,Marketing,South,1,Bachelors,53,19,146336,7022,78069,52217,8.2,2021-03-14,Adult
22,1023,Employee_23,Finance,North,0,PhD,53,6,62711,9151,54748,28308,7.1,2022-12-24,Adult
23,1024,Employee_24,Sales,East,1,PhD,45,19,35539,5600,5801,25949,6.2,2017-05-22,Adult
24,1025,Employee_25,Sales,South,1,Diploma,33,8,137941,7996,19190,71990,2.2,2019-12-27,Adult
25,1026,Employee_26,HR,South,1,PhD,23,0,83351,9007,49689,21150,8.3,2018-07-20,Adult
26,1027,Employee_27,HR,West,1,Bachelors,24,7,91267,12946,50993,86617,8.4,2025-10-27,Adult
27,1028,Employee_28,IT,South,1,Diploma,58,6,78354,4642,29592,36896,6.6,2020-10-10,Adult
28,1029,Employee_29,Finance,South,0,Bachelors,38,17,32557,11312,10647,66175,8.4,2016-08-18,Adult
29,1030,Employee_30,Finance,South,1,Diploma,23,7,68360,7679,8716,27805,6.9,2020-03-18,Adult
30,1031,Employee_31,HR,West,0,Diploma,23,0,112018,8208,88891,25237,2.9,2016-12-29,Adult
31,1032,Employee_32,Finance,South,1,Masters,49,10,32200,18589,87545,40056,3.5,2018-09-27,Adult
32,1033,Employee_33,Finance,East,0,Bachelors,44,27,142476,10716,89912,65543,2.9,2016-02-01,Adult
33,1034,Employee_34,Sales,West,1,PhD,58,24,98497,17453,70316,76556,4.4,2016-11-29,Adult
34,1035,Employee_35,HR,East,1,PhD,53,24,76975,3444,2368,23343,1.4,2023-06-18,Adult
35,1036,Employee_36,Marketing,West,0,Bachelors,54,17,51357,10757,77575,33500,6.6,2021-02-02,Adult
36,1037,Employee_37,HR,South,0,PhD,22,22,149121,14434,6655,73222,4.0,2019-06-24,Adult
37,1038,Employee_38,Marketing,East,0,PhD,40,29,107505,1060,70031,49375,6.9,2016-01-31,Adult
38,1039,Employee_39,Sales,West,1,Bachelors,23,9,32869,18711,76429,29662,4.5,2021-10-28,Adult
39,1040,Employee_40,IT,North,0,Diploma,47,2,91135,3420,91083,36964,7.1,2024-01-18,Adult
40,1041,Employee_41,Finance,South,1,Bachelors,53,6,80108,301,87922,79638,4.1,2025-11-30,Adult
41,1042,Employee_42,Sales,West,1,Diploma,27,27,142296,12468,55766,87215,3.3,2015-03-17,Adult
42,1043,Employee_43,Finance,North,0,PhD,53,15,124179,16990,13403,89042,5.5,2015-09-22,Adult
43,1044,Employee_44,IT,West,0,PhD,25,25,120272,19554,32097,33284,7.2,2021-11-07,Adult
44,1045,Employee_45,IT,North,1,PhD,32,15,68467,699,78657,81389,4.1,2019-12-25,Adult
45,1046,Employee_46,Sales,South,1,Masters,38,24,53328,190,10966,29435,9.4,2016-12-18,Adult
46,1047,Employee_47,IT,East,0,Diploma,59,19,149181,10492,99157,74340,1.4,2022-08-14,Adult
47,1048,Employee_48,Marketing,North,0,Masters,45,27,121412,17364,93848,64078,4.8,2024-06-17,Adult
48,1049,Employee_49,IT,West,0,Masters,26,16,116831,2975,52921,71293,9.7,2024-12-14,Adult
49,1050,Employee_50,Finance,South,1,Bachelors,55,1,33987,6102,49726,80403,5.9,2017-04-30,Adult

In [171]:
df19['Region'].unique()

array(['West', 'East', 'North', 'South'], dtype=object)

In [172]:
df19['Region'] = df19['Region'].map({
    'West':1,
    'East':2,
    'North':3,
    'South':4
})

In [173]:
df19['Age_Gap'] = df19['Age_Gap'].replace({
    'Adult':'above 18'
})

In [174]:
df19

,EmployeeID,Name,Department,Region,Gender,Education,Age,YearsExperience,Salary,Bonus,SalesAmount,Target,PerformanceScore,JoinDate,Age_Gap
0,1001,Employee_1,Finance,1,1,PhD,27,5,61616,13446,50336,70300,2.6,2020-03-07,above 18
1,1002,Employee_2,Marketing,2,0,Bachelors,49,21,133727,1218,85314,42677,1.2,2021-11-09,above 18
2,1003,Employee_3,HR,1,0,PhD,49,10,142893,4735,26641,75609,7.9,2023-02-15,above 18
3,1004,Employee_4,Marketing,2,0,Bachelors,41,15,50932,11296,34584,76661,8.3,2021-02-17,above 18
4,1005,Employee_5,Marketing,1,1,PhD,51,15,147796,4555,32745,51024,4.1,2022-08-18,above 18
5,1006,Employee_6,IT,3,1,Masters,32,0,59855,9146,23093,73006,5.2,2025-04-18,above 18
6,1007,Employee_7,HR,1,1,PhD,49,8,91434,8050,66105,35338,6.8,2018-01-27,above 18
7,1008,Employee_8,HR,2,1,Bachelors,46,27,102694,12757,51885,88027,1.4,2019-04-21,above 18
8,1009,Employee_9,HR,2,1,Bachelors,54,26,73016,19830,36631,39508,9.5,2017-09-04,above 18
9,1010,Employee_10,Marketing,4,1,Masters,22,5,37400,17429,72991,23051,9.0,2017-10-05,above 18
10,1011,Employee_11,Finance,3,1,PhD,48,15,147858,6893,4014,68747,3.3,2020-11-13,above 18
11,1012,Employee_12,HR,1,1,PhD,34,28,72642,18077,11093,74021,1.1,2019-08-15,above 18
12,1013,Employee_13,Marketing,4,1,Masters,24,2,45151,14373,18070,86412,9.4,2022-06-03,above 18
13,1014,Employee_14,IT,1,0,PhD,27,19,81407,14565,35777,78335,5.5,2023-12-06,above 18
14,1015,Employee_15,Finance,1,1,PhD,29,27,96690,3436,56958,76179,5.9,2025-06-04,above 18
15,1016,Employee_16,IT,4,0,Bachelors,48,26,34499,8754,82074,52093,7.2,2015-02-06,above 18
16,1017,Employee_17,Finance,4,0,PhD,30,3,36295,10677,10729,89678,6.5,2025-07-18,above 18
17,1018,Employee_18,Marketing,4,0,PhD,58,18,89040,5895,99713,59734,9.5,2024-06-02,above 18
18,1019,Employee_19,Sales,4,1,Masters,54,25,42183,19738,45017,37019,9.5,2025-04-24,above 18
19,1020,Employee_20,Finance,4,1,Masters,45,2,59299,16609,66320,48251,8.8,2019-03-29,above 18
20,1021,Employee_21,IT,1,1,Diploma,36,18,42874,15636,27751,45945,6.7,2021-05-15,above 18
21,1022,Employee_22,Marketing,4,1,Bachelors,53,19,146336,7022,78069,52217,8.2,2021-03-14,above 18
22,1023,Employee_23,Finance,3,0,PhD,53,6,62711,9151,54748,28308,7.1,2022-12-24,above 18
23,1024,Employee_24,Sales,2,1,PhD,45,19,35539,5600,5801,25949,6.2,2017-05-22,above 18
24,1025,Employee_25,Sales,4,1,Diploma,33,8,137941,7996,19190,71990,2.2,2019-12-27,above 18
25,1026,Employee_26,HR,4,1,PhD,23,0,83351,9007,49689,21150,8.3,2018-07-20,above 18
26,1027,Employee_27,HR,1,1,Bachelors,24,7,91267,12946,50993,86617,8.4,2025-10-27,above 18
27,1028,Employee_28,IT,4,1,Diploma,58,6,78354,4642,29592,36896,6.6,2020-10-10,above 18
28,1029,Employee_29,Finance,4,0,Bachelors,38,17,32557,11312,10647,66175,8.4,2016-08-18,above 18
29,1030,Employee_30,Finance,4,1,Diploma,23,7,68360,7679,8716,27805,6.9,2020-03-18,above 18
30,1031,Employee_31,HR,1,0,Diploma,23,0,112018,8208,88891,25237,2.9,2016-12-29,above 18
31,1032,Employee_32,Finance,4,1,Masters,49,10,32200,18589,87545,40056,3.5,2018-09-27,above 18
32,1033,Employee_33,Finance,2,0,Bachelors,44,27,142476,10716,89912,65543,2.9,2016-02-01,above 18
33,1034,Employee_34,Sales,1,1,PhD,58,24,98497,17453,70316,76556,4.4,2016-11-29,above 18
34,1035,Employee_35,HR,2,1,PhD,53,24,76975,3444,2368,23343,1.4,2023-06-18,above 18
35,1036,Employee_36,Marketing,1,0,Bachelors,54,17,51357,10757,77575,33500,6.6,2021-02-02,above 18
36,1037,Employee_37,HR,4,0,PhD,22,22,149121,14434,6655,73222,4.0,2019-06-24,above 18
37,1038,Employee_38,Marketing,2,0,PhD,40,29,107505,1060,70031,49375,6.9,2016-01-31,above 18
38,1039,Employee_39,Sales,1,1,Bachelors,23,9,32869,18711,76429,29662,4.5,2021-10-28,above 18
39,1040,Employee_40,IT,3,0,Diploma,47,2,91135,3420,91083,36964,7.1,2024-01-18,above 18
40,1041,Employee_41,Finance,4,1,Bachelors,53,6,80108,301,87922,79638,4.1,2025-11-30,above 18
41,1042,Employee_42,Sales,1,1,Diploma,27,27,142296,12468,55766,87215,3.3,2015-03-17,above 18
42,1043,Employee_43,Finance,3,0,PhD,53,15,124179,16990,13403,89042,5.5,2015-09-22,above 18
43,1044,Employee_44,IT,1,0,PhD,25,25,120272,19554,32097,33284,7.2,2021-11-07,above 18
44,1045,Employee_45,IT,3,1,PhD,32,15,68467,699,78657,81389,4.1,2019-12-25,above 18
45,1046,Employee_46,Sales,4,1,Masters,38,24,53328,190,10966,29435,9.4,2016-12-18,above 18
46,1047,Employee_47,IT,2,0,Diploma,59,19,149181,10492,99157,74340,1.4,2022-08-14,above 18
47,1048,Employee_48,Marketing,3,0,Masters,45,27,121412,17364,93848,64078,4.8,2024-06-17,above 18
48,1049,Employee_49,IT,1,0,Masters,26,16,116831,2975,52921,71293,9.7,2024-12-14,above 18
49,1050,Employee_50,Finance,4,1,Bachelors,55,1,33987,6102,49726,80403,5.9,2017-04-30,above 18

In [175]:
df19.groupby('Department')['Salary'].transform(lambda x:x.mean())

0     75256.615385
1     93065.600000
2     99541.100000
3     93065.600000
4     93065.600000
5     84287.500000
6     99541.100000
7     99541.100000
8     99541.100000
9     93065.600000
10    75256.615385
11    99541.100000
12    93065.600000
13    84287.500000
14    75256.615385
15    84287.500000
16    75256.615385
17    93065.600000
18    77521.857143
19    75256.615385
20    84287.500000
21    93065.600000
22    75256.615385
23    77521.857143
24    77521.857143
25    99541.100000
26    99541.100000
27    84287.500000
28    75256.615385
29    75256.615385
30    99541.100000
31    75256.615385
32    75256.615385
33    77521.857143
34    99541.100000
35    93065.600000
36    99541.100000
37    93065.600000
38    77521.857143
39    84287.500000
40    75256.615385
41    77521.857143
42    75256.615385
43    84287.500000
44    84287.500000
45    77521.857143
46    84287.500000
47    93065.600000
48    84287.500000
49    75256.615385
Name: Salary, dtype: float64

In [176]:
df19['Age'] = df19['Age'].transform(lambda x:(x-x.mean())/x.std())

In [177]:
df19.groupby('Department')['Salary'].transform(lambda x:(x-x.mean())/x.std())

0    -0.332387
1     0.924122
2     1.573017
3    -0.957581
4     1.243871
5    -0.677730
6    -0.294165
7     0.114402
8    -0.962459
9    -1.265126
10    1.769112
11   -0.976029
12   -1.088967
13   -0.079902
14    0.522277
15   -1.381078
16   -0.949396
17   -0.091491
18   -0.734826
19   -0.388847
20   -1.148764
21    1.210690
22   -0.305705
23   -0.872979
24    1.256338
25   -0.587455
26   -0.300224
27   -0.164589
28   -1.040482
29   -0.168053
30    0.452722
31   -1.049181
32    1.637967
33    0.436151
34   -0.818807
35   -0.947922
36    1.798999
37    0.328168
38   -0.928499
39    0.189942
40    0.118216
41    1.346895
42    1.192115
43    0.998170
44   -0.438843
45   -0.503080
46    1.800073
47    0.644236
48    0.902720
49   -1.005636
Name: Salary, dtype: float64

In [178]:
df19['Adult_Flag'] = (df19['Age']>=18)

In [179]:
df19['Gender'] = df19['Gender'].apply(lambda x:'Male' if x==1 else 'Female')

In [180]:
df19

,EmployeeID,Name,Department,Region,Gender,Education,Age,YearsExperience,Salary,Bonus,SalesAmount,Target,PerformanceScore,JoinDate,Age_Gap,Adult_Flag
0,1001,Employee_1,Finance,1,Male,PhD,-1.103100,5,61616,13446,50336,70300,2.6,2020-03-07,above 18,False
1,1002,Employee_2,Marketing,2,Female,Bachelors,0.683955,21,133727,1218,85314,42677,1.2,2021-11-09,above 18,False
2,1003,Employee_3,HR,1,Female,PhD,0.683955,10,142893,4735,26641,75609,7.9,2023-02-15,above 18,False
3,1004,Employee_4,Marketing,2,Female,Bachelors,0.034117,15,50932,11296,34584,76661,8.3,2021-02-17,above 18,False
4,1005,Employee_5,Marketing,1,Male,PhD,0.846414,15,147796,4555,32745,51024,4.1,2022-08-18,above 18,False
5,1006,Employee_6,IT,3,Male,Masters,-0.696952,0,59855,9146,23093,73006,5.2,2025-04-18,above 18,False
6,1007,Employee_7,HR,1,Male,PhD,0.683955,8,91434,8050,66105,35338,6.8,2018-01-27,above 18,False
7,1008,Employee_8,HR,2,Male,Bachelors,0.440265,27,102694,12757,51885,88027,1.4,2019-04-21,above 18,False
8,1009,Employee_9,HR,2,Male,Bachelors,1.090104,26,73016,19830,36631,39508,9.5,2017-09-04,above 18,False
9,1010,Employee_10,Marketing,4,Male,Masters,-1.509249,5,37400,17429,72991,23051,9.0,2017-10-05,above 18,False
10,1011,Employee_11,Finance,3,Male,PhD,0.602725,15,147858,6893,4014,68747,3.3,2020-11-13,above 18,False
11,1012,Employee_12,HR,1,Male,PhD,-0.534492,28,72642,18077,11093,74021,1.1,2019-08-15,above 18,False
12,1013,Employee_13,Marketing,4,Male,Masters,-1.346790,2,45151,14373,18070,86412,9.4,2022-06-03,above 18,False
13,1014,Employee_14,IT,1,Female,PhD,-1.103100,19,81407,14565,35777,78335,5.5,2023-12-06,above 18,False
14,1015,Employee_15,Finance,1,Male,PhD,-0.940641,27,96690,3436,56958,76179,5.9,2025-06-04,above 18,False
15,1016,Employee_16,IT,4,Female,Bachelors,0.602725,26,34499,8754,82074,52093,7.2,2015-02-06,above 18,False
16,1017,Employee_17,Finance,4,Female,PhD,-0.859411,3,36295,10677,10729,89678,6.5,2025-07-18,above 18,False
17,1018,Employee_18,Marketing,4,Female,PhD,1.415023,18,89040,5895,99713,59734,9.5,2024-06-02,above 18,False
18,1019,Employee_19,Sales,4,Male,Masters,1.090104,25,42183,19738,45017,37019,9.5,2025-04-24,above 18,False
19,1020,Employee_20,Finance,4,Male,Masters,0.359036,2,59299,16609,66320,48251,8.8,2019-03-29,above 18,False
20,1021,Employee_21,IT,1,Male,Diploma,-0.372032,18,42874,15636,27751,45945,6.7,2021-05-15,above 18,False
21,1022,Employee_22,Marketing,4,Male,Bachelors,1.008874,19,146336,7022,78069,52217,8.2,2021-03-14,above 18,False
22,1023,Employee_23,Finance,3,Female,PhD,1.008874,6,62711,9151,54748,28308,7.1,2022-12-24,above 18,False
23,1024,Employee_24,Sales,2,Male,PhD,0.359036,19,35539,5600,5801,25949,6.2,2017-05-22,above 18,False
24,1025,Employee_25,Sales,4,Male,Diploma,-0.615722,8,137941,7996,19190,71990,2.2,2019-12-27,above 18,False
25,1026,Employee_26,HR,4,Male,PhD,-1.428020,0,83351,9007,49689,21150,8.3,2018-07-20,above 18,False
26,1027,Employee_27,HR,1,Male,Bachelors,-1.346790,7,91267,12946,50993,86617,8.4,2025-10-27,above 18,False
27,1028,Employee_28,IT,4,Male,Diploma,1.415023,6,78354,4642,29592,36896,6.6,2020-10-10,above 18,False
28,1029,Employee_29,Finance,4,Female,Bachelors,-0.209573,17,32557,11312,10647,66175,8.4,2016-08-18,above 18,False
29,1030,Employee_30,Finance,4,Male,Diploma,-1.428020,7,68360,7679,8716,27805,6.9,2020-03-18,above 18,False
30,1031,Employee_31,HR,1,Female,Diploma,-1.428020,0,112018,8208,88891,25237,2.9,2016-12-29,above 18,False
31,1032,Employee_32,Finance,4,Male,Masters,0.683955,10,32200,18589,87545,40056,3.5,2018-09-27,above 18,False
32,1033,Employee_33,Finance,2,Female,Bachelors,0.277806,27,142476,10716,89912,65543,2.9,2016-02-01,above 18,False
33,1034,Employee_34,Sales,1,Male,PhD,1.415023,24,98497,17453,70316,76556,4.4,2016-11-29,above 18,False
34,1035,Employee_35,HR,2,Male,PhD,1.008874,24,76975,3444,2368,23343,1.4,2023-06-18,above 18,False
35,1036,Employee_36,Marketing,1,Female,Bachelors,1.090104,17,51357,10757,77575,33500,6.6,2021-02-02,above 18,False
36,1037,Employee_37,HR,4,Female,PhD,-1.509249,22,149121,14434,6655,73222,4.0,2019-06-24,above 18,False
37,1038,Employee_38,Marketing,2,Female,PhD,-0.047113,29,107505,1060,70031,49375,6.9,2016-01-31,above 18,False
38,1039,Employee_39,Sales,1,Male,Bachelors,-1.428020,9,32869,18711,76429,29662,4.5,2021-10-28,above 18,False
39,1040,Employee_40,IT,3,Female,Diploma,0.521495,2,91135,3420,91083,36964,7.1,2024-01-18,above 18,False
40,1041,Employee_41,Finance,4,Male,Bachelors,1.008874,6,80108,301,87922,79638,4.1,2025-11-30,above 18,False
41,1042,Employee_42,Sales,1,Male,Diploma,-1.103100,27,142296,12468,55766,87215,3.3,2015-03-17,above 18,False
42,1043,Employee_43,Finance,3,Female,PhD,1.008874,15,124179,16990,13403,89042,5.5,2015-09-22,above 18,False
43,1044,Employee_44,IT,1,Female,PhD,-1.265560,25,120272,19554,32097,33284,7.2,2021-11-07,above 18,False
44,1045,Employee_45,IT,3,Male,PhD,-0.696952,15,68467,699,78657,81389,4.1,2019-12-25,above 18,False
45,1046,Employee_46,Sales,4,Male,Masters,-0.209573,24,53328,190,10966,29435,9.4,2016-12-18,above 18,False
46,1047,Employee_47,IT,2,Female,Diploma,1.496253,19,149181,10492,99157,74340,1.4,2022-08-14,above 18,False
47,1048,Employee_48,Marketing,3,Female,Masters,0.359036,27,121412,17364,93848,64078,4.8,2024-06-17,above 18,False
48,1049,Employee_49,IT,1,Female,Masters,-1.184330,16,116831,2975,52921,71293,9.7,2024-12-14,above 18,False
49,1050,Employee_50,Finance,4,Male,Bachelors,1.171334,1,33987,6102,49726,80403,5.9,2017-04-30,above 18,False

In [181]:
df19['position'] = np.where(df19['YearsExperience'] >= 10,'senior','junior')

In [182]:
df19[df19['Education'].str.startswith('B')]

,EmployeeID,Name,Department,Region,Gender,Education,Age,YearsExperience,Salary,Bonus,SalesAmount,Target,PerformanceScore,JoinDate,Age_Gap,Adult_Flag,position
1,1002,Employee_2,Marketing,2,Female,Bachelors,0.683955,21,133727,1218,85314,42677,1.2,2021-11-09,above 18,False,senior
3,1004,Employee_4,Marketing,2,Female,Bachelors,0.034117,15,50932,11296,34584,76661,8.3,2021-02-17,above 18,False,senior
7,1008,Employee_8,HR,2,Male,Bachelors,0.440265,27,102694,12757,51885,88027,1.4,2019-04-21,above 18,False,senior
8,1009,Employee_9,HR,2,Male,Bachelors,1.090104,26,73016,19830,36631,39508,9.5,2017-09-04,above 18,False,senior
15,1016,Employee_16,IT,4,Female,Bachelors,0.602725,26,34499,8754,82074,52093,7.2,2015-02-06,above 18,False,senior
21,1022,Employee_22,Marketing,4,Male,Bachelors,1.008874,19,146336,7022,78069,52217,8.2,2021-03-14,above 18,False,senior
26,1027,Employee_27,HR,1,Male,Bachelors,-1.346790,7,91267,12946,50993,86617,8.4,2025-10-27,above 18,False,junior
28,1029,Employee_29,Finance,4,Female,Bachelors,-0.209573,17,32557,11312,10647,66175,8.4,2016-08-18,above 18,False,senior
32,1033,Employee_33,Finance,2,Female,Bachelors,0.277806,27,142476,10716,89912,65543,2.9,2016-02-01,above 18,False,senior
35,1036,Employee_36,Marketing,1,Female,Bachelors,1.090104,17,51357,10757,77575,33500,6.6,2021-02-02,above 18,False,senior
38,1039,Employee_39,Sales,1,Male,Bachelors,-1.428020,9,32869,18711,76429,29662,4.5,2021-10-28,above 18,False,junior
40,1041,Employee_41,Finance,4,Male,Bachelors,1.008874,6,80108,301,87922,79638,4.1,2025-11-30,above 18,False,junior
49,1050,Employee_50,Finance,4,Male,Bachelors,1.171334,1,33987,6102,49726,80403,5.9,2017-04-30,above 18,False,junior

In [183]:
df20 = pd.read_csv(r"C:\Users\chahat\Downloads\employees(2).csv")
df20

   employee_id     name dept_id       location  salary
0          101    Alice      D1       New York   72000
1          102      Bob      D2    Los Angeles   65000
2          103  Charlie      D3       New York   80000
3          104    David      D5  San Francisco   71000
4          105      Eva      D1       New York   69000
5          106    Frank     NaN        Chicago   58000
6          107    Grace      D2    Los Angeles   62000
7          108    Helen      D6         Boston   75000

In [184]:
df21 = pd.read_csv(r"C:\Users\chahat\Downloads\departments.csv")
df21

  dept_id  dept_name       manager
0      D1      Sales  Mike Johnson
1      D2  Marketing     Sarah Lee
2      D3         IT     Tom Brown
3      D4         HR    Nina Patel
4      D7    Finance     Omar Khan

In [185]:
df22 = pd.merge(df20,df21,on='dept_id',how='inner')

In [186]:
df22

   employee_id     name dept_id     location  salary  dept_name       manager
0          101    Alice      D1     New York   72000      Sales  Mike Johnson
1          102      Bob      D2  Los Angeles   65000  Marketing     Sarah Lee
2          103  Charlie      D3     New York   80000         IT     Tom Brown
3          105      Eva      D1     New York   69000      Sales  Mike Johnson
4          107    Grace      D2  Los Angeles   62000  Marketing     Sarah Lee

In [187]:
df23 = pd.merge(df20,df21,on='dept_id',how='left')

In [188]:
df23

,employee_id,name,dept_id,location,salary,dept_name,manager
0,101,Alice,D1,New York,72000,Sales,Mike Johnson
1,102,Bob,D2,Los Angeles,65000,Marketing,Sarah Lee
2,103,Charlie,D3,New York,80000,IT,Tom Brown
3,104,David,D5,San Francisco,71000,NaN,NaN
4,105,Eva,D1,New York,69000,Sales,Mike Johnson
5,106,Frank,NaN,Chicago,58000,NaN,NaN
6,107,Grace,D2,Los Angeles,62000,Marketing,Sarah Lee
7,108,Helen,D6,Boston,75000,NaN,NaN

In [189]:
df24 = pd.merge(df20,df21,on='dept_id',how='right')

In [190]:
df24

   employee_id     name dept_id     location   salary  dept_name       manager
0        101.0    Alice      D1     New York  72000.0      Sales  Mike Johnson
1        105.0      Eva      D1     New York  69000.0      Sales  Mike Johnson
2        102.0      Bob      D2  Los Angeles  65000.0  Marketing     Sarah Lee
3        107.0    Grace      D2  Los Angeles  62000.0  Marketing     Sarah Lee
4        103.0  Charlie      D3     New York  80000.0         IT     Tom Brown
5          NaN      NaN      D4          NaN      NaN         HR    Nina Patel
6          NaN      NaN      D7          NaN      NaN    Finance     Omar Khan

In [191]:
df25 = pd.merge(df20,df21,on='dept_id',how='outer')

In [192]:
df25

,employee_id,name,dept_id,location,salary,dept_name,manager
0,101.0,Alice,D1,New York,72000.0,Sales,Mike Johnson
1,105.0,Eva,D1,New York,69000.0,Sales,Mike Johnson
2,102.0,Bob,D2,Los Angeles,65000.0,Marketing,Sarah Lee
3,107.0,Grace,D2,Los Angeles,62000.0,Marketing,Sarah Lee
4,103.0,Charlie,D3,New York,80000.0,IT,Tom Brown
5,NaN,NaN,D4,NaN,NaN,HR,Nina Patel
6,104.0,David,D5,San Francisco,71000.0,NaN,NaN
7,108.0,Helen,D6,Boston,75000.0,NaN,NaN
8,NaN,NaN,D7,NaN,NaN,Finance,Omar Khan
9,106.0,Frank,NaN,Chicago,58000.0,NaN,NaN

In [193]:
df26 = pd.DataFrame({
    'id':[1,2,3,4,5,6,7,8]
})
df20 = pd.concat([df20,df26],axis=1)

In [194]:
df21 = pd.concat([df21,df26],axis=1)

In [195]:
df27 = pd.merge(df20,df21,on=['dept_id','id'],how='inner')

In [196]:
df27

,employee_id,name,dept_id,location,salary,id,dept_name,manager
0,101,Alice,D1,New York,72000,1,Sales,Mike Johnson
1,102,Bob,D2,Los Angeles,65000,2,Marketing,Sarah Lee
2,103,Charlie,D3,New York,80000,3,IT,Tom Brown
3,106,Frank,NaN,Chicago,58000,6,NaN,NaN

In [197]:
df28 = pd.merge(df20,df21,on=['dept_id','id'],how='outer',indicator=True)

In [198]:
df28

,employee_id,name,dept_id,location,salary,id,dept_name,manager,_merge
0,101.0,Alice,D1,New York,72000.0,1,Sales,Mike Johnson,both
1,105.0,Eva,D1,New York,69000.0,5,NaN,NaN,left_only
2,102.0,Bob,D2,Los Angeles,65000.0,2,Marketing,Sarah Lee,both
3,107.0,Grace,D2,Los Angeles,62000.0,7,NaN,NaN,left_only
4,103.0,Charlie,D3,New York,80000.0,3,IT,Tom Brown,both
5,NaN,NaN,D4,NaN,NaN,4,HR,Nina Patel,right_only
6,104.0,David,D5,San Francisco,71000.0,4,NaN,NaN,left_only
7,108.0,Helen,D6,Boston,75000.0,8,NaN,NaN,left_only
8,NaN,NaN,D7,NaN,NaN,5,Finance,Omar Khan,right_only
9,106.0,Frank,NaN,Chicago,58000.0,6,NaN,NaN,both
10,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,right_only
11,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,right_only

In [199]:
 df20 = df20.rename(columns={
     'id':'id_1'
 })

In [200]:
df29 = pd.merge(df20,df21,left_on='id_1',right_on='id',how='inner')

In [201]:
df29

,employee_id,name,dept_id_x,location,salary,id_1,dept_id_y,dept_name,manager,id
0,101,Alice,D1,New York,72000,1,D1,Sales,Mike Johnson,1
1,102,Bob,D2,Los Angeles,65000,2,D2,Marketing,Sarah Lee,2
2,103,Charlie,D3,New York,80000,3,D3,IT,Tom Brown,3
3,104,David,D5,San Francisco,71000,4,D4,HR,Nina Patel,4
4,105,Eva,D1,New York,69000,5,D7,Finance,Omar Khan,5
5,106,Frank,NaN,Chicago,58000,6,NaN,NaN,NaN,6
6,107,Grace,D2,Los Angeles,62000,7,NaN,NaN,NaN,7
7,108,Helen,D6,Boston,75000,8,NaN,NaN,NaN,8

In [202]:
df20 = df20.rename(columns={
    'id_1':'id'
})

In [203]:
df20.columns

Index(['employee_id', 'name', 'dept_id', 'location', 'salary', 'id'], dtype='object')

In [204]:
df30 = df20.join(df21,on='id',how='inner',lsuffix='_left',rsuffix='_right')

In [205]:
df30

,id,employee_id,name,dept_id_left,location,salary,id_left,dept_id_right,dept_name,manager,id_right
0,1,101,Alice,D1,New York,72000,1,D2,Marketing,Sarah Lee,2
1,2,102,Bob,D2,Los Angeles,65000,2,D3,IT,Tom Brown,3
2,3,103,Charlie,D3,New York,80000,3,D4,HR,Nina Patel,4
3,4,104,David,D5,San Francisco,71000,4,D7,Finance,Omar Khan,5
4,5,105,Eva,D1,New York,69000,5,NaN,NaN,NaN,6
5,6,106,Frank,NaN,Chicago,58000,6,NaN,NaN,NaN,7
6,7,107,Grace,D2,Los Angeles,62000,7,NaN,NaN,NaN,8

In [206]:
df31 = pd.read_csv(r"C:\Users\chahat\Downloads\sales_jan.csv")
df31

  order_id  order_date   product  amount
0       J1  2026-01-05  Widget A     120
1       J2  2026-01-12  Widget B      75
2       J3  2026-01-20  Widget A     150

In [207]:
df32 = pd.read_csv(r"C:\Users\chahat\Downloads\sales_feb.csv")
df32

  order_id  order_date   product  amount
0       F1  2026-02-02  Widget B      90
1       F2  2026-02-15  Widget C     200
2       F3  2026-02-25  Widget A     130

In [208]:
df33 = pd.concat([df31,df32],ignore_index=True)

In [209]:
df33

  order_id  order_date   product  amount
0       J1  2026-01-05  Widget A     120
1       J2  2026-01-12  Widget B      75
2       J3  2026-01-20  Widget A     150
3       F1  2026-02-02  Widget B      90
4       F2  2026-02-15  Widget C     200
5       F3  2026-02-25  Widget A     130

In [210]:
df34 = pd.read_csv(r"C:\Users\chahat\Downloads\employee_basic.csv")
df34

   employee_id     name
0          101    Alice
1          102      Bob
2          103  Charlie

In [211]:
df35 = pd.read_csv(r"C:\Users\chahat\Downloads\employee_contact.csv")
df35

   employee_id                email     phone
0          101    alice@example.com  555-0101
1          102      bob@example.com  555-0102
2          103  charlie@example.com  555-0103

In [212]:
df36 = pd.concat([df34,df35],axis=1)

In [213]:
df36

   employee_id     name  employee_id                email     phone
0          101    Alice          101    alice@example.com  555-0101
1          102      Bob          102      bob@example.com  555-0102
2          103  Charlie          103  charlie@example.com  555-0103

In [214]:
df37 = pd.read_csv(r"C:\Users\chahat\Downloads\customers.csv")
df37

  customer_id customer_name region
0          C1     Acme Corp   East
1          C1     Acme Corp   East
2          C2      Beta LLC   West
3          C3     Gamma Inc  South

In [215]:
df38 = pd.read_csv(r"C:\Users\chahat\Downloads\orders.csv")
df38

  order_id customer_id  amount
0       O1          C1     250
1       O2          C1     400
2       O3          C2     150
3       O4          C5     300

In [216]:
df39 = pd.merge(df37,df38,on='customer_id',how='outer')

In [217]:
df39

  customer_id customer_name region order_id  amount
0          C1     Acme Corp   East       O1   250.0
1          C1     Acme Corp   East       O2   400.0
2          C1     Acme Corp   East       O1   250.0
3          C1     Acme Corp   East       O2   400.0
4          C2      Beta LLC   West       O3   150.0
5          C3     Gamma Inc  South      NaN     NaN
6          C5           NaN    NaN       O4   300.0

In [218]:
df39.drop_duplicates(keep='first',inplace=True)

In [219]:
df39

  customer_id customer_name region order_id  amount
0          C1     Acme Corp   East       O1   250.0
1          C1     Acme Corp   East       O2   400.0
4          C2      Beta LLC   West       O3   150.0
5          C3     Gamma Inc  South      NaN     NaN
6          C5           NaN    NaN       O4   300.0

In [220]:
df40 = pd.read_csv(r"C:\Users\chahat\Downloads\students.csv")
df40

  student_id student_name
0         S1         Liam
1         S2         Maya
2         S3         Noah

In [221]:
df41 = pd.read_csv(r"C:\Users\chahat\Downloads\courses.csv")
df41

  course_id           course_name
0     CS101  Intro to Programming
1   MATH201           Calculus II
2    ENG110      Academic Writing

In [222]:
df42 = pd.read_csv(r"C:\Users\chahat\Downloads\enrollments.csv")
df42

  student_id course_id
0         S1     CS101
1         S1   MATH201
2         S2     CS101
3         S2    ENG110
4         S3   MATH201
5         S3    ENG110

In [223]:
df43 = pd.merge(df20,df21,on='dept_id',validate='many_to_many')

In [224]:
df43

,employee_id,name,dept_id,location,salary,id_x,dept_name,manager,id_y
0,101,Alice,D1,New York,72000,1,Sales,Mike Johnson,1
1,102,Bob,D2,Los Angeles,65000,2,Marketing,Sarah Lee,2
2,103,Charlie,D3,New York,80000,3,IT,Tom Brown,3
3,106,Frank,NaN,Chicago,58000,6,NaN,NaN,6
4,105,Eva,D1,New York,69000,5,Sales,Mike Johnson,1
5,106,Frank,NaN,Chicago,58000,6,NaN,NaN,8
6,107,Grace,D2,Los Angeles,62000,7,Marketing,Sarah Lee,2
7,106,Frank,NaN,Chicago,58000,6,NaN,NaN,7

In [225]:
df44 = pd.read_csv(r"C:\Users\chahat\Downloads\sales_data (1).csv")
df44

,OrderID,Date,Region,Category,Product,Salesperson,Channel,Quantity,UnitPrice,Sales,Profit
0,1001,2024-01-01,East,Furniture,Desk,John,Online,8,154.76,1238.08,516.79
1,1002,2024-01-02,North,Grocery,Dairy,John,Online,8,10.66,85.28,34.75
2,1003,2024-01-04,East,Electronics,Smartphone,Fatima,Retail Store,10,502.57,5025.70,2089.00
3,1004,2024-01-04,South,Electronics,Smartphone,Fatima,Online,11,458.79,5046.69,1457.62
4,1005,2024-01-05,North,Electronics,Smartphone,John,Retail Store,5,512.98,2564.90,1043.24
...,...,...,...,...,...,...,...,...,...,...,...
196,1197,2024-06-28,West,Clothing,T-Shirt,Aarav,Retail Store,9,13.51,121.59,46.61
197,1198,2024-06-28,South,Grocery,Rice,Aarav,Online,8,19.94,159.52,52.06
198,1199,2024-06-29,West,Electronics,Laptop,John,Online,10,690.88,6908.80,2143.12
199,1200,2024-06-29,North,Clothing,Shoes,Aarav,Online,10,60.22,602.20,151.04
200,1201,2024-06-30,South,Furniture,Desk,Fatima,Online,8,153.93,1231.44,358.40

In [226]:
df44.pivot_table(
    values='Profit',
    index = 'Category',
    columns = 'Salesperson',
    aggfunc = 'mean')

Salesperson,Aarav,Fatima,John,Maria,Priya,Wei
Category,,,,,,
Clothing,121.296667,108.175000,79.953571,139.075000,96.010000,84.820000
Electronics,799.813846,1082.868125,887.840000,993.187778,1193.680000,431.008889
Furniture,600.655714,962.516667,455.347778,236.835000,443.474444,557.344444
Grocery,34.482222,16.581429,19.321250,15.207500,26.480000,20.771818

In [227]:
df44.pivot_table(
    values = 'Sales',
    index = 'Product',
    columns = 'Salesperson',
    aggfunc = ['max','min']
)

                 max                                                   min  \
Salesperson    Aarav   Fatima     John    Maria    Priya      Wei    Aarav
Product
Beverages      49.04     6.07    54.99      NaN    69.96    16.56    49.04
Bookshelf     257.62      NaN   494.16  1345.52  1315.93   835.87   257.62
Chair          89.92   388.28   543.96   360.36   860.40   967.80    89.92
Dairy            NaN    60.48    85.28    51.40      NaN   105.40      NaN
Desk         1718.97  1231.44  1313.92  1484.90   486.36  1280.64   568.92
Headphones    842.10   812.20   536.48   686.96      NaN   769.05   159.54
Jacket        749.65   427.62   608.96   746.24   712.40   486.36   619.29
Jeans          80.40   386.73   388.30   219.85   163.96   363.87    38.90
Laptop       6382.40  5694.32  6908.80  6141.76  4767.49      NaN  1500.80
Rice          175.50    18.54   141.19    63.87   145.44   144.41    18.06
Shoes         602.20   434.00   321.30      NaN   551.70   272.65   509.58
Smartphone   5603.51  5450.40  5224.80  3063.48  2615.50  3691.36   532.45
Snacks         59.44    87.20    16.06    49.98    68.80    89.65    59.44
Sofa         5445.00  7034.17  5606.19      NaN  3942.26  3946.02  1832.73
T-Shirt       179.85   178.86   122.67   147.70    62.84    82.62   121.59
Tablet       1403.65  1919.89  3160.52  1620.15  2547.28   296.54   606.82


Salesperson   Fatima     John    Maria    Priya      Wei
Product
Beverages       6.07    28.10      NaN    69.96     5.77
Bookshelf        NaN   494.16   386.94   476.08   597.55
Chair         388.28   246.60   167.98   860.40   967.80
Dairy          18.72    31.74    29.28      NaN    39.72
Desk          326.34   298.12   150.90   152.61   823.70
Headphones    415.40   229.05   686.96      NaN   172.56
Jacket         63.91   406.50   323.40   712.40    72.12
Jeans         315.76   307.51   219.85   120.48   363.87
Laptop        807.05  2889.72  2374.71  3712.90      NaN
Rice           18.21    19.53    63.87   115.02   144.41
Shoes         320.70    49.90      NaN   305.64   272.65
Smartphone    536.99  2564.90  1968.68  2615.50   902.60
Snacks         83.00    16.06    49.98    21.81     7.42
Sofa         5747.58   604.02      NaN  2761.50  3895.68
T-Shirt       178.86    42.78   147.70    62.84    82.62
Tablet       1901.62   619.50   935.58  2547.28   296.54

In [228]:
df44.pivot_table(
    values = 'Profit',
    index = 'Region',
    columns = 'Category',
    aggfunc = 'sum',
    margins=True
)

Category  Clothing  Electronics  Furniture  Grocery       All
Region
East        518.51     17118.11    7300.55     5.93  24943.10
North      1199.78     16142.56    9592.25   297.66  27232.25
South      1386.06      7103.68    6550.63   430.71  15471.08
West       1528.53     17381.37    1062.77   268.40  20241.07
All        4632.88     57745.72   24506.20  1002.70  87887.50

In [229]:
df44.pivot_table(
    values = 'Sales',
    index = 'Product',
    columns = 'Salesperson',
    aggfunc = ['max','min'],
    fill_value = 0
)

                 max                                                   min  \
Salesperson    Aarav   Fatima     John    Maria    Priya      Wei    Aarav
Product
Beverages      49.04     6.07    54.99     0.00    69.96    16.56    49.04
Bookshelf     257.62     0.00   494.16  1345.52  1315.93   835.87   257.62
Chair          89.92   388.28   543.96   360.36   860.40   967.80    89.92
Dairy           0.00    60.48    85.28    51.40     0.00   105.40     0.00
Desk         1718.97  1231.44  1313.92  1484.90   486.36  1280.64   568.92
Headphones    842.10   812.20   536.48   686.96     0.00   769.05   159.54
Jacket        749.65   427.62   608.96   746.24   712.40   486.36   619.29
Jeans          80.40   386.73   388.30   219.85   163.96   363.87    38.90
Laptop       6382.40  5694.32  6908.80  6141.76  4767.49     0.00  1500.80
Rice          175.50    18.54   141.19    63.87   145.44   144.41    18.06
Shoes         602.20   434.00   321.30     0.00   551.70   272.65   509.58
Smartphone   5603.51  5450.40  5224.80  3063.48  2615.50  3691.36   532.45
Snacks         59.44    87.20    16.06    49.98    68.80    89.65    59.44
Sofa         5445.00  7034.17  5606.19     0.00  3942.26  3946.02  1832.73
T-Shirt       179.85   178.86   122.67   147.70    62.84    82.62   121.59
Tablet       1403.65  1919.89  3160.52  1620.15  2547.28   296.54   606.82


Salesperson   Fatima     John    Maria    Priya      Wei
Product
Beverages       6.07    28.10     0.00    69.96     5.77
Bookshelf       0.00   494.16   386.94   476.08   597.55
Chair         388.28   246.60   167.98   860.40   967.80
Dairy          18.72    31.74    29.28     0.00    39.72
Desk          326.34   298.12   150.90   152.61   823.70
Headphones    415.40   229.05   686.96     0.00   172.56
Jacket         63.91   406.50   323.40   712.40    72.12
Jeans         315.76   307.51   219.85   120.48   363.87
Laptop        807.05  2889.72  2374.71  3712.90     0.00
Rice           18.21    19.53    63.87   115.02   144.41
Shoes         320.70    49.90     0.00   305.64   272.65
Smartphone    536.99  2564.90  1968.68  2615.50   902.60
Snacks         83.00    16.06    49.98    21.81     7.42
Sofa         5747.58   604.02     0.00  2761.50  3895.68
T-Shirt       178.86    42.78   147.70    62.84    82.62
Tablet       1901.62   619.50   935.58  2547.28   296.54

In [230]:
df44.pivot_table(
    values = 'Profit',
    index = ['Channel','Region'],
    columns = 'Category',
    aggfunc = 'sum',
    margins=True
)

Category             Clothing  Electronics  Furniture  Grocery       All
Channel      Region
Online       East      518.51      9075.81    6506.38     5.93  16106.63
             North     876.23      7768.15    5286.22   221.21  14151.81
             South    1113.61      6250.74    3580.70   282.91  11227.96
             West     1177.73     10753.40        NaN   144.62  12075.75
Retail Store East         NaN      8042.30     794.17      NaN   8836.47
             North     323.55      8374.41    4306.03    76.45  13080.44
             South     272.45       852.94    2969.93   147.80   4243.12
             West      350.80      6627.97    1062.77   123.78   8165.32
All                   4632.88     57745.72   24506.20  1002.70  87887.50

In [231]:
pd.crosstab(
    index = df44['Category'],
    columns = df44['Channel']
)

Channel      Online  Retail Store
Category
Clothing         33            13
Electronics      38            27
Furniture        27            19
Grocery          29            15

In [232]:
pd.crosstab(
    index = df44['Category'],
    columns = df44['Channel'],
    normalize = 'columns'
)

Channel        Online  Retail Store
Category
Clothing     0.259843      0.175676
Electronics  0.299213      0.364865
Furniture    0.212598      0.256757
Grocery      0.228346      0.202703

In [233]:
pd.crosstab(
    index = df44['Category'],
    columns = df44['Channel'],
    normalize = 'index'
)

Channel        Online  Retail Store
Category
Clothing     0.717391      0.282609
Electronics  0.584615      0.415385
Furniture    0.586957      0.413043
Grocery      0.659091      0.340909

In [234]:
pd.crosstab(
    index = df44['Category'],
    columns = df44['Channel'],
    margins = True
)

Channel      Online  Retail Store  All
Category
Clothing         33            13   46
Electronics      38            27   65
Furniture        27            19   46
Grocery          29            15   44
All             127            74  201

In [235]:
df44['Date'] = pd.to_datetime(df44['Date'])

In [236]:
df44['Month'] = df44['Date'].dt.month

In [237]:
df44

,OrderID,Date,Region,Category,Product,Salesperson,Channel,Quantity,UnitPrice,Sales,Profit,Month
0,1001,2024-01-01,East,Furniture,Desk,John,Online,8,154.76,1238.08,516.79,1
1,1002,2024-01-02,North,Grocery,Dairy,John,Online,8,10.66,85.28,34.75,1
2,1003,2024-01-04,East,Electronics,Smartphone,Fatima,Retail Store,10,502.57,5025.70,2089.00,1
3,1004,2024-01-04,South,Electronics,Smartphone,Fatima,Online,11,458.79,5046.69,1457.62,1
4,1005,2024-01-05,North,Electronics,Smartphone,John,Retail Store,5,512.98,2564.90,1043.24,1
...,...,...,...,...,...,...,...,...,...,...,...,...
196,1197,2024-06-28,West,Clothing,T-Shirt,Aarav,Retail Store,9,13.51,121.59,46.61,6
197,1198,2024-06-28,South,Grocery,Rice,Aarav,Online,8,19.94,159.52,52.06,6
198,1199,2024-06-29,West,Electronics,Laptop,John,Online,10,690.88,6908.80,2143.12,6
199,1200,2024-06-29,North,Clothing,Shoes,Aarav,Online,10,60.22,602.20,151.04,6
200,1201,2024-06-30,South,Furniture,Desk,Fatima,Online,8,153.93,1231.44,358.40,6

In [238]:
df44.pivot_table(
    index = 'Month',
    columns = ['Region','Category'],
    values = 'Sales',
    aggfunc = 'sum'
)

Region       East                                  North              \
Category Clothing Electronics Furniture Grocery Clothing Electronics
Month
1          388.30     8849.04   9931.66     NaN   359.55     8015.30
2          746.24         NaN   5606.19     NaN   608.96    11195.16
3           38.90     3359.48   3511.66     NaN   879.04     9077.57
4             NaN    14711.92    979.41     NaN   253.77     4870.57
5             NaN    10495.60   1132.88   16.56   551.70     8561.16
6          132.52     7242.93    298.12     NaN  1073.30     2889.72

Region                        South                                   West  \
Category Furniture Grocery Clothing Electronics Furniture Grocery Clothing
Month
1           967.80   85.28   943.40     5046.69   2162.70  222.09   899.14
2          4063.66     NaN   593.35         NaN    257.62  176.67    82.25
3          6603.71  292.20    73.52     7219.82   5469.81  158.63   427.62
4              NaN  189.55  1105.65     5628.72   4922.72  136.65   609.91
5          7034.17  195.41  1049.83     1374.12   5447.87  123.67  1000.93
6          5747.58  101.20      NaN     1968.68   1231.44  403.07  1323.06

Region
Category Electronics Furniture Grocery
Month
1            8672.18       NaN  240.63
2            5720.06       NaN   34.12
3            2543.40       NaN  105.40
4            3331.48   3946.02   39.72
5            5009.34       NaN  267.27
6           22139.23       NaN   49.04

In [239]:
df44.pivot_table(
    index = ['Region','Channel'],
    columns = 'Category',
    values = 'Profit',
    aggfunc = 'sum',
    fill_value = 0
)

Category             Clothing  Electronics  Furniture  Grocery
Region Channel
East   Online          518.51      9075.81    6506.38     5.93
       Retail Store      0.00      8042.30     794.17     0.00
North  Online          876.23      7768.15    5286.22   221.21
       Retail Store    323.55      8374.41    4306.03    76.45
South  Online         1113.61      6250.74    3580.70   282.91
       Retail Store    272.45       852.94    2969.93   147.80
West   Online         1177.73     10753.40       0.00   144.62
       Retail Store    350.80      6627.97    1062.77   123.78

In [240]:
df44.melt(
    id_vars = 'OrderID',
    var_name = 'Category',
    value_name = 'Value'
)

      OrderID Category                Value
0        1001     Date  2024-01-01 00:00:00
1        1002     Date  2024-01-02 00:00:00
2        1003     Date  2024-01-04 00:00:00
3        1004     Date  2024-01-04 00:00:00
4        1005     Date  2024-01-05 00:00:00
...       ...      ...                  ...
2206     1197    Month                    6
2207     1198    Month                    6
2208     1199    Month                    6
2209     1200    Month                    6
2210     1201    Month                    6

[2211 rows x 3 columns]

In [241]:
df44.pivot(
    index = 'OrderID',
    columns = 'Category',
    values = 'Profit'
)

Category  Clothing  Electronics  Furniture  Grocery
OrderID
1001           NaN          NaN     516.79      NaN
1002           NaN          NaN        NaN    34.75
1003           NaN      2089.00        NaN      NaN
1004           NaN      1457.62        NaN      NaN
1005           NaN      1043.24        NaN      NaN
...            ...          ...        ...      ...
1197         46.61          NaN        NaN      NaN
1198           NaN          NaN        NaN    52.06
1199           NaN      2143.12        NaN      NaN
1200        151.04          NaN        NaN      NaN
1201           NaN          NaN     358.40      NaN

[201 rows x 4 columns]

In [242]:
df44.stack()

0    OrderID                     1001
     Date         2024-01-01 00:00:00
     Region                      East
     Category               Furniture
     Product                     Desk
                         ...
200  Quantity                       8
     UnitPrice                 153.93
     Sales                    1231.44
     Profit                     358.4
     Month                          6
Length: 2412, dtype: object

In [243]:
df44.unstack()

OrderID  0      1001
         1      1002
         2      1003
         3      1004
         4      1005
                ...
Month    196       6
         197       6
         198       6
         199       6
         200       6
Length: 2412, dtype: object

In [244]:
df44.melt(id_vars = 'Category' )

         Category variable value
0       Furniture  OrderID  1001
1         Grocery  OrderID  1002
2     Electronics  OrderID  1003
3     Electronics  OrderID  1004
4     Electronics  OrderID  1005
...           ...      ...   ...
2206     Clothing    Month     6
2207      Grocery    Month     6
2208  Electronics    Month     6
2209     Clothing    Month     6
2210    Furniture    Month     6

[2211 rows x 3 columns]

In [245]:
df45 = pd.read_csv(r"C:\Users\chahat\Downloads\datetime_operations_dataset.csv")
df45

,order_id,customer_name,product,category,quantity,unit_price,total_amount,order_date,ship_date,delivery_date,return_date
0,1001,Alice Johnson,Laptop,Electronics,1,75000.0,75000.0,2022-01-05,2022-01-07,2022-01-10,NaN
1,1002,Bob Smith,Office Chair,Furniture,2,8500.0,17000.0,2022-01-12,2022-01-14,2022-01-18,NaN
2,1003,Carol Williams,Notebook Pack,Stationery,10,150.0,1500.0,2022-02-03,2022-02-04,2022-02-06,NaN
3,1004,David Brown,Smartphone,Electronics,1,45000.0,45000.0,2022-02-14,2022-02-16,2022-02-20,NaN
4,1005,Eva Davis,Desk Lamp,Furniture,3,1200.0,3600.0,2022-03-01,2022-03-03,2022-03-07,NaN
5,1006,Frank Miller,Headphones,Electronics,2,3500.0,7000.0,2022-03-22,2022-03-24,2022-03-28,NaN
6,1007,Grace Wilson,Monitor,Electronics,1,22000.0,22000.0,2022-04-05,2022-04-07,2022-04-12,NaN
7,1008,Henry Moore,Pen Set,Stationery,20,80.0,1600.0,2022-04-19,2022-04-20,2022-04-23,NaN
8,1009,Isla Taylor,Bookshelf,Furniture,1,12000.0,12000.0,2022-05-08,2022-05-11,2022-05-16,NaN
9,1010,Jake Anderson,Keyboard,Electronics,1,2800.0,2800.0,2022-05-25,2022-05-27,2022-05-31,NaN
10,1011,Karen Thomas,Filing Cabinet,Furniture,1,9500.0,9500.0,2022-06-10,2022-06-13,2022-06-17,NaN
11,1012,Liam Jackson,USB Hub,Electronics,4,900.0,3600.0,2022-06-28,2022-06-29,2022-07-02,NaN
12,1013,Mia Harris,Stapler,Stationery,5,350.0,1750.0,2022-07-04,2022-07-05,2022-07-08,NaN
13,1014,Noah Martin,Webcam,Electronics,1,4500.0,4500.0,2022-07-19,2022-07-21,2022-07-25,NaN
14,1015,Olivia Garcia,Ergonomic Chair,Furniture,1,18000.0,18000.0,2022-08-02,2022-08-05,2022-08-10,NaN
15,1016,Paul Martinez,Tablet,Electronics,1,32000.0,32000.0,2022-08-14,2022-08-16,2022-08-20,NaN
16,1017,Quinn Robinson,Highlighters,Stationery,15,60.0,900.0,2022-09-01,2022-09-02,2022-09-05,NaN
17,1018,Rachel Clark,Printer,Electronics,1,15000.0,15000.0,2022-09-18,2022-09-20,2022-09-25,NaN
18,1019,Sam Rodriguez,Side Table,Furniture,2,4500.0,9000.0,2022-10-06,2022-10-08,2022-10-13,NaN
19,1020,Tina Lewis,Mouse,Electronics,2,1200.0,2400.0,2022-10-23,2022-10-25,2022-10-29,NaN
20,1021,Uma Lee,Whiteboard,Stationery,1,2800.0,2800.0,2022-11-07,2022-11-09,2022-11-14,NaN
21,1022,Victor Walker,Smart Speaker,Electronics,1,6500.0,6500.0,2022-11-24,2022-11-26,2022-11-30,NaN
22,1023,Wendy Hall,Wardrobe,Furniture,1,28000.0,28000.0,2022-12-05,2022-12-08,2022-12-14,NaN
23,1024,Xavier Allen,Sticky Notes,Stationery,30,40.0,1200.0,2022-12-20,2022-12-21,2022-12-24,NaN
24,1025,Yara Young,SSD Drive,Electronics,2,5500.0,11000.0,2023-01-09,2023-01-11,2023-01-15,NaN
25,1026,Zoe Hernandez,Coffee Table,Furniture,1,11000.0,11000.0,2023-01-26,2023-01-29,2023-02-03,NaN
26,1027,Aaron King,Notebook,Stationery,8,120.0,960.0,2023-02-13,2023-02-14,2023-02-17,NaN
27,1028,Bella Wright,Smart TV,Electronics,1,55000.0,55000.0,2023-02-28,2023-03-02,2023-03-07,NaN
28,1029,Carlos Scott,Sofa,Furniture,1,38000.0,38000.0,2023-03-14,2023-03-17,2023-03-22,NaN
29,1030,Diana Green,Pen Drive,Electronics,5,800.0,4000.0,2023-03-29,2023-03-30,2023-04-02,NaN
30,1031,Ethan Adams,Scissors,Stationery,6,200.0,1200.0,2023-04-10,2023-04-11,2023-04-14,2023-04-20
31,1032,Fiona Baker,Gaming Chair,Furniture,1,21000.0,21000.0,2023-04-25,2023-04-28,2023-05-03,NaN
32,1033,George Carter,Router,Electronics,1,3200.0,3200.0,2023-05-12,2023-05-14,2023-05-18,NaN
33,1034,Hannah Evans,Desk Organizer,Stationery,4,650.0,2600.0,2023-05-29,2023-05-30,2023-06-02,NaN
34,1035,Ian Foster,Dining Table,Furniture,1,45000.0,45000.0,2023-06-14,2023-06-17,2023-06-22,NaN
35,1036,Julia Gray,Power Bank,Electronics,3,2200.0,6600.0,2023-06-30,2023-07-01,2023-07-05,NaN
36,1037,Kevin Hill,Ruler Set,Stationery,12,90.0,1080.0,2023-07-11,2023-07-12,2023-07-15,NaN
37,1038,Laura Irwin,Air Purifier,Electronics,1,12000.0,12000.0,2023-07-28,2023-07-30,2023-08-03,NaN
38,1039,Mike James,Recliner,Furniture,1,32000.0,32000.0,2023-08-09,2023-08-13,2023-08-18,NaN
39,1040,Nina Kelly,Calculator,Electronics,2,1500.0,3000.0,2023-08-25,2023-08-27,2023-08-31,NaN
40,1041,Oscar Lane,Tape Rolls,Stationery,25,30.0,750.0,2023-09-06,2023-09-07,2023-09-10,NaN
41,1042,Paula Mason,Smartwatch,Electronics,1,18000.0,18000.0,2023-09-22,2023-09-24,2023-09-28,NaN
42,1043,Quincy Nash,Bed Frame,Furniture,1,25000.0,25000.0,2023-10-07,2023-10-10,2023-10-15,NaN
43,1044,Rosa Owen,Color Pens,Stationery,20,75.0,1500.0,2023-10-24,2023-10-25,2023-10-28,NaN
44,1045,Steve Price,Earbuds,Electronics,2,4000.0,8000.0,2023-11-08,2023-11-10,2023-11-14,NaN
45,1046,Tara Quinn,Study Desk,Furniture,1,16000.0,16000.0,2023-11-25,2023-11-28,2023-12-03,NaN
46,1047,Umar Reed,Hard Drive,Electronics,1,6000.0,6000.0,2023-12-09,2023-12-11,2023-12-15,NaN
47,1048,Vera Shaw,Index Cards,Stationery,50,20.0,1000.0,2023-12-21,2023-12-22,2023-12-26,NaN
48,1049,Will Turner,Electric Kettle,Electronics,1,2500.0,2500.0,2024-01-08,2024-01-09,2024-01-13,NaN
49,1050,Xena Underhill,Bar Stool,Furniture,4,3800.0,15200.0,2024-01-23,2024-01-25,2024-01-30,NaN
50,1051,Yusuf Vance,Projector,Electronics,1,35000.0,35000.0,2024-02-07,2024-02-09,2024-02-14,NaN
51,1052,Zara Wade,Glue Sticks,Stationery,40,25.0,1000.0,2024-02-22,2024-02-23,2024-02-26,NaN
52,1053,Adam Xavier,Ceiling Fan,Electronics,2,8500.0,17000.0,2024-03-05,2024-03-07,2024-03-12,NaN
53,1054,Bella Yates,Wardrobe,Furniture,1,31000.0,31000.0,2024-03-19,2024-03-22,2024-03-27,NaN
54,1055,Chris Zimmer,Webcam,Electronics,1,4800.0,4800.0,2024-04-03,2024-04-05,2024-04-09,NaN
55,1056,Diana Aaron,Pencil Box,Stationery,15,110.0,1650.0,2024-04-18,2024-04-19,2024-04-22,NaN
56,1057,Evan Bell,Mixer Grinder,Electronics,1,5500.0,5500.0,2024-05-02,2024-05-04,2024-05-08,NaN
57,1058,Fay Cole,Bean Bag,Furniture,2,7500.0,15000.0,2024-05-17,2024-05-19,2024-05-24,NaN
58,1059,Greg Dean,Laptop Stand,Electronics,1,1800.0,1800.0,2024-06-01,2024-06-02,2024-06-05,2024-06-12
59,1060,Hannah Ellis,Glue Bottle,Stationery,30,45.0,1350.0,2024-06-20,2024-06-21,2024-06-24,NaN

In [246]:
df45['order_date'] = pd.to_datetime(df45['order_date'])

In [247]:
df45['ship_date'] = pd.to_datetime(df45['ship_date'])

In [248]:
df45['delivery_date'] = pd.to_datetime(df45['delivery_date'])

In [249]:
df45['order_day'] = df45['order_date'].dt.day

In [250]:
df45['order_month'] = df45['order_date'].dt.month

In [251]:
df45['order_year'] = df45['order_date'].dt.year

In [252]:
df45['order_weekday'] = df45['order_date'].dt.day_name()

In [253]:
df45['order_quarter'] = df45['order_date'].dt.quarter

In [254]:
df45[df45['order_month'] == 3]

,order_id,customer_name,product,category,quantity,unit_price,total_amount,order_date,ship_date,delivery_date,return_date,order_day,order_month,order_year,order_weekday,order_quarter
4,1005,Eva Davis,Desk Lamp,Furniture,3,1200.0,3600.0,2022-03-01,2022-03-03,2022-03-07,NaN,1,3,2022,Tuesday,1
5,1006,Frank Miller,Headphones,Electronics,2,3500.0,7000.0,2022-03-22,2022-03-24,2022-03-28,NaN,22,3,2022,Tuesday,1
28,1029,Carlos Scott,Sofa,Furniture,1,38000.0,38000.0,2023-03-14,2023-03-17,2023-03-22,NaN,14,3,2023,Tuesday,1
29,1030,Diana Green,Pen Drive,Electronics,5,800.0,4000.0,2023-03-29,2023-03-30,2023-04-02,NaN,29,3,2023,Wednesday,1
52,1053,Adam Xavier,Ceiling Fan,Electronics,2,8500.0,17000.0,2024-03-05,2024-03-07,2024-03-12,NaN,5,3,2024,Tuesday,1
53,1054,Bella Yates,Wardrobe,Furniture,1,31000.0,31000.0,2024-03-19,2024-03-22,2024-03-27,NaN,19,3,2024,Tuesday,1

In [255]:
df45['order_diff'] = df45['order_date'].diff().dt.days

In [256]:
df45

,order_id,customer_name,product,category,quantity,unit_price,total_amount,order_date,ship_date,delivery_date,return_date,order_day,order_month,order_year,order_weekday,order_quarter,order_diff
0,1001,Alice Johnson,Laptop,Electronics,1,75000.0,75000.0,2022-01-05,2022-01-07,2022-01-10,NaN,5,1,2022,Wednesday,1,NaN
1,1002,Bob Smith,Office Chair,Furniture,2,8500.0,17000.0,2022-01-12,2022-01-14,2022-01-18,NaN,12,1,2022,Wednesday,1,7.0
2,1003,Carol Williams,Notebook Pack,Stationery,10,150.0,1500.0,2022-02-03,2022-02-04,2022-02-06,NaN,3,2,2022,Thursday,1,22.0
3,1004,David Brown,Smartphone,Electronics,1,45000.0,45000.0,2022-02-14,2022-02-16,2022-02-20,NaN,14,2,2022,Monday,1,11.0
4,1005,Eva Davis,Desk Lamp,Furniture,3,1200.0,3600.0,2022-03-01,2022-03-03,2022-03-07,NaN,1,3,2022,Tuesday,1,15.0
5,1006,Frank Miller,Headphones,Electronics,2,3500.0,7000.0,2022-03-22,2022-03-24,2022-03-28,NaN,22,3,2022,Tuesday,1,21.0
6,1007,Grace Wilson,Monitor,Electronics,1,22000.0,22000.0,2022-04-05,2022-04-07,2022-04-12,NaN,5,4,2022,Tuesday,2,14.0
7,1008,Henry Moore,Pen Set,Stationery,20,80.0,1600.0,2022-04-19,2022-04-20,2022-04-23,NaN,19,4,2022,Tuesday,2,14.0
8,1009,Isla Taylor,Bookshelf,Furniture,1,12000.0,12000.0,2022-05-08,2022-05-11,2022-05-16,NaN,8,5,2022,Sunday,2,19.0
9,1010,Jake Anderson,Keyboard,Electronics,1,2800.0,2800.0,2022-05-25,2022-05-27,2022-05-31,NaN,25,5,2022,Wednesday,2,17.0
10,1011,Karen Thomas,Filing Cabinet,Furniture,1,9500.0,9500.0,2022-06-10,2022-06-13,2022-06-17,NaN,10,6,2022,Friday,2,16.0
11,1012,Liam Jackson,USB Hub,Electronics,4,900.0,3600.0,2022-06-28,2022-06-29,2022-07-02,NaN,28,6,2022,Tuesday,2,18.0
12,1013,Mia Harris,Stapler,Stationery,5,350.0,1750.0,2022-07-04,2022-07-05,2022-07-08,NaN,4,7,2022,Monday,3,6.0
13,1014,Noah Martin,Webcam,Electronics,1,4500.0,4500.0,2022-07-19,2022-07-21,2022-07-25,NaN,19,7,2022,Tuesday,3,15.0
14,1015,Olivia Garcia,Ergonomic Chair,Furniture,1,18000.0,18000.0,2022-08-02,2022-08-05,2022-08-10,NaN,2,8,2022,Tuesday,3,14.0
15,1016,Paul Martinez,Tablet,Electronics,1,32000.0,32000.0,2022-08-14,2022-08-16,2022-08-20,NaN,14,8,2022,Sunday,3,12.0
16,1017,Quinn Robinson,Highlighters,Stationery,15,60.0,900.0,2022-09-01,2022-09-02,2022-09-05,NaN,1,9,2022,Thursday,3,18.0
17,1018,Rachel Clark,Printer,Electronics,1,15000.0,15000.0,2022-09-18,2022-09-20,2022-09-25,NaN,18,9,2022,Sunday,3,17.0
18,1019,Sam Rodriguez,Side Table,Furniture,2,4500.0,9000.0,2022-10-06,2022-10-08,2022-10-13,NaN,6,10,2022,Thursday,4,18.0
19,1020,Tina Lewis,Mouse,Electronics,2,1200.0,2400.0,2022-10-23,2022-10-25,2022-10-29,NaN,23,10,2022,Sunday,4,17.0
20,1021,Uma Lee,Whiteboard,Stationery,1,2800.0,2800.0,2022-11-07,2022-11-09,2022-11-14,NaN,7,11,2022,Monday,4,15.0
21,1022,Victor Walker,Smart Speaker,Electronics,1,6500.0,6500.0,2022-11-24,2022-11-26,2022-11-30,NaN,24,11,2022,Thursday,4,17.0
22,1023,Wendy Hall,Wardrobe,Furniture,1,28000.0,28000.0,2022-12-05,2022-12-08,2022-12-14,NaN,5,12,2022,Monday,4,11.0
23,1024,Xavier Allen,Sticky Notes,Stationery,30,40.0,1200.0,2022-12-20,2022-12-21,2022-12-24,NaN,20,12,2022,Tuesday,4,15.0
24,1025,Yara Young,SSD Drive,Electronics,2,5500.0,11000.0,2023-01-09,2023-01-11,2023-01-15,NaN,9,1,2023,Monday,1,20.0
25,1026,Zoe Hernandez,Coffee Table,Furniture,1,11000.0,11000.0,2023-01-26,2023-01-29,2023-02-03,NaN,26,1,2023,Thursday,1,17.0
26,1027,Aaron King,Notebook,Stationery,8,120.0,960.0,2023-02-13,2023-02-14,2023-02-17,NaN,13,2,2023,Monday,1,18.0
27,1028,Bella Wright,Smart TV,Electronics,1,55000.0,55000.0,2023-02-28,2023-03-02,2023-03-07,NaN,28,2,2023,Tuesday,1,15.0
28,1029,Carlos Scott,Sofa,Furniture,1,38000.0,38000.0,2023-03-14,2023-03-17,2023-03-22,NaN,14,3,2023,Tuesday,1,14.0
29,1030,Diana Green,Pen Drive,Electronics,5,800.0,4000.0,2023-03-29,2023-03-30,2023-04-02,NaN,29,3,2023,Wednesday,1,15.0
30,1031,Ethan Adams,Scissors,Stationery,6,200.0,1200.0,2023-04-10,2023-04-11,2023-04-14,2023-04-20,10,4,2023,Monday,2,12.0
31,1032,Fiona Baker,Gaming Chair,Furniture,1,21000.0,21000.0,2023-04-25,2023-04-28,2023-05-03,NaN,25,4,2023,Tuesday,2,15.0
32,1033,George Carter,Router,Electronics,1,3200.0,3200.0,2023-05-12,2023-05-14,2023-05-18,NaN,12,5,2023,Friday,2,17.0
33,1034,Hannah Evans,Desk Organizer,Stationery,4,650.0,2600.0,2023-05-29,2023-05-30,2023-06-02,NaN,29,5,2023,Monday,2,17.0
34,1035,Ian Foster,Dining Table,Furniture,1,45000.0,45000.0,2023-06-14,2023-06-17,2023-06-22,NaN,14,6,2023,Wednesday,2,16.0
35,1036,Julia Gray,Power Bank,Electronics,3,2200.0,6600.0,2023-06-30,2023-07-01,2023-07-05,NaN,30,6,2023,Friday,2,16.0
36,1037,Kevin Hill,Ruler Set,Stationery,12,90.0,1080.0,2023-07-11,2023-07-12,2023-07-15,NaN,11,7,2023,Tuesday,3,11.0
37,1038,Laura Irwin,Air Purifier,Electronics,1,12000.0,12000.0,2023-07-28,2023-07-30,2023-08-03,NaN,28,7,2023,Friday,3,17.0
38,1039,Mike James,Recliner,Furniture,1,32000.0,32000.0,2023-08-09,2023-08-13,2023-08-18,NaN,9,8,2023,Wednesday,3,12.0
39,1040,Nina Kelly,Calculator,Electronics,2,1500.0,3000.0,2023-08-25,2023-08-27,2023-08-31,NaN,25,8,2023,Friday,3,16.0
40,1041,Oscar Lane,Tape Rolls,Stationery,25,30.0,750.0,2023-09-06,2023-09-07,2023-09-10,NaN,6,9,2023,Wednesday,3,12.0
41,1042,Paula Mason,Smartwatch,Electronics,1,18000.0,18000.0,2023-09-22,2023-09-24,2023-09-28,NaN,22,9,2023,Friday,3,16.0
42,1043,Quincy Nash,Bed Frame,Furniture,1,25000.0,25000.0,2023-10-07,2023-10-10,2023-10-15,NaN,7,10,2023,Saturday,4,15.0
43,1044,Rosa Owen,Color Pens,Stationery,20,75.0,1500.0,2023-10-24,2023-10-25,2023-10-28,NaN,24,10,2023,Tuesday,4,17.0
44,1045,Steve Price,Earbuds,Electronics,2,4000.0,8000.0,2023-11-08,2023-11-10,2023-11-14,NaN,8,11,2023,Wednesday,4,15.0
45,1046,Tara Quinn,Study Desk,Furniture,1,16000.0,16000.0,2023-11-25,2023-11-28,2023-12-03,NaN,25,11,2023,Saturday,4,17.0
46,1047,Umar Reed,Hard Drive,Electronics,1,6000.0,6000.0,2023-12-09,2023-12-11,2023-12-15,NaN,9,12,2023,Saturday,4,14.0
47,1048,Vera Shaw,Index Cards,Stationery,50,20.0,1000.0,2023-12-21,2023-12-22,2023-12-26,NaN,21,12,2023,Thursday,4,12.0
48,1049,Will Turner,Electric Kettle,Electronics,1,2500.0,2500.0,2024-01-08,2024-01-09,2024-01-13,NaN,8,1,2024,Monday,1,18.0
49,1050,Xena Underhill,Bar Stool,Furniture,4,3800.0,15200.0,2024-01-23,2024-01-25,2024-01-30,NaN,23,1,2024,Tuesday,1,15.0
50,1051,Yusuf Vance,Projector,Electronics,1,35000.0,35000.0,2024-02-07,2024-02-09,2024-02-14,NaN,7,2,2024,Wednesday,1,15.0
51,1052,Zara Wade,Glue Sticks,Stationery,40,25.0,1000.0,2024-02-22,2024-02-23,2024-02-26,NaN,22,2,2024,Thursday,1,15.0
52,1053,Adam Xavier,Ceiling Fan,Electronics,2,8500.0,17000.0,2024-03-05,2024-03-07,2024-03-12,NaN,5,3,2024,Tuesday,1,12.0
53,1054,Bella Yates,Wardrobe,Furniture,1,31000.0,31000.0,2024-03-19,2024-03-22,2024-03-27,NaN,19,3,2024,Tuesday,1,14.0
54,1055,Chris Zimmer,Webcam,Electronics,1,4800.0,4800.0,2024-04-03,2024-04-05,2024-04-09,NaN,3,4,2024,Wednesday,2,15.0
55,1056,Diana Aaron,Pencil Box,Stationery,15,110.0,1650.0,2024-04-18,2024-04-19,2024-04-22,NaN,18,4,2024,Thursday,2,15.0
56,1057,Evan Bell,Mixer Grinder,Electronics,1,5500.0,5500.0,2024-05-02,2024-05-04,2024-05-08,NaN,2,5,2024,Thursday,2,14.0
57,1058,Fay Cole,Bean Bag,Furniture,2,7500.0,15000.0,2024-05-17,2024-05-19,2024-05-24,NaN,17,5,2024,Friday,2,15.0
58,1059,Greg Dean,Laptop Stand,Electronics,1,1800.0,1800.0,2024-06-01,2024-06-02,2024-06-05,2024-06-12,1,6,2024,Saturday,2,15.0
59,1060,Hannah Ellis,Glue Bottle,Stationery,30,45.0,1350.0,2024-06-20,2024-06-21,2024-06-24,NaN,20,6,2024,Thursday,2,19.0

In [257]:
df45['order_prev_date'] = df45['order_date'].shift(1)

In [259]:
df45['order_next_date'] = df45['order_date'].shift(-1)

In [269]:
df45.groupby('order_month')['total_amount'].sum()

order_month
1     131700.0
2     138460.0
3     100600.0
4      52250.0
5      41100.0
6      67850.0
7      19330.0
8      85000.0
9      34650.0
10     37900.0
11     33300.0
12     36200.0
Name: total_amount, dtype: float64

In [270]:
df46 = pd.read_csv(r"C:\Users\chahat\Downloads\window_functions_dataset.csv")
df46

,date,store_id,product,sales,revenue,temperature,stock_price,units_sold,discount_pct,region
0,2024-01-01,1,Apple,150,4500.0,22.5,145.3,150,5,North
1,2024-01-02,1,Apple,175,5250.0,23.1,146.2,175,5,North
2,2024-01-03,1,Apple,200,6000.0,21.8,144.8,200,8,North
3,2024-01-04,1,Apple,130,3900.0,20.5,147.5,130,3,North
4,2024-01-05,1,Apple,210,6300.0,24.0,149.0,210,10,North
5,2024-01-06,1,Apple,185,5550.0,22.3,148.2,185,7,North
6,2024-01-07,1,Apple,220,6600.0,25.1,150.1,220,12,North
7,2024-01-08,1,Apple,195,5850.0,23.7,151.3,195,6,North
8,2024-01-09,1,Apple,240,7200.0,26.0,152.0,240,15,North
9,2024-01-10,1,Apple,260,7800.0,27.2,153.5,260,10,North
10,2024-01-11,1,Apple,170,5100.0,21.0,152.8,170,4,North
11,2024-01-12,1,Apple,230,6900.0,24.8,154.2,230,9,North
12,2024-01-13,1,Apple,250,7500.0,26.5,155.0,250,11,North
13,2024-01-14,1,Apple,280,8400.0,28.0,156.4,280,13,North
14,2024-01-15,1,Apple,300,9000.0,29.3,157.8,300,15,North
15,2024-01-01,2,Banana,90,1800.0,22.5,145.3,90,2,South
16,2024-01-02,2,Banana,110,2200.0,23.1,146.2,110,3,South
17,2024-01-03,2,Banana,95,1900.0,21.8,144.8,95,2,South
18,2024-01-04,2,Banana,120,2400.0,20.5,147.5,120,5,South
19,2024-01-05,2,Banana,130,2600.0,24.0,149.0,130,6,South
20,2024-01-06,2,Banana,105,2100.0,22.3,148.2,105,3,South
21,2024-01-07,2,Banana,140,2800.0,25.1,150.1,140,7,South
22,2024-01-08,2,Banana,115,2300.0,23.7,151.3,115,4,South
23,2024-01-09,2,Banana,150,3000.0,26.0,152.0,150,8,South
24,2024-01-10,2,Banana,160,3200.0,27.2,153.5,160,9,South
25,2024-01-11,2,Banana,100,2000.0,21.0,152.8,100,2,South
26,2024-01-12,2,Banana,145,2900.0,24.8,154.2,145,7,South
27,2024-01-13,2,Banana,155,3100.0,26.5,155.0,155,8,South
28,2024-01-14,2,Banana,170,3400.0,28.0,156.4,170,10,South
29,2024-01-15,2,Banana,180,3600.0,29.3,157.8,180,11,South
30,2024-01-01,3,Cherry,60,3000.0,22.5,145.3,60,0,East
31,2024-01-02,3,Cherry,75,3750.0,23.1,146.2,75,0,East
32,2024-01-03,3,Cherry,55,2750.0,21.8,144.8,55,0,East
33,2024-01-04,3,Cherry,80,4000.0,20.5,147.5,80,5,East
34,2024-01-05,3,Cherry,90,4500.0,24.0,149.0,90,5,East
35,2024-01-06,3,Cherry,70,3500.0,22.3,148.2,70,0,East
36,2024-01-07,3,Cherry,95,4750.0,25.1,150.1,95,8,East
37,2024-01-08,3,Cherry,65,3250.0,23.7,151.3,65,0,East
38,2024-01-09,3,Cherry,100,5000.0,26.0,152.0,100,10,East
39,2024-01-10,3,Cherry,110,5500.0,27.2,153.5,110,10,East
40,2024-01-11,3,Cherry,50,2500.0,21.0,152.8,50,0,East
41,2024-01-12,3,Cherry,105,5250.0,24.8,154.2,105,8,East
42,2024-01-13,3,Cherry,115,5750.0,26.5,155.0,115,10,East
43,2024-01-14,3,Cherry,125,6250.0,28.0,156.4,125,12,East
44,2024-01-15,3,Cherry,135,6750.0,29.3,157.8,135,15,East

In [271]:
df46.groupby('product')['sales'].rolling(3).mean()

product
Apple    0            NaN
         1            NaN
         2     175.000000
         3     168.333333
         4     180.000000
         5     175.000000
         6     205.000000
         7     200.000000
         8     218.333333
         9     231.666667
         10    223.333333
         11    220.000000
         12    216.666667
         13    253.333333
         14    276.666667
Banana   15           NaN
         16           NaN
         17     98.333333
         18    108.333333
         19    115.000000
         20    118.333333
         21    125.000000
         22    120.000000
         23    135.000000
         24    141.666667
         25    136.666667
         26    135.000000
         27    133.333333
         28    156.666667
         29    168.333333
Cherry   30           NaN
         31           NaN
         32     63.333333
         33     70.000000
         34     75.000000
         35     80.000000
         36     85.000000
         37     76.666667
         38     86.666667
         39     91.666667
         40     86.666667
         41     88.333333
         42     90.000000
         43    115.000000
         44    125.000000
Name: sales, dtype: float64

In [272]:
df46.groupby('product')['sales'].rolling(3).sum()

product
Apple    0       NaN
         1       NaN
         2     525.0
         3     505.0
         4     540.0
         5     525.0
         6     615.0
         7     600.0
         8     655.0
         9     695.0
         10    670.0
         11    660.0
         12    650.0
         13    760.0
         14    830.0
Banana   15      NaN
         16      NaN
         17    295.0
         18    325.0
         19    345.0
         20    355.0
         21    375.0
         22    360.0
         23    405.0
         24    425.0
         25    410.0
         26    405.0
         27    400.0
         28    470.0
         29    505.0
Cherry   30      NaN
         31      NaN
         32    190.0
         33    210.0
         34    225.0
         35    240.0
         36    255.0
         37    230.0
         38    260.0
         39    275.0
         40    260.0
         41    265.0
         42    270.0
         43    345.0
         44    375.0
Name: sales, dtype: float64

In [273]:
df46.groupby('product')['sales'].rolling(3).max()

product
Apple    0       NaN
         1       NaN
         2     200.0
         3     200.0
         4     210.0
         5     210.0
         6     220.0
         7     220.0
         8     240.0
         9     260.0
         10    260.0
         11    260.0
         12    250.0
         13    280.0
         14    300.0
Banana   15      NaN
         16      NaN
         17    110.0
         18    120.0
         19    130.0
         20    130.0
         21    140.0
         22    140.0
         23    150.0
         24    160.0
         25    160.0
         26    160.0
         27    155.0
         28    170.0
         29    180.0
Cherry   30      NaN
         31      NaN
         32     75.0
         33     80.0
         34     90.0
         35     90.0
         36     95.0
         37     95.0
         38    100.0
         39    110.0
         40    110.0
         41    110.0
         42    115.0
         43    125.0
         44    135.0
Name: sales, dtype: float64

In [274]:
df46.groupby('product')['sales'].rolling(3).min()

product
Apple    0       NaN
         1       NaN
         2     150.0
         3     130.0
         4     130.0
         5     130.0
         6     185.0
         7     185.0
         8     195.0
         9     195.0
         10    170.0
         11    170.0
         12    170.0
         13    230.0
         14    250.0
Banana   15      NaN
         16      NaN
         17     90.0
         18     95.0
         19     95.0
         20    105.0
         21    105.0
         22    105.0
         23    115.0
         24    115.0
         25    100.0
         26    100.0
         27    100.0
         28    145.0
         29    155.0
Cherry   30      NaN
         31      NaN
         32     55.0
         33     55.0
         34     55.0
         35     70.0
         36     70.0
         37     65.0
         38     65.0
         39     65.0
         40     50.0
         41     50.0
         42     50.0
         43    105.0
         44    115.0
Name: sales, dtype: float64

In [275]:
df46.groupby('product')['sales'].expanding().mean()

product
Apple    0     150.000000
         1     162.500000
         2     175.000000
         3     163.750000
         4     173.000000
         5     175.000000
         6     181.428571
         7     183.125000
         8     189.444444
         9     196.500000
         10    194.090909
         11    197.083333
         12    201.153846
         13    206.785714
         14    213.000000
Banana   15     90.000000
         16    100.000000
         17     98.333333
         18    103.750000
         19    109.000000
         20    108.333333
         21    112.857143
         22    113.125000
         23    117.222222
         24    121.500000
         25    119.545455
         26    121.666667
         27    124.230769
         28    127.500000
         29    131.000000
Cherry   30     60.000000
         31     67.500000
         32     63.333333
         33     67.500000
         34     72.000000
         35     71.666667
         36     75.000000
         37     73.750000
         38     76.666667
         39     80.000000
         40     77.272727
         41     79.583333
         42     82.307692
         43     85.357143
         44     88.666667
Name: sales, dtype: float64

In [276]:
df46.groupby('product')['sales'].expanding().sum()

product
Apple    0      150.0
         1      325.0
         2      525.0
         3      655.0
         4      865.0
         5     1050.0
         6     1270.0
         7     1465.0
         8     1705.0
         9     1965.0
         10    2135.0
         11    2365.0
         12    2615.0
         13    2895.0
         14    3195.0
Banana   15      90.0
         16     200.0
         17     295.0
         18     415.0
         19     545.0
         20     650.0
         21     790.0
         22     905.0
         23    1055.0
         24    1215.0
         25    1315.0
         26    1460.0
         27    1615.0
         28    1785.0
         29    1965.0
Cherry   30      60.0
         31     135.0
         32     190.0
         33     270.0
         34     360.0
         35     430.0
         36     525.0
         37     590.0
         38     690.0
         39     800.0
         40     850.0
         41     955.0
         42    1070.0
         43    1195.0
         44    1330.0
Name: sales, dtype: float64

In [277]:
df46.groupby('product')['sales'].cumsum()

0      150
1      325
2      525
3      655
4      865
5     1050
6     1270
7     1465
8     1705
9     1965
10    2135
11    2365
12    2615
13    2895
14    3195
15      90
16     200
17     295
18     415
19     545
20     650
21     790
22     905
23    1055
24    1215
25    1315
26    1460
27    1615
28    1785
29    1965
30      60
31     135
32     190
33     270
34     360
35     430
36     525
37     590
38     690
39     800
40     850
41     955
42    1070
43    1195
44    1330
Name: sales, dtype: int64

In [278]:
df46.groupby('product')['sales'].cummax()

0     150
1     175
2     200
3     200
4     210
5     210
6     220
7     220
8     240
9     260
10    260
11    260
12    260
13    280
14    300
15     90
16    110
17    110
18    120
19    130
20    130
21    140
22    140
23    150
24    160
25    160
26    160
27    160
28    170
29    180
30     60
31     75
32     75
33     80
34     90
35     90
36     95
37     95
38    100
39    110
40    110
41    110
42    115
43    125
44    135
Name: sales, dtype: int64

In [281]:
df46.groupby('product')['sales'].shift(1)

0       NaN
1     150.0
2     175.0
3     200.0
4     130.0
5     210.0
6     185.0
7     220.0
8     195.0
9     240.0
10    260.0
11    170.0
12    230.0
13    250.0
14    280.0
15      NaN
16     90.0
17    110.0
18     95.0
19    120.0
20    130.0
21    105.0
22    140.0
23    115.0
24    150.0
25    160.0
26    100.0
27    145.0
28    155.0
29    170.0
30      NaN
31     60.0
32     75.0
33     55.0
34     80.0
35     90.0
36     70.0
37     95.0
38     65.0
39    100.0
40    110.0
41     50.0
42    105.0
43    115.0
44    125.0
Name: sales, dtype: float64

In [282]:
df46.groupby('product')['sales'].shift(-1)

0     175.0
1     200.0
2     130.0
3     210.0
4     185.0
5     220.0
6     195.0
7     240.0
8     260.0
9     170.0
10    230.0
11    250.0
12    280.0
13    300.0
14      NaN
15    110.0
16     95.0
17    120.0
18    130.0
19    105.0
20    140.0
21    115.0
22    150.0
23    160.0
24    100.0
25    145.0
26    155.0
27    170.0
28    180.0
29      NaN
30     75.0
31     55.0
32     80.0
33     90.0
34     70.0
35     95.0
36     65.0
37    100.0
38    110.0
39     50.0
40    105.0
41    115.0
42    125.0
43    135.0
44      NaN
Name: sales, dtype: float64

In [283]:
df47 = pd.read_csv(r"C:\Users\chahat\Downloads\advanced_pandas_dataset.csv")
df47

,transaction_id,customer_id,customer_name,age,gender,country,city,product_id,product_name,category,...,purchase_date,delivery_date,return_flag,return_reason,rating,review_text,support_tickets,days_since_last_purchase,total_past_orders,clv_score
0,TXN000001,CUST0001,Alice Johnson,28,Female,India,Mumbai,PROD001,Wireless Headphones,Electronics,...,2024-01-01,2024-01-05,False,NaN,5,Great product,0.0,15.0,24.0,8750.5
1,TXN000002,CUST0002,Bob Smith,35,Male,India,Delhi,PROD002,Running Shoes,Footwear,...,2024-01-01,2024-01-04,False,NaN,4,Good quality,1.0,30.0,12.0,4200.0
2,TXN000003,CUST0003,Carol White,22,Female,India,Bangalore,PROD003,Cotton Kurta,Clothing,...,3,Average,0,5,3,950.25,NaN,NaN,NaN,NaN
3,TXN000004,CUST0004,David Lee,45,Male,India,Hyderabad,PROD004,Air Fryer,Kitchen,...,2024-01-02,2024-01-06,False,NaN,5,Excellent,0.0,60.0,45.0,22000.0
4,TXN000005,CUST0005,Eva Brown,31,Female,India,Chennai,PROD005,Yoga Mat,Sports,...,4,Very good,0,20,8,3100.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,TXN000096,CUST0088,Kavita Pandey,46,Female,India,Aligarh,PROD095,Wheat Flour,Grocery,...,2024-01-28,2024-02-01,False,NaN,4,Good quality atta,0.0,55.0,21.0,7700.0
96,TXN000097,CUST0089,Lokesh Pillai,32,Male,India,Palakkad,PROD096,Resistance Bands,Sports,...,4,Good elasticity,0,8,6,2200.00,NaN,NaN,NaN,NaN
97,TXN000098,CUST0090,Meena Devi,63,Female,India,Patna,PROD097,Ayurvedic Syrup,Health,...,5,Feel rejuvenated,0,120,8,2800.00,NaN,NaN,NaN,NaN
98,TXN000099,CUST0091,Nitin Bose,29,Male,India,Durgapur,PROD098,USB Hub,Electronics,...,4,All ports work,0,13,5,1800.00,NaN,NaN,NaN,NaN
99,TXN000100,CUST0092,Omkar Kulkarni,36,Male,India,Pune,PROD099,Pressure Gauge,Automobile,...,2024-01-29,2024-02-01,False,NaN,4,Accurate reading,0.0,40.0,31.0,12500.0

In [284]:
df47.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   transaction_id            100 non-null    object
 1   customer_id               100 non-null    object
 2   customer_name             100 non-null    object
 3   age                       100 non-null    int64
 4   gender                    100 non-null    object
 5   country                   100 non-null    object
 6   city                      100 non-null    object
 7   product_id                100 non-null    object
 8   product_name              100 non-null    object
 9   category                  100 non-null    object
 10  sub_category              100 non-null    object
 11  brand                     100 non-null    object
 12  quantity                  100 non-null    int64
 13  unit_price                100 non-null    float64
 14  discount_pct              100 non-null    int64
 15  payment_method            100 non-null    object
 16  channel                   100 non-null    object
 17  device                    83 non-null     object
 18  os                        83 non-null     object
 19  browser                   83 non-null     object
 20  is_member                 100 non-null    object
 21  membership_tier           43 non-null     object
 22  purchase_date             100 non-null    object
 23  delivery_date             100 non-null    object
 24  return_flag               100 non-null    object
 25  return_reason             60 non-null     object
 26  rating                    100 non-null    int64
 27  review_text               100 non-null    object
 28  support_tickets           43 non-null     float64
 29  days_since_last_purchase  43 non-null     float64
 30  total_past_orders         40 non-null     float64
 31  clv_score                 40 non-null     float64
dtypes: float64(5), int64(4), object(23)
memory usage: 25.1+ KB

In [285]:
df47['age'] = df47['age'].astype('int8')

In [287]:
df47['quantity'] = df47['quantity'].astype('int8')

In [290]:
df47['unit_price'] = df47['unit_price'].astype('float16')

In [292]:
df47['discount_pct'] = df47['discount_pct'].astype('int8')

In [294]:
df47['rating'] = df47['rating'].astype('int8')

In [296]:
df47[['support_tickets','days_since_last_purchase',  
'total_past_orders','clv_score']] = df47[['support_tickets','days_since_last_purchase',  
'total_past_orders','clv_score']].astype('float16')

In [299]:
df47['category'] = df47['category'].astype('category')

In [306]:
z = []
for chunk in pd.read_csv(
    r"C:\Users\chahat\Downloads\advanced_pandas_dataset.csv",chunksize=10
):
    z.append(chunk)
z

[  transaction_id customer_id  customer_name  age  gender country       city  \
 0      TXN000001    CUST0001  Alice Johnson   28  Female   India     Mumbai
 1      TXN000002    CUST0002      Bob Smith   35    Male   India      Delhi
 2      TXN000003    CUST0003    Carol White   22  Female   India  Bangalore
 3      TXN000004    CUST0004      David Lee   45    Male   India  Hyderabad
 4      TXN000005    CUST0005      Eva Brown   31  Female   India    Chennai
 5      TXN000006    CUST0006      Frank Das   27    Male   India    Kolkata
 6      TXN000007    CUST0007    Grace Patel   38  Female   India       Pune
 7      TXN000008    CUST0008     Hank Kumar   52    Male   India  Ahmedabad
 8      TXN000009    CUST0009      Iris Nair   24  Female   India     Jaipur
 9      TXN000010    CUST0010      Jay Mehta   40    Male   India      Surat

   product_id         product_name     category  ... purchase_date  \
 0    PROD001  Wireless Headphones  Electronics  ...    2024-01-01
 1    PROD002        Running Shoes     Footwear  ...    2024-01-01
 2    PROD003         Cotton Kurta     Clothing  ...             3
 3    PROD004            Air Fryer      Kitchen  ...    2024-01-02
 4    PROD005             Yoga Mat       Sports  ...             4
 5    PROD006           Novels Set        Books  ...             2
 6    PROD007          Smart Watch  Electronics  ...    2024-01-03
 7    PROD008         Office Chair    Furniture  ...    2024-01-03
 8    PROD009           Face Serum       Beauty  ...             4
 9    PROD010        Mixer Grinder      Kitchen  ...    2024-01-04

    delivery_date  return_flag  return_reason  rating    review_text  \
 0     2024-01-05        False            NaN       5  Great product
 1     2024-01-04        False            NaN       4   Good quality
 2        Average            0              5       3         950.25
 3     2024-01-06        False            NaN       5      Excellent
 4      Very good            0             20       8        3100.00
 5  Disappointing            2             45       6        1800.00
 6     2024-01-07        False            NaN       5        Love it
 7     2024-01-10         True        Damaged       2             90
 8     Works well            0              7       5        2100.00
 9     2024-01-08        False            NaN       5       Must buy

   support_tickets days_since_last_purchase total_past_orders clv_score
 0             0.0                     15.0              24.0    8750.5
 1             1.0                     30.0              12.0    4200.0
 2             NaN                      NaN               NaN       NaN
 3             0.0                     60.0              45.0   22000.0
 4             NaN                      NaN               NaN       NaN
 5             NaN                      NaN               NaN       NaN
 6             0.0                     10.0              31.0   14500.0
 7            18.0                   9800.0               NaN       NaN
 8             NaN                      NaN               NaN       NaN
 9             0.0                     25.0              52.0   28000.0

 [10 rows x 32 columns],
    transaction_id customer_id  customer_name  age  gender country       city  \
 10      TXN000011    CUST0001  Alice Johnson   28  Female   India     Mumbai
 11      TXN000012    CUST0002      Bob Smith   35    Male   India      Delhi
 12      TXN000013    CUST0003    Carol White   22  Female   India  Bangalore
 13      TXN000014    CUST0011      Kevin Roy   33    Male   India    Lucknow
 14      TXN000015    CUST0012      Laura Sen   29  Female   India     Bhopal
 15      TXN000016    CUST0013     Mike Joshi   47    Male   India     Nagpur
 16      TXN000017    CUST0014     Nina Gupta   26  Female   India      Patna
 17      TXN000018    CUST0015      Oscar Rao   36    Male   India   Vadodara
 18      TXN000019    CUST0016    Priya Singh   43  Female   India     Rajkot
 19      TXN000020    CUST0017      Raj Verma   31    Male   India     Meerut

    product_id    product_name     category  ... purchase_date  \
 10    PROD011      Phone Case  Electronics  ...    2024-01-04
 11    PROD012  Protein Powder       Health  ...    2024-01-05
 12    PROD013           Jeans     Clothing  ...             5
 13    PROD004       Air Fryer      Kitchen  ...             4
 14    PROD014    Lipstick Set       Beauty  ...             3
 15    PROD015       Treadmill       Sports  ...    2024-01-06
 16    PROD016        Earrings    Jewellery  ...             4
 17    PROD017      Laptop Bag  Accessories  ...    2024-01-07
 18    PROD018    Cookware Set      Kitchen  ...    2024-01-07
 19    PROD019     Cricket Bat       Sports  ...             5

          delivery_date  return_flag  return_reason  rating    review_text  \
 10          2024-01-06        False            NaN       3           Okay
 11          2024-01-08        False            NaN       4           Good
 12         Perfect fit            0              5       4        1200.00
 13               Great            1             55       9        3800.00
 14     Average quality            0             12       7        2500.00
 15          2024-01-15        False            NaN       5  Life changing
 16           Beautiful            0              3       2         700.00
 17          2024-01-10        False            NaN       4        Durable
 18          2024-01-12         True     Wrong item       1             22
 19  Professional grade            0              8       6        2200.00

    support_tickets days_since_last_purchase total_past_orders clv_score
 10             0.0                     15.0              25.0    8900.5
 11             0.0                     30.0              13.0    4500.0
 12             NaN                      NaN               NaN       NaN
 13             NaN                      NaN               NaN       NaN
 14             NaN                      NaN               NaN       NaN
 15             0.0                    180.0              41.0   35000.0
 16             NaN                      NaN               NaN       NaN
 17             0.0                     40.0              19.0    7200.0
 18            28.0                  11500.0               NaN       NaN
 19             NaN                      NaN               NaN       NaN

 [10 rows x 32 columns],
    transaction_id customer_id customer_name  age  gender country        city  \
 20      TXN000021    CUST0018     Sara Khan   25  Female   India        Agra
 21      TXN000022    CUST0019    Tom Sharma   50    Male   India    Varanasi
 22      TXN000023    CUST0020    Uma Pillai   34  Female   India  Coimbatore
 23      TXN000024    CUST0021    Vijay Nair   28    Male   India       Kochi
 24      TXN000025    CUST0022      Wini Das   37  Female   India      Indore
 25      TXN000026    CUST0023      Xavi Roy   42    Male   India       Thane
 26      TXN000027    CUST0024    Yash Patel   23    Male   India      Nashik
 27      TXN000028    CUST0025      Zara Ali   30  Female   India  Aurangabad
 28      TXN000029    CUST0026     Arjun Rao   44    Male   India      Mysore
 29      TXN000030    CUST0027     Bhanu Lal   39    Male   India     Jodhpur

    product_id      product_name     category  ... purchase_date  \
 20    PROD020             Saree     Clothing  ...             4
 21    PROD021  Diabetic Monitor       Health  ...    2024-01-08
 22    PROD022        Hair Dryer       Beauty  ...             4
 23    PROD023        Sunglasses  Accessories  ...             3
 24    PROD024          Iron Box      Kitchen  ...    2024-01-09
 25    PROD025         Desk Lamp    Furniture  ...             4
 26    PROD026          Backpack  Accessories  ...             5
 27    PROD027           Perfume       Beauty  ...    2024-01-10
 28    PROD028        Dinner Set      Kitchen  ...    2024-01-10
 29    PROD029        Wall Clock    Furniture  ...             3

       delivery_date  return_flag  return_reason  rating    review_text  \
 20    Lovely fabric            0           14.0       4        1600.00
 21       2024-01-11        False            NaN       5  Very accurate
 22      Works great            0           18.0      10        3600.00
 23  Expected better            1            9.0       5        2000.00
 24       2024-01-12        False            NaN       4      Efficient
 25  Good brightness            0           50.0      11        4100.00
 26         Spacious            0            4.0       2         800.00
 27       2024-01-13        False            NaN       4     Nice scent
 28       2024-01-16        False            NaN       5        Elegant
 29           Decent            0           72.0       8        2900.00

    support_tickets days_since_last_purchase total_past_orders clv_score
 20             NaN                      NaN               NaN       NaN
 21             0.0                     35.0              22.0    8400.0
 22             NaN                      NaN               NaN       NaN
 23             NaN                      NaN               NaN       NaN
 24             0.0                     28.0              33.0   13000.0
 25             NaN                      NaN               NaN       NaN
 26             NaN                      NaN               NaN       NaN
 27             0.0                     20.0              16.0    6000.0
 28             0.0                     65.0              48.0   26000.0
 29             NaN                      NaN               NaN       NaN

 [10 rows x 32 columns],
    transaction_id customer_id  customer_name  age  gender country        city  \
 30      TXN000031    CUST0028     Charu Seth   27  Female   India     Udaipur
 31      TXN000032    CUST0029     Dev Tiwari   33    Male   India    Guwahati
 32      TXN000033    CUST0030     Ela Mishra   48  Female   India      Ranchi
 33      TXN000034    CUST0031  Farhan Ansari   36    Male   India      Raipur
 34      TXN000035    CUST0032    Geeta Yadav   55  Female   India    Amritsar
 35      TXN000036    CUST0033   Hari Chandra   29    Male   India    Ludhiana
 36      TXN000037    CUST0034    Isha Kapoor   24  Female   India   Faridabad
 37      TXN000038    CUST0035   Jatin Bansal   41    Male   India   Ghaziabad
 38      TXN000039    CUST0036    Kavya Reddy   32  Female   India  Vijayawada
 39      TXN000040    CUST0037     Lalit Jain   46    Male   India      Rajkot

    product_id            product_name     category  ... purchase_date  \
 30    PROD030                Nail Kit       Beauty  ...             4
 31    PROD031                Football       Sports  ...             4
 32    PROD032            Saree Blouse     Clothing  ...    2024-01-11
 33    PROD033            Gaming Mouse  Electronics  ...             5
 34    PROD034  Blood Pressure Monitor       Health  ...    2024-01-12
 35    PROD035       Bluetooth Speaker  Electronics  ...             4
 36    PROD036                   Kurti     Clothing  ...             4
 37    PROD037              Car Vacuum   Automobile  ...    2024-01-13
 38    PROD038             Moisturizer       Beauty  ...             4
 39    PROD039              Wall Paint         Home  ...    2024-01-14

       delivery_date  return_flag  return_reason  rating     review_text  \
 30  Love the colors            0              6       3         1100.00
 31     Good quality            0             16       7         2600.00
 32       2024-01-14        False            NaN       3  Okay stitching
 33    Smooth clicks            0             11       6         2300.00
 34       2024-01-15        False            NaN       5     Easy to use
 35   Loud and clear            0             19       9         3400.00
 36      Nice prints            0              2       2          750.00
 37       2024-01-18         True      Defective       3              27
 38       Non-greasy            0             13       8         2900.00
 39       2024-01-20        False            NaN       3   Good coverage

    support_tickets days_since_last_purchase total_past_orders clv_score
 30             NaN                      NaN               NaN       NaN
 31             NaN                      NaN               NaN       NaN
 32             1.0                     33.0              29.0   10500.0
 33             NaN                      NaN               NaN       NaN
 34             0.0                     42.0              20.0    7800.0
 35             NaN                      NaN               NaN       NaN
 36             NaN                      NaN               NaN       NaN
 37            30.0                  12000.0               NaN       NaN
 38             NaN                      NaN               NaN       NaN
 39             0.0                     50.0              21.0    7500.0

 [10 rows x 32 columns],
    transaction_id customer_id  customer_name  age  gender country  \
 40      TXN000041    CUST0038   Mona Agarwal   38  Female   India
 41      TXN000042    CUST0039  Naveen Pillai   26    Male   India
 42      TXN000043    CUST0040      Ojas Shah   35    Male   India
 43      TXN000044    CUST0041    Pooja Tomar   30  Female   India
 44      TXN000045    CUST0042     Qazi Hamid   53    Male   India
 45      TXN000046    CUST0043    Rita Saxena   28  Female   India
 46      TXN000047    CUST0044     Sonu Gupta   40    Male   India
 47      TXN000048    CUST0045     Tina Verma   22  Female   India
 48      TXN000049    CUST0046     Uday Sinha   37    Male   India
 49      TXN000050    CUST0047      Vani Bose   34  Female   India

            city product_id     product_name    category  ... purchase_date  \
 40      Jodhpur    PROD040  Pressure Cooker     Kitchen  ...    2024-01-14
 41    Mangalore    PROD041            Novel       Books  ...             4
 42  Gandhinagar    PROD042     Formal Shirt    Clothing  ...    2024-01-15
 43        Noida    PROD043       Eye Shadow      Beauty  ...             3
 44     Srinagar    PROD044            Shawl    Clothing  ...    2024-01-15
 45     Dehradun    PROD045      Sketch Pens  Stationery  ...             4
 46       Shimla    PROD046           Jacket    Clothing  ...    2024-01-16
 47   Chandigarh    PROD047            Kajal      Beauty  ...             4
 48        Patna    PROD048        Chess Set      Sports  ...             4
 49      Kolkata    PROD049          Dupatta    Clothing  ...    2024-01-17

        delivery_date  return_flag  return_reason  rating      review_text  \
 40        2024-01-18        False            NaN       5  Durable product
 41    Gripping story            0           21.0       5          1900.00
 42        2024-01-18        False            NaN       4        Fits well
 43  Color payoff low            0            8.0       6          2100.00
 44        2024-01-22        False            NaN       5        Authentic
 45    Vibrant colors            0            3.0       3           900.00
 46        2024-01-20        False            NaN       5        Very warm
 47      Long lasting            0            1.0       1           300.00
 48     Good material            0           60.0      10          3500.00
 49        2024-01-20        False            NaN       3      Fabric okay

    support_tickets days_since_last_purchase total_past_orders clv_score
 40             0.0                     38.0              34.0   14200.0
 41             NaN                      NaN               NaN       NaN
 42             0.0                     44.0              47.0   21000.0
 43             NaN                      NaN               NaN       NaN
 44             0.0                     90.0              17.0    6800.0
 45             NaN                      NaN               NaN       NaN
 46             0.0                     25.0              26.0   10100.0
 47             NaN                      NaN               NaN       NaN
 48             NaN                      NaN               NaN       NaN
 49             0.0                     17.0              15.0    5700.0

 [10 rows x 32 columns],
    transaction_id customer_id  customer_name  age  gender country  \
 50      TXN000051    CUST0048     Wasim Khan   49    Male   India
 51      TXN000052    CUST0049      Xena Nair   26  Female   India
 52      TXN000053    CUST0050      Yusuf Ali   31    Male   India
 53      TXN000054    CUST0001  Alice Johnson   28  Female   India
 54      TXN000055    CUST0010      Jay Mehta   40    Male   India
 55      TXN000056    CUST0051   Zobia Rahman   33  Female   India
 56      TXN000057    CUST0052  Aakash Tiwari   25    Male   India
 57      TXN000058    CUST0053    Bindiya Pal   44  Female   India
 58      TXN000059    CUST0054   Chetan Joshi   38    Male   India
 59      TXN000060    CUST0055   Divya Shukla   27  Female   India

              city product_id       product_name     category  ...  \
 50      Hyderabad    PROD050             Router  Electronics  ...
 51          Kochi    PROD051    Turmeric Powder      Grocery  ...
 52      Kozhikode    PROD052       Casual Shoes     Footwear  ...
 53         Mumbai    PROD053         HDMI Cable  Electronics  ...
 54          Surat    PROD054  Induction Cooktop      Kitchen  ...
 55        Lucknow    PROD055            Lehenga     Clothing  ...
 56    Bhubaneswar    PROD056            Headset  Electronics  ...
 57  Visakhapatnam    PROD057            Almonds      Grocery  ...
 58         Jaipur    PROD058            Trimmer     Grooming  ...
 59         Kanpur    PROD059              Flats     Footwear  ...

    purchase_date        delivery_date  return_flag  return_reason  rating  \
 50    2024-01-17           2024-01-21        False            NaN       5
 51             4          Fresh aroma            0            4.0       3
 52             3   Sole wore out fast            1           28.0       8
 53    2024-01-18           2024-01-20        False            NaN       4
 54    2024-01-18           2024-01-22        False            NaN       5
 55             5       Stunning piece            0          120.0       6
 56             5  Crystal clear audio            0            9.0       4
 57    2024-01-19           2024-01-22        False            NaN       4
 58             4    Good battery life            0           14.0      11
 59             3      Size runs small            1            6.0       4

          review_text support_tickets days_since_last_purchase  \
 50       Fast speeds             0.0                     36.0
 51           1000.00             NaN                      NaN
 52           2700.00             NaN                      NaN
 53        Works fine             0.0                     15.0
 54  Energy efficient             0.0                     25.0
 55           2400.00             NaN                      NaN
 56           1600.00             NaN                      NaN
 57   Fresh and tasty             0.0                     20.0
 58           4200.00             NaN                      NaN
 59           1400.00             NaN                      NaN

    total_past_orders clv_score
 50              32.0   13800.0
 51               NaN       NaN
 52               NaN       NaN
 53              26.0    9050.5
 54              53.0   28500.0
 55               NaN       NaN
 56               NaN       NaN
 57              23.0    8600.0
 58               NaN       NaN
 59               NaN       NaN

 [10 rows x 32 columns],
    transaction_id customer_id   customer_name  age  gender country       city  \
 60      TXN000061    CUST0016     Priya Singh   43  Female   India     Rajkot
 61      TXN000062    CUST0056   Esha Malhotra   35  Female   India  Faridabad
 62      TXN000063    CUST0057    Farida Begum   52  Female   India  Allahabad
 63      TXN000064    CUST0058  Gaurav Chauhan   29    Male   India    Gwalior
 64      TXN000065    CUST0059      Hema Dubey   41  Female   India   Jabalpur